### ISSUE TITLE
zrep 1.7.4 break on linux because of ln -n

### ISSUE THREAD

**Issue by kuon** [bolthole/zrep#104]
zrep 1.7.4 adds the following:

    LN_S="ln -n -s"

The ksh build on linux (archlinux with ksh 93v) will use a built in for `ln` which do not support `-n`.

The following error is returned:

```
ln: -n: unknown option
Usage: ln [-firRsuvFbxX] [-B[type]] [-S suffix] source destination
   Or: ln [ options ] file ... directory

```

A simple fix is to use `ln` full path, but I don't know if it's always there on all systems zrep supports:

    LN_S="/usr/bin/ln -n -s"

**Comment by ppbrown** [comment]
thanks for pointing that out.
Funnily enough, the latest github version of zrep doesnt use ln at all any
more. but I forgot to pull that reference.
So i'll remove it from the script.
havent gotten around to making an official 1.7.5 release but it should be
good to use.
