### ISSUE TITLE
Unsent snapshots piling up, filling up disk

### ISSUE THREAD

**Issue by ksalman** [bolthole/zrep#106]
We do zrep snapshots pretty frequently, every 5 minutes, and there is a lot of churn between one snapshot and the next. If the zrep sync fails for some reason, and keeps failing, zrep keeps creating new unsent snapshots on the source, and due to the churn the disk fills up pretty quickly.

Following is just an example of an empty dataset, but in a busy dataset each unsent snapshot takes enough that it fills the disk pretty quickly.
```
root@brigade:/root# zfs list -rt snapshot datapool/foobar
NAME                                 USED  AVAIL  REFER  MOUNTPOINT
datapool/foobar@zrep_000000             0      -  32.0K  -
datapool/foobar@zrep_000001             0      -  32.0K  -
datapool/foobar@zrep_000002             0      -  32.0K  -
datapool/foobar@zrep_000003             0      -  32.0K  -
datapool/foobar@zrep_000004_unsent      0      -  34.0K  -
datapool/foobar@zrep_000005_unsent      0      -  34.0K  -
datapool/foobar@zrep_000006_unsent      0      -  34.0K  -
datapool/foobar@zrep_000007_unsent      0      -  34.0K  -
```

I am not sure if there is a need for zrep to keep making new unsent snapshot while there is an existing one that it could send. Or possibly there can be an option to have zrep use the unsent it created previously, meaning there would be one unsent snapshot, ever.

**Comment by ppbrown** [comment]
HI,

I think you misunderstand how snapshots work.
Your disk probably isnt filling up due to the unsent. its more likely
filling up simply because of the difference between the last successfully
sent snapshot, and your current disk.

But, if you like, you could always just pause your zrep runs, and nuke all
the _unsent snapshots.

**Comment by ppbrown** [comment]
I just pushed a git update with a new tunable:
ZREP_RENAME_UNSENT

set it to "no", in your environment, and it should remove the failed
snapshots instead of renaming.
Lemme know how it works.

**Comment by ksalman** [comment]
Hello, it works as expected. Thank you for putting that in.
