### ISSUE TITLE
zrep sync interrupted and now I can't delete a snapshot (dataset is busy)

### ISSUE THREAD

**Issue by almoondsllc** [bolthole/zrep#107]

**Comment by ppbrown** [comment]
Hi.
that sounds like a ZFS level problem. you'll need to check with your "OS
vendor", so to speak.
Presuming you alerady did a "ps -ef" and you dont see any zrep or zfs
commands still lingering

**Comment by almoondsllc** [comment]
Infact it is :), the problem is I can't kill this orphan process with "kill -9 25557" :\
root     25557     1  0 gen17 ?        00:00:00 zfs send -w -I drevo/kvm-enc zrep_001255 drevo/kvm-enc zrep_001256
I would like avoid rebooting the server

**Comment by almoondsllc** [comment]
Thank you for your help, I solved just rebooting :)
