### ISSUE TITLE
Default to delete unsent snapshots

### ISSUE THREAD

**Issue by mlavkin** [bolthole/zrep#109]
Hi, we uses zrep about two years on FreeBSD.
Sometimes when zrep trying to rename snapshot system completly hangs.
This is bug https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227740 
My workaround it's to change rename to destroy on zrep code, but I think will be good to make option for select behavor of delete or rename.

**Comment by mlavkin** [comment]
Sorry, I found in last code 
ZREP_RENAME_UNSENT=${ZREP_RENAME_UNSENT:-yes}

**Comment by mlavkin** [comment]
Waiting for release!

**Comment by ppbrown** [comment]
Thank you for your interest in zrep!
Currently, official release is pending user feedback, from issues #65 and #49 
If you would like to speed things along, you might test out the features and let me know if it works cleanly.
