### ISSUE TITLE
After a failover, readonly is set incorrectly on new master

### ISSUE THREAD

**Issue by plantroon** [bolthole/zrep#111]
OS: Debian 9.8 with zfs-dkms from contrib
(src means source/master, dest means destination/slave in my description below)

Steps to reproduce this issue:
1. `export ZREP_R=-R` on both sides of replication
2. initialize zrep on dataset tank/users on src
3. `zfs create tank/users/test` on src
4. `zrep sync tank/users` on src
5. `zfs get readonly tank/users/test` on both sides, it should be set properly now (dest: on, inherited from tank/users; src: off, default)
6. `zrep failover tank/users` on src
7. `zfs get readonly tank/users/test` on both sides, it is incorrectly set on new src (dest: on, inherited from tank/users; src: on, temporary)

One needs to run zfs inherit readonly tank/users/test on new src and then it behaves correctly on every subsequent failover.

**Comment by ppbrown** [comment]
Hmm.
I*'m not entirely sure whether this is a bug in zrep, or bug in zfs.
readonly is a property.
by default, properties are supposed to be inherited from parent.

There is no "zfs set -R". 
zrep does the zfs set readonly on the parent.
So, when zrep does the set readonly, the sub zfs should automatically get set readonly as well.
If it doesnt.... its a bug in your ZFS implementation, right?

**Comment by plantroon** [comment]
I will test a newer ZFS version and report back in a few days.

What is strange is that after running zfs inherit readonly tank/users/test on new src it starts working correctly on the given dataset, on every subsequent failover. I have to do that for each new dataset created - this is not such a big deal because there will be maybe 5-6 created per year under this replicated dataset.

**Comment by ppbrown** [comment]
I wouldnt call it strange. I would call it "bugged zfs behaviour".
your manual call, restored proper zfs behaviour for the new filesystem.

**Comment by plantroon** [comment]
So you were right about bugged ZFS behaviour on Linux (tested ZFS on Linux  0.6.5.9-5 and 0.7.12-1). On FreeBSD 12 this does not happen for example. I will report this to ZFS on Linux devs if I get more useful details.

**Comment by ppbrown** [comment]
I think you have enough to report to zfs devs as is.
