### ISSUE TITLE
What happens when zfs recv fails?

### ISSUE THREAD

**Issue by Harvie** [bolthole/zrep#112]
https://github.com/bolthole/zrep/blob/93a0c9f68af3c4aa49d9725473227e0f2132187a/zrep_sync#L316

How do you know that sync was completed? If remote server undergoes (eg.) power outage, ssh will timeout and the script will continue without checking that snapshot was completely received...

At least from my understanding of the code.

**Comment by ppbrown** [comment]
Because of line 304.

"if [[ $? -ne 0 ]] ; then"

the ssh isnt in the background. it sits there until the sync is complete.
If the remote side crashes, then the ssh will timeout, which will return non-0 status.
$? is status of last command
