### ISSUE TITLE
zrep sync failing on MacOS openzfs

### ISSUE THREAD

**Issue by tgunr** [bolthole/zrep#113]
I just finished with
`zrep -i  tank/downloads localhost delta/downloads` and mounted it, looked good. 
Unmounted it and tried 
`zrep sync -v   tank/downloads`

result
`
sending tank/downloads@zrep_000002 to localhost:delta/downloads
send from @zrep_000001 to tank/downloads@zrep_000002 estimated size is 624
total estimated size is 624
TIME        SENT   SNAPSHOT
Expiring zrep snaps on tank/downloads
Also running expire on localhost:delta/downloads now...
Expiring zrep snaps on delta/downloads
Error: zrep:savecount on delta/downloads set to improper value -
REMOTE expire failed
`

**Comment by tgunr** [comment]
The result is the second attempt but first had same error.

**Comment by ppbrown** [comment]
You seem to have made a lot of mods to the code. I cant help you there.
There is no "total estimated size" or "TIME SENT" in the code, that I can see.

**Comment by tgunr** [comment]
I have made no changes to the code. I have checked out master branch commit 93a0c9f68af3c4aa49d9725473227e0f2132187a

**Comment by ppbrown** [comment]
please try it without -v

**Comment by ppbrown** [comment]
Hello,
any further feedback?  I'd like to help this.
BTW, it seems like the sync itself works fine. its just the post-sync cleanup that has an issue.

Im suspecting you have chosen to zero out the  savecount property manually, and that is causing the issue. 
it needs to be set to a number.

**Comment by ppbrown** [comment]
closing due to lack of feedback from reporter
