### ISSUE TITLE
zrep unsent snapshots on freebsd 12.0-RELEASE-p4

### ISSUE THREAD

**Issue by kristoferus75** [bolthole/zrep#115]
Hi !

I use zrep to snapshot jails and rrd datasets

But now are often unsent snapashots -> how can i figure out whats the problem ?

Yesterday a made a zrep job start manually but than the freebsd machine have no memory and no and so i need to made an hard reset !

the biggest rrd folder for snapshots have diff from on the day to other snapshot 20GB

i have also test mbuffer in .cshrc file and have installed mpuffer but no success :-(
and also i stopped the jails and then i start zrep -S .. in a script -> no success

```
set ZREP_OUTFILTER="mbuffer -q -m 1G -s 128k"
set ZREP_INFILTER="mbuffer -q -m 1G -s 128k"
```

Thanks

kind regards 

kristoferus75

**Comment by ppbrown** [comment]
Hello,
i'm afraid I probably cant really help you here.
You have a "my machine doesnt work" problem. There's almost an infinit number of reasons why it isnt working. you need to do some more detailed investigation yourself :)

sounds like you have a reoccuring memory problem though.
I would suggest
1. increasing amount of memory
2. getting detailed logging of both machines' memory usage. at least every 5 minutes, if not 1 minute.
That should help you diagnose what is going wrong with your systems.
