### ISSUE TITLE
When do ZREP and otherwise created snapshots really conflict?

### ISSUE THREAD

**Issue by ams-tschoening** [bolthole/zrep#119]
# Some background

I'm running two hosts serving VMs and am using ZREP to replicate those VMs to the other host regularly, without using any fail- or takeover currently. Hosts are simply restarted as needed with VMs shut down before. Additionally, each hosts backs its own VMs up using `rsync` to some external NAS.

# The problem

Because `rsync` might need a long time, each host creates an additional snapshot only for backup purposes and not following the naming scheme of ZREP. In the past it happened from time to time that ZREP got out of sync and ran into errors replicating all hosts, resulting in that all snapshots needed to be deleted and pools initially synced again, until the problem occurred again at some point. Because of that, using ZREP has been changed to additionally check if a special backup-snapshot is in place and to simply not run ZREP than.

While since then no more errors happened anymore, the time when ZREP actually doesn't run per day increased to many hours, depending on how long the backup takes. Because of the increasing VM-sizes, it's about 5 to 7 hours per day currently and I would like to get rid of that replication-whole. Sadly, I can't provide all details of the errors happened anymore, like concrete error messages, because a coworker implemented things and is not available anymore.

# Documented warnings

I've read the following in the [docs](http://www.bolthole.com/solaris/zrep/zrep.documentation.html#tuning):

> You CANNOT manually create snapshots on remote side, because then incremental repliation will fail, due to the target "not being the most recent snapshot"

The snapshots created per host for backups are always only for the pool for which the individual host is the master, so from my understanding the documented restriction is fulfilled. ZREP alone is caring about snapshots in the target/remote side. OTOH I read the following at the [troubleshooting page](http://www.bolthole.com/solaris/zrep/troubleshooting.html):

> Do note that you cannot just randomly create snapshots on both sides for this purpose. The snapshot on the target side, must have been created as a result of a zfs send/receive combination.[...]

That reads a bit like creating additional snapshots on the master is always a problem with only additionally mentioning the case when creating them on the target as well.

# Questions

So, can creating snapshots in our setup be considered safe regarding parallel usage of ZREP in theory?

If so, the problems we ran into might have some other root cause, only fixed using additional checks by accident. If our approach is not considered safe instead, we might get rid of creating additional snapshots following this advice of you:

> b) schedule 'clone' jobs on remote side.

What I didn't find yet regarding that approach is how that influences automatic cleanup of snapshots by ZREP. Clones need to be created based on snapshots and those snapshots are kept around until their depending clone gets deleted:

> Even though the clone is created somewhere else in the dataset hierarchy, the original snapshot cannot be destroyed as long as the clone exists.

https://docs.oracle.com/cd/E19253-01/819-5461/gbcxz/index.html

So what happens if I create a clone based on the most current ZREP-snapshot and ZREP can't cleanup that snapshot because `rsync` needs the clone for hours? Will it run into an error or clean the snapshots up some point later in time?

Thanks for clearing things up!

**Comment by ppbrown** [comment]
Hi Thorsten,
couple of things come to mind when I read your report.

1. Just because zrep fails.. shouldnt mean you then have to  have "all snapshots needed to be deleted and pools initially synced again". Either you are missing a few things in your ZFS understanding, or you are not communicating some crucial facts to me

2. Why not just run rsync off an existing zrep-created snapshot, instead of creating ANOTHER snapshot?
Even if it takes a full day to complete the rsync.. surely you are keeping your zrep snapshots longer than a day?

Finally, 
"So what happens if I create a clone based on the most current ZREP-snapshot and ZREP can't cleanup that snapshot because rsync needs the clone for hours?"
The whole point of creating a clone, is that if you fully complete the clone process.. it becomes COMPLETELY independant of the original filesystem. It doesnt care about the original filesystem, and the original filesystem doesnt care about it.

But I'd recommend you first try the other two things above, before resorting to clones.

**Comment by ams-tschoening** [comment]
> [...]Either you are missing a few things in your ZFS understanding, or you are not communicating some crucial facts to me

As said, I lack the details for the error occurred, but my coworker said that he needed to destroy snapshots and get ZREP through the initial setup process to get things working again.

> Why not just run rsync off an existing zrep-created snapshot, instead of creating ANOTHER snapshot?

The backup process included suspending VMs in the past and therefore was not properly aligned with concurrent `cron`-based execution of ZREP.  From our understanding of the docs our approach seemed to be OK, that's why I asked if it is or is known to break.

So, is it OK to manually create non-ZREP-named snapshots on the master or does it always break things? The docs aren't that clear to me regarding that point.

We might have missed the following approach from the docs as well or it might not have been available at that time:

    # pause database  
    zrep snaponly
    # resume database
    zrep synconly

But before reusing ZREP-managed snapshots, I would like to better understand how ZREP behaves regarding automatic cleanup after syncing.

> Even if it takes a full day to complete the rsync.. surely you are keeping your zrep snapshots longer than a day?

We simply leave that to ZREP defaults currently, so it's cleaning up old snapshots [directly after syncing](https://github.com/bolthole/zrep/blob/master/zrep_sync#L462) from my understanding. I only see the default of the last 5 snapshots as well.

	_snapandsync $srcfs $desthost $destfs
    [...]
	print Expiring zrep snaps on $srcfs
	_expire $srcfs

> The whole point of creating a clone, is that if you fully complete the clone process.. it becomes COMPLETELY independant of the original filesystem. It doesnt care about the original filesystem, and the original filesystem doesnt care about it.

But the snapshot on which the clone has been created needs to stay around and that snapshot would be managed by ZREP and ZREP would try to destroy it at some point. That even applies without any clone, but simply mounting a ZREP-managed snapshots:

ZREP is executing every 15 minutes using `cron` currently and backup using `rsync` might take hours to complete. So it's very likely that the snapshot I'm using for backup is more than the X snapshots ZREP keeps around by default.

From my understanding, ZREP would try to destroy it after some sync and couldn't because it is either still mounted or even cloned for the backup. That would at least result in error messages forwarded by `cron`, something like `dataset is busy`.  But looking at the code it doesn't seem to break ZREP, instead it would simply destroy it when not used anymore after some later sync.

    zfs destroy -r $snap

https://github.com/bolthole/zrep/blob/master/zrep_sync#L702

Is that correct?

I would like to avoid those error messages of course.

**Comment by ppbrown** [comment]
How is it that rsync takes hours to complete, yet zrep can complete its
runs in 15 minutes?

**Comment by ams-tschoening** [comment]
> How is it that rsync takes hours to complete, yet zrep can complete its runs in 15 minutes?

Is that really necessary to know to answer my questions? :-)

ZREP is used to replicate two equally powerful servers directly connected using 2*1 GBit ethernet with somewhat fast HDDs. Changes between two runs of ZREP are somewhat small compared to overall amount of storage consumed by the VMs. Very few GiBs of changed data most likely every 15 minutes, if at all.

`rsync` OTOH is used to backup all ~670 GiBs of data once per day to some far slower NAS and using delta-xfer as well as simply copying the whole files has proven to be equally slow in that setup. So `rsync` simply takes hours to complete and that's why I need to care about how ZREP behaves in case I reuse its own managed snapshots for some other purpose.

Or you are telling me it should be fine in theory to additionally create non-ZREP-managed snapshots on the master. From my understanding of sending incremental snapshots, I would have expected it to be OK, because ZREP [provides the last successful sent one and the new one to send now](https://github.com/bolthole/zrep/blob/master/zrep_sync#L293). Our own snapshot maybe created in between shouldn't interfere with that in theory, but we ran into problems for some reason in the past...

**Comment by ppbrown** [comment]
> How is it that rsync takes hours to complete, yet zrep can complete its runs in 15 minutes?
>
> Is that really necessary to know to answer my questions? :-)

yes. yes it is :-P

If you have a "much slower NAS",as you say, then using rsync can be
unnessessarily slow, even to just calculate what needs to be sent.
What you should probably do, is use "zfs diff" to calculate the files
changed between zrep snapshots, and then explicitly send those files
over.
This gives you two benefits:

1. it should complete in 15 minutes
2. you wont need to make any extra snapshots.

**Comment by ams-tschoening** [comment]
> What you should probably do, is use "zfs diff" to calculate the files changed between zrep snapshots, and then explicitly send those files over.

`rsync` runs only once a day, ZREP every 15 minutes storing 5 snapshots by default, so I can't use `zfs diff` to calculate changed files between `rsync` of yesterday and today. Additionally, `zfs diff` doesn't tell `rsync` which blocks of files have changed, so `rsync` still needs to transfer the whole file or calculate changed blocks since yesterday on its own. Both is equally slow in case of large VM-files with some of those being X00 GiB in size. And those are the ones `zfs diff` will output anyway, because while they might change a little only, they do so at least once per day.

While I appreciate the time you take to answer, this is really getting off-topic. My questions are more focussed than discussing different backup strategies in my opinion:

1. How does(/should?) ZREP behave with additional non-ZREP-managed snapshots in theory?
2. How does(/should?) ZREP behave with using its own managed snapshots longer than itself expects?

I additionally asked for ZFS and sending intermediate snapshots or not in general [elsewhere](https://serverfault.com/questions/976096/is-it-safe-to-send-zfs-snapshots-incrementally-ignoring-some-intermediate-snapsh).

**Comment by ppbrown** [comment]
The more (and more accurate) information you tell me, the better advice I
can give you.

Im giving you the advice I'm giving you, because something in your setup is
inherently broken. That is indicated by your comment that you felt the need
to completely blow away the ZFS replicated filesystem and reinitialize.

If your system wasnt broken, then what you are doing, should actually
already work. IF you described it accurately to me, which I suspect you
have not.

Seems like you left out important information.  Previously you told me that
your entire dataset was around  670 GiBs in size.
now you say that  you are backing up VM snapshots, and they tend to be "
X00 GiB in size"

As such, your entire secondary backup strategy is misguided. What you
should REALLY do, is change how you do the NAS backups.
rsyncs are relatively okay for decent speed media and pipes.
Differential zfs replication is good for slow media and pipes.  If you're
dead set on using both live filesystem rsync and zfs replication, seems
like the saner thing to do is swap locations. rsync to where you current
send ZFS, and zrep through the NAS pipe.

Most people using zrep in these situations, actually have a ZFS backed NAS,
so they use zrep natively to the NAS filesystem
(IE on top of  "Free NAS")

If you cant do that, then you might actually create a ZFS volume out of the
NAS share. Mount it on the current ZFS based fileshare (or heck, a
completely different new server), and then do an additional zfs
replication, using TAGS, as described in the documentation.

ALTERNATIVELY...
between zfs runs, you could pick the oldest snapshot on the master, and
instead of going through the zfs expire process... you could try renaming
it.
As far as zrep goes, that should look like an expire.
But you will then have a snapshot you can use for rsync.

**Comment by ams-tschoening** [comment]
> Im giving you the advice I'm giving you, because something in your setup is inherently broken.[...]

My setup is pretty standard, with the only question left why we ran into problems with ZREP in the past. While not blaming ZREP for anything, I just wanted to understand the possible root cause of those problems to reconsider the currently implemented workaround.

In the meantime I found some old messages that sound like they had to do with the problem, but am not sure:

    cannot receive incremental stream: most recent snapshot of zfs-pool/vbox/tori does not match incremental source
    cannot open 'zfs-pool/vbox/tori@zrep_0001b7': dataset does not exist

No idea what my coworker once did how exactly to run into those problems, I only see what I have currently and remember what he told me.

> If your system wasnt broken, then what you are doing, should actually already work.

That's what I think as well after looking at ZREP-sources and ZFS docs: ZREP in theory should care about custom snapshots as long as those don't follow its naming convention. ZFS OTOH should be able to calculate differences between two ZREP-managed snapshots regardless of any intermediate custom snapshots. So my backup-snapshot shouldn't harm in any way in theory.

Seems I'll simply re-allow that and see what happens.

> Previously you told me that your entire dataset was around  670 GiBs in size. now you say that  you are backing up VM snapshots, and they tend to be "X00 GiB in size"

There is no discrepancy: At one comment I was talking about the size of the entire dataset, at another of the size of individual files only, because only those are relevant to `rsync` and its delta-xfer algorithm. It makes a huge difference for that if files are small or not and some of my VM-files are huge.

> As such, your entire secondary backup strategy is misguided.[...]

I disagree, simply because the NAS doesn't support ZFS natively, using e.g. iSCSI has proven to be error prone in the past as well (most likely because of a lack of performance) and all of your other suggestions make the setup far more complex without any benefit in the end.

The point is that I should be able to create non-ZREP-managed snapshots for whatever reasons I like for how long I want and if that is possible or not is the main thing I was interested in. You said that should be possible, so I'm trying that again and see if things still break. Hopefully not.

> between zfs runs, you could pick the oldest snapshot on the master, and instead of going through the zfs expire process... you could try renaming it.

I would like to avoid dealing with ZREP-internals, that was one of the reasons creating a custom snapshot on our own. That approach doesn't work very well anyway with things like aligning snapshot creation and VM-suspending, so the better approach is to use `snaponly` and `synconly` like documented for e.g. databases, which guarantees most current data to backup.

But that led to the second question how ZREP behaves in case of mounting its own managed snapshots until expiration time and longer... It most likely simply [prints errors](https://github.com/bolthole/zrep/blob/master/zrep_sync#L702), so instead of renaming things and stuff I simply suggest to create a small wrapper around ZREP dealing with error messages and ignoring things not of interest. That would help me with in my opinion [unnecessary lock messages](https://github.com/bolthole/zrep/issues/92) as well in the version of ZREP I'm using currently.

But in the best case, the problems of the past simply won't occur anymore.

**Comment by ppbrown** [comment]
"cannot receive incremental stream: most recent snapshot of zfs-pool/vbox/tori does not match incremental source
cannot open 'zfs-pool/vbox/tori@zrep_0001b7': dataset does not exist"

yes, thats saying something on the receiving side removed a snapshot prematurely. Things are happening,or were happening, on your boxes, that you arent aware of.
Cant make "incremental snapshots", if the increment points have been tampered with.
