### ISSUE TITLE
zrep tags, for multiple destinations, are problematic

### ISSUE THREAD

**Issue by ksalman** [bolthole/zrep#12]
Since zrep now supports tags for multiple destinations, I have been taking advantage of this and syncing source with two destinations. But zrep sends all intermediary snapshots, using the -I opiton, https://github.com/bolthole/zrep/blob/master/zrep#L1138. The snaphsots created on the source look like this

    NAME                                     USED  AVAIL  REFER  MOUNTPOINT
    datapool/ops-spool@zrep-brigade_0000c0      0      -   773M  -
    datapool/ops-spool@zrep_0001e1              0      -   773M  -

Next when I do another zrep with zrep-brigade tag, it sends both zrep_0001e1 and zrep-brigade_0000c1, which is not what we want.

This would not be a big deal except that when it comes time to expiring old snapshots, say, for tag zrep-brigade, it only expires zrep-brigade snapshots, logically. And all the other zrep_xxx snapshots stick around, and keep accumulating. You could remove the -I option when doing a zfs send and I don't think removing it would affect zrep operation. I removed it in my local copy, and testing it, but wanted to create an issue if other folks want to see why zrep is sending and accumulating other tags, when doing multi-destination syncs.

**Comment by darkpixel** [comment]
I have the same issue.  I have zfs-auto-snapshot on Linux taking frequent snapshots (every 5 minutes) and storing them for 3 hours in case we need to rapidly roll back from yet another Cryptolocker infection on Windows shares.  zfs-auto-snapshot automatically handles expiring of old snapshots too, but by that time, zrep has replicated them off to my off-site backup target.  So I had to write a quick-and-dirty script to clear them all out.  It would be nice to be able to drop the -I option.  I don't think it would affect anything.

**Comment by ppbrown** [comment]
Ooops. I didnt consider the expiration issue.
FYI the simplest quickndirty  expire way would be to just run zrep from cron with
zrep -t yourothertag expire

but thats not particularly user friendly.

i think I might go with a polymorphic strategy.
On the one hand, I kinda like the "send all snapshots" default case thing.
On the other hand, obviously when you're doing multitarget snapshotting, this is bad.

So.. maybe change the incremental flag from -I to -i, but only if the tag is something other than the default "zrep" ?

What do you guys think?

**Comment by darkpixel** [comment]
That sounds like a great solution.  Maybe with CLI args to override what zrep thinks is best.  i.e. -I always send intermediate snapshots and -i force incremental.  Then if the user doesn't specify an option, zrep does what you described above.

**Comment by ppbrown** [comment]
i'm hesitant to use up an argument flag unless really important.
I dont forsee many people actually WANTING to change the behaviour.
If there are multiple requests, I'll reconsider.

**Comment by ksalman** [comment]
I like your suggestion of using -i for tags that aren't "zrep".

**Comment by ppbrown** [comment]
I'll probably allow for environment override but not commandline override.

**Comment by darkpixel** [comment]
Seems like a good compromise.  I just need a way to force zrep to not replicate all the snapshots.  I was going to take the route of hacking the source to replace the -I with -i.  On some machines I will only have one destination (offsite) rather than a local backup and an offsite backup, so I'd like to be able to force it.

In our case, there is about 200 MB of data churn every 5 minutes (when my normal snapshots are taken), but it's really just a few files that get written, then overwritten.  So the size difference between the zrep snapshots every ~90 minutes is still about 300 MB.  With -I I end up having to back up about 2.5 GB every hour instead of ~275 MB.

**Comment by onlime** [comment]
+1 command line override sounds like a good solution.

Please just don't change the default from -I to -i. We currently very much depend on the "zfs send -I" in zrep as we are pulling backups from a remote backup server using pve-zsync (ProxmoxVE) which creates snapshots with its own prefix - those need to be replicated as well, as backup always needs to be able to pick up from both host nodes. The -I in this case is very handy as we are running zrep very frequently.

**Comment by ppbrown** [comment]
Okay, zrep 1.5.2 uploaded to github, which does the polymorphic solution, and also allows use of ZREP_INC_FLAG override in environment

**Comment by ksalman** [comment]
Could you also do the same fix when setting tag with the -t option? I.e., if I use the the -t option to set a tag other then "zrep" it is still using -I flag.

**Comment by ppbrown** [comment]
oops. sorry about that. I'll code a fix for that

**Comment by darkpixel** [comment]
Tested, works for me on machines not using multiple targets.

**Comment by ppbrown** [comment]
okay, I added small tweak for the -t case. 
This one I have not tested, since its fairly trivial.
Please test and let me know. It's v 1.5.3 from github

**Comment by ksalman** [comment]
Sorry for the delayed response. It appears to be working so I am closing this issue.
