### ISSUE TITLE
Possible missing usage of "ZREPTAG" in "synctosnap".

### ISSUE THREAD

**Issue by ams-tschoening** [bolthole/zrep#120]
Came across the following line in [zrep_sync](https://github.com/bolthole/zrep/blob/master/zrep_sync#L119):

    zrep_[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]*)

[Creation of snapshots](https://github.com/bolthole/zrep/blob/master/zrep_snap#L165) uses `ZREPTAG` as variable prefix:

    newsnap="$1@${ZREPTAG}_$newseqX"

 [Other places](https://github.com/bolthole/zrep/blob/master/zrep_snap#L37) checking snapshot names do as well:

    sed -n "/@${ZREPTAG}_[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]/"p |

Isn't the first line missing `ZREPTAG`?

**Comment by ppbrown** [comment]
Oh! Thank you for finding that.
Commited a fix, 0de8602
