### ISSUE TITLE
Possible wrong check for snapshot naming convention in "zrep_sentsync".

### ISSUE THREAD

**Issue by ams-tschoening** [bolthole/zrep#121]
During discovering #120 I recognized the following line in [zrep_sentsync](https://github.com/bolthole/zrep/blob/master/zrep_sync#L48):

    *@${ZREPTAG}_[0-9]*)

[Creation of snapshots](https://github.com/bolthole/zrep/blob/master/zrep_snap#L165) uses HEX to encode the serial number:

    newsnap="$1@${ZREPTAG}_$newseqX"

 [Other places](https://github.com/bolthole/zrep/blob/master/zrep_snap#L37) checking snapshot names do take that into account:

    sed -n "/@${ZREPTAG}_[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]/"p |

Isn't the first line missing allowing `a-f`?

There seem to be many checks for the naming convention and some consider all individual chars of the HEX-serial in their regular expression, [some](https://github.com/bolthole/zrep/blob/master/zrep_snap#L107) only the first few:

    grep "@${ZREPTAG}_[0-9a-f][0-9a-f]"

Maybe you should consider factoring out that naming scheme reg exp into some global variable?

**Comment by ppbrown** [comment]
And another one, thank you. Although that one may never be hit, since user would have to go through
0x9fffff snaps to hit it.
At one snap a minute, that would take 20 years ;-)

I didnt see the need to do the full check in all cases. It was just a quickie junk check
