### ISSUE TITLE
Possibly reconsider the default value "-I" of "ZREP_INC_FLAG".

### ISSUE THREAD

**Issue by ams-tschoening** [bolthole/zrep#122]
This is related to some other question I had [some days ago](https://github.com/bolthole/zrep/issues/119) already, but here's the summary of the current setup:

ZREP syncs two hosts with each other every 15 minutes and manages everything automatically. Once per day each host is creating an additional snapshot for backup purposes for it's own data only,  simply named `backup` and therefore not following ZREP naming scheme by purpose, to not interfere with its operation. This worked quite well the last two days except that the snapshot `backup` gets synced as well.

The reason is that ZREP uses the flag `-I` by default and that tells ZFS to send intermediate snapshots as well:

> Use the zfs send -I option to send all incremental streams from one snapshot to a cumulative snapshot.

https://docs.oracle.com/cd/E19253-01/819-5461/gfwqb/index.html

While I see the benefits of getting all snapshots to the replication target easily, I wonder if this default value is really useful looking at the context ZREP is used in most likely. You [change that value](https://github.com/bolthole/zrep/blob/master/zrep#L80) to `-i` already in case `ZREPTAG` is not the default value, assuming that snapshots go to different replication targets.

Currently it looks like ZREP operates totally independent of other snapshots because of its own naming scheme and that is what I expected(/hoped) how things worked right from the start. I guess it's save to assume that in most cases ZREP will execute pretty often in frequent intervals. So most of the time there won't be any non-ZREP-managed intermediate snapshots anyway, why using `-I` doesn't provide that much benefit.

So how can intermediate snapshots occur? One case is mine and users simply created some in which case it's pretty unexpected that those get synced even if not following the naming scheme of ZREP. The other case is the special `*_unsent`-snapshots ZREP create in case a sync fails, because those are intermediate snapshots covered by `-I` as well. The only difference between those two cases is that `* _unsent` follows ZREP naming convention and gets cleaned up automatically. But those getting synced was unexpected for me as well and I wondered why that happened when I saw it yesterday, now I know the reason.

So, isn't `-i` the better default value in most cases? I would even argue removing that switch entirely to make implementation easier.

**Comment by ppbrown** [comment]
Most people prefer it as is.
The behaviour you dont view as neccessary, others view as useful. Particularly in the realm of deliberate archive snapshots.
