### ISSUE TITLE
Possibly unnecessary error message "[File exists]" for attempt to aquire the global lock.

### ISSUE THREAD

**Issue by ams-tschoening** [bolthole/zrep#124]
This is linked to a [former discussion](https://github.com/bolthole/zrep/issues/92#issuecomment-514216251). The following is the current implementation of the first attempt to aquire the global lock, but a similar approach is used later in the loop as well:

    set -C
    echo $Z_GLOBAL_PID > $Z_GLOBAL_LOCKFILE && return 0

https://github.com/bolthole/zrep/blob/master/zrep#L327

Every few days I get error messages like the following:

    /usr/local/zrep/zrep[320]: /var/run/zrep.lock: file already exists [File exists]

While that message [changed because of different implementations](https://github.com/bolthole/zrep/issues/92) in different versions of ZREP, all those implementations had some kind of that message in common.

In the past I thought I trigger that message because of too frequent runs of ZREP using `cron` on one and the same host, but that is not the case with that message occurring only every few days and using a time window of 15 minutes between executions. If that time window wouldn't be enough to succeed in general, the error would occur far more often.

Looking at all my error messages a second time, I think the real reason I get that is because of [zrep_expire](https://github.com/bolthole/zrep/blob/master/zrep#L2030): I have two hosts syncing each other at different fixed time points with both having a 15 minute time window, but in the end, each host always triggers execution of ZREP on the replication target for calling `zrep_expire`. So from time to time it happens that a locally started ZREP and that executed by the replication target to expire his old snapshots overlap shortly, resulting in the error message.

The important thing to note is that I only seem to get that message once, so based on the current implementation to aquire the lock, one second later things succeed already. Additionally take into account that it's in general impossible to know how long each execution of ZREP will take, all time windows are only an educated guess with the possibility of being to small sometimes under some workloads.

Therefore I'm suggesting that this concrete error message is unnecessary verbose, because the surrounding code not only deals with that "problem" properly, it even triggers it by design using `set -C`. So in this concrete case that concrete message does not inform anyone of any problem, but is only a verbose side effect of code working as intended. If things would be broken for some reason, the later checks would handle and inform about that properly.

Additionally keep in mind that you are [ignoring error messages](https://github.com/bolthole/zrep/blob/master/zrep#L348) sometimes as well, even all of those:

    kill -0 $lockpid 2>/dev/null

So how about something like the following to filter out those messages?

     bash -c "set -C && echo 'test' 2>&1 1>zrep.lock | grep -Pv '(?:existing file)|(?:\[File exists\])'"

**Comment by ppbrown** [comment]
Informational note to you:
The reason I ignore the output of "kill -0 $lockpid" is that the output is not an actual ERROR.
It is merely informational output.

**Comment by ppbrown** [comment]
I just made a commit that I think addresses your issue. Please try out 9e3b8af

Note: there is also another change wrapped in there. theoretically it will not affect you.

**Comment by ams-tschoening** [comment]
Thanks for the change, giving master a try currently and will report in case of any problems.

**Comment by ams-tschoening** [comment]
Not sure if this is related, but the current master seems to have a serious issue for me: After upgrading to master yesterday, this morning my hosts and VMs were pretty slow. The reason was hundreds of zrep-processes running with lots of CPU-usage. Those many processes simply didn't let much room for anything else. So I issued `killall "/bin/ksh"`, checked out v1.7.6 again and things were back to normal. The next execution of zrep simply replicated data again without any problems.

This looks like the locking is broken now.

![Clipboard02](https://user-images.githubusercontent.com/6223655/62520742-799f4c00-b82e-11e9-85fe-8fbb30b608c3.png)

**Comment by ppbrown** [comment]
Yikes! Sorry about that.

Oddly...I dont see an obvious reason why it would not hold the lock.
but I do see mishandling of error messages on on retry for lock.
So new push for THAT bit.
Not sure if that will fix the problem for you though.

Any further insight you have about the locking would be appreciated

**Comment by ppbrown** [comment]
Doing a git diff against the 1.7.6 version, and ignoring comment lines.. the only diffs for the get_global_lock function are now:


-       set -C
-       echo $Z_GLOBAL_PID > $Z_GLOBAL_LOCKFILE && return 0
+       set -C  #noclobber
+       echo $Z_GLOBAL_PID > $Z_GLOBAL_LOCKFILE 2>/dev/null && return 0  

-               echo $Z_GLOBAL_PID > $Z_GLOBAL_LOCKFILE && return 0
+               errmsg=`echo $Z_GLOBAL_PID 2>&1 > $Z_GLOBAL_LOCKFILE `
+               if [[ $? -eq 0 ]] ; then return 0 ; fi


But a simple test script that seems identical, works flawlessly for me:

#!/bin/ksh

LOCKFILE=/tmp/lockit
set -C  #noclobber

echo $$ >$LOCKFILE  2>/dev/null && return 0
echo lockfile failed. retrying...

errmsg=`echo $$ 2>&1 >$LOCKFILE `
if [[ $? -eq 0 ]] ; then 
        print it worked;
        return 0 
fi

echo FAIL: errmsg is $errm

**Comment by ams-tschoening** [comment]
I was just guessing about the lock, because that's what came into my mind seeing all those running processes. Maybe it's somewhere else, as said I was running master and not only your last mentioned locking changes from https://github.com/bolthole/zrep/commit/9e3b8af6eb258a3f8e304bce8f1e007c317ce549.

But this was too "exciting" for today, will leave this open and going to have a look at some later point.

**Comment by ppbrown** [comment]
okay thanks.

For better checking, I have created a branch, with JUST the new lock code, without the other changes. Perhaps you would test that.

https://github.com/bolthole/zrep/raw/zrep_newlock_tmp/zrep

**Comment by ppbrown** [comment]
okay, found the problem. 
a3a7c5e77198b4e25e91850986c0e3b5f07a1e5b
added sync -r.. but it also changed the way args are parsed for sync.
aand.. got into an endless loop. eheheehh...
It never even got to the global lock part.
So I'm fairly confident latest commit fixes this issue, and I'm closing this issue for now.

(fix in 90a02ef96bda5d2de9647d1bda78795394823e9f  )
