### ISSUE TITLE
_errprint used before being defined

### ISSUE THREAD

**Issue by dca58** [bolthole/zrep#126]
ZREP_VERSION=1.7.6

This produced:
```
zrep[165]: _errprint: not found [No such file or directory]
zrep[166]: _errprint: not found [No such file or directory] 
```
I moved the _errprint function definition before its first usage (at line 173) to fix it.

**Comment by ppbrown** [comment]
hello,
you give incomplete information. You didnt say what you were DOING to
trigger this problem.
under normal use, it isnt an issue.

however, I figured it out.
pushed 37c5780

**Comment by dca58** [comment]
Indeed sorry about the incompleteness...
