### ISSUE TITLE
Perl dependency

### ISSUE THREAD

**Issue by dca58** [bolthole/zrep#127]
Not a bug, just a comment about perl dependency and portability...

In function prep_gettimeinseconds there is this block:
```
        seconds=`perl -e 'print int(time);' 2>/dev/null`
        if [[ -z "$seconds" ]] ; then
                # attempt fallback if no perl present (eg: stock FreeBSD)
                seconds=`date +%s`
        fi
```
Another way to the same in pure ksh93 is
`seconds=$(printf '%(%s)T' now)`
with no dependency at all on any external code.

In the same way in prep_status()
date=`perl -e 'use POSIX qw(strftime); print strftime "%Y/%m/%d-%H:%M:%S",localtime('$sentseconds');'`
can be replaced with:
`date=$(printf '%(%Y/%m/%d-%H:%M:%S)T\n' "#$sentseconds")`

**Comment by ppbrown** [comment]
Huh.. neat!

Do you know of any way to check that this functionality is enabled other
than making the call? some ksh93 compatible environment variable set or
something?

**Comment by dca58** [comment]
It's quite old, I believe it was part of ksh 93h from 1999 and it is definitely documented in the Oreilly book from 2002. 
So one way to check could possibly be to use the value of ${.sh.version} ?

**Comment by dca58** [comment]
Just found it, it's indeed in 93h, see https://opensource.apple.com/source/ksh/ksh-18/ksh/src/cmd/ksh93/RELEASE93

**Comment by ppbrown** [comment]
thats pretty cool. It was tough to find documentation about it, but I
finally found some.
It was kinda lacking, so I updated my own ksh documentation about it :)

http://www.bolthole.com/solaris/ksh-oddthings.html

**Comment by ppbrown** [comment]
I just pushed something up to git. please let me know if it works
appropriately for you.

**Comment by dca58** [comment]
Documentation is indeed lacking which is weird for such a handy feature.

Note that in the example in your doc (printf "%T\n" #1566656615) the timestamp value must be quoted (printf "%T\n" "#1566656615" otherwise the # and everything that follows is interpreted as a comment.

> thats pretty cool. It was tough to find documentation about it, but I finally found some. It was kinda lacking, so I updated my own ksh documentation about it :) http://www.bolthole.com/solaris/ksh-oddthings.html

**Comment by dca58** [comment]
> I just pushed something up to git. please let me know if it works appropriately for you.
Double quotes are missing around #$sentseconds at line 603, but I'll try to test it later this week.

**Comment by ppbrown** [comment]
I tested the example I showed. it worked.
did you try it and it failed? If so I'd like to see the version of ksh
youare using.

**Comment by ppbrown** [comment]
OHHHH... I see the problem.
It didnt give an ERROR, like I would expect.
but it didnt decode the string. it just printed out curent time.
thanks for pointing that out.

**Comment by dca58** [comment]
Seems to be running just fine.

For the record, zrep is used here from the global zone of SmartOS machines to replicate fs across hosts. 
Perl is not installed on the global zone and they are several versions of date, both from GNU and from probably Solaris itself, hence the original comment.

ksh version: sh (AT&T Research) 93t+ 2010-03-05 

Thanks a lot for this really handy tool !
