### ISSUE TITLE
Error: Some kind of error during sending. Bailing out of _refreshpull

### ISSUE THREAD

**Issue by bmnave** [bolthole/zrep#128]
I'm running a refresh pull from my backup server in a cron job once an hour for four different filesystems.  One of the filesystems has been erroring with:

```
zrep refresh -v <fs>
cannot receive incremental stream: most recent snapshot of <fs> does not
match incremental source
Error: Unforseen error pulling snapshot <fs>@zrep_000691 from <master>
<root@backup:/path> # Error: Some kind of error during sending. Bailing out of _refreshpull
```

The filesystem that's failing has a very low change rate. So I don't understand the `most recent snapshot does not match incremental source` part.  Before I wipe the fs on the backup host and run a full sync, is there anything else I can do?

Both master and backup are FreeNAS-11.2-U5 running zrep version 1.7.7 ksh is:

```
# ksh --version
  version         sh (AT&T Research) 93u+ 2012-08-01
```

Thanks!
-b

**Comment by ppbrown** [comment]
first off, you almost never have to fully wipe the backup host fs.
you just need to roll back the system to the most recent successful sync.


Before that though.. you should make a fresh snapshot on the backup
side, and then do a zfs diff, to find out what has changed, between
the zrep synced snapshot, and the snapshot you just made.
Then, Stop Changing It Like That! :)

side comment: many zfs implementations seem somewhat stupid about
keeping a "read only filesystem", actually read only.
In those cases, its best to leave the backup side unmounted, so it
isnt possible to change the filesystem in any way.

In case it wasnt clear:
The problem isnt on your master side. It's something happening on your
receiving side.

**Comment by bmnave** [comment]
Hi @ppbrown,

Sorry it's taken me a while to circle back to this.  I tried what you suggested, created a snapshot on the backup side and then ran a zfs diff against the last zrep snapshot on the backup side.  There are no differences. :-/

I'm not sure if this means anything, but zrep list -v on the filesystem on the master and backup seem to disagree on the last snapshot synced:

On the master:
```
# zrep list -v <fs>
<fs>:
quota   none
reservation     none
aclmode passthrough
refquota        500G
refreservation  none
zrep:src-fs     <fs>
zrep:master     yes
zrep:savecount  168
zrep:lock-time  20190919223613
zrep:dest-host  backup
org.freenas:permissions_type    PERM
zrep:src-host   master
zrep:dest-fs    <fs>
zrep:lock-pid   27680
last snapshot synced: <fs>@zrep_000689
```

On the backup:
```
# zrep list -v  <fs>
<fs>:
quota   none
reservation     none
readonly        on
aclmode passthrough
refquota        500G
refreservation  none
zrep:savecount  168
zrep:lock-time  20190919223607
zrep:dest-host  backup
zrep:src-host   master
zrep:dest-fs    <fs>
zrep:src-fs     <fs>
org.freenas:permissions_type    PERM
zrep:lock-pid   22604
last snapshot synced: <fs>@zrep_000678
```

**Comment by ppbrown** [comment]
" zrep list -v on the filesystem on the master and backup seem to disagree on the last snapshot synced"

well that seems indicative of something rather tragic.

My suggestion is that you delete "extra" snapshots until both sides have the same "most recent" snapshot. 
you will then have to zfs rollback on the backup destination to that snapshot.
manuall set the "last snapshot synced"  property to point to the appropriate one. and then you should be able to do a zrep sync again.
