### ISSUE TITLE
Verbost send mode requested for Additional transfer details

### ISSUE THREAD

**Issue by darkpixel** [bolthole/zrep#129]
A typical transfer looks like this:
```
sending tank/myshare@zrep-remote_000007 to backup.mydomain.tld:tank/backups/myshare
Expiring zrep snaps on tank/myshare
Also running expire on backup.mydomain.tld:tank/backups/myshare now...
Expiring zrep snaps on tank/backups/myshare
```
Somewhere in the output, I'd love to see both the source and destination snapshots.  i.e.:

```sending from tank/myshare@zrep-remote_000006 to tank/myshare@zrep-remote_000007```

Additionally I'd love to see the estimated amount of data being transferred.

I think both of these could potentially be accomplished by passing ```-v``` to ```zfs send```.

That would give output similar to:
```
skipping snapshot tank/myshare@zfs-auto-snap_05-2019-09-22-2230 because it was created after the destination snapshot (zrep-remote_000006)
skipping snapshot tank/myshare@zfs-auto-snap_05-2019-09-22-2245 because it was created after the destination snapshot (zrep-remote_000006)
skipping snapshot tank/myshare/vm-100-disk-0@zfs-auto-snap_05-2019-09-22-2230 because it was created after the destination snapshot (zrep-remote_000006)
skipping snapshot tank/myshare/vm-100-disk-0@zfs-auto-snap_05-2019-09-22-2245 because it was created after the destination snapshot (zrep-remote_000006)
skipping snapshot tank/myshare/vm-101-disk-0@zfs-auto-snap_05-2019-09-22-2230 because it was created after the destination snapshot (zrep-remote_000006)
skipping snapshot tank/myshare/vm-101-disk-0@zfs-auto-snap_05-2019-09-22-2245 because it was created after the destination snapshot (zrep-remote_000006)
skipping snapshot tank/myshare/vm-100-disk-1@zfs-auto-snap_05-2019-09-22-2230 because it was created after the destination snapshot (zrep-remote_000006)
skipping snapshot tank/myshare/vm-100-disk-1@zfs-auto-snap_05-2019-09-22-2245 because it was created after the destination snapshot (zrep-remote_000006)
send from @zrep-remote_000005 to tank/myshare@zrep-remote_000006 estimated size is 624B
send from @zrep-remote_000005 to tank/myshare/vm-100-disk-0@zrep-remote_000006 estimated size is 3.65G
send from @zrep-remote_000005 to tank/myshare/vm-101-disk-0@zrep-remote_000006 estimated size is 3.26G
send from @zrep-remote_000005 to tank/myshare/vm-100-disk-1@zrep-remote_000006 estimated size is 821M
total estimated size is 7.72G
```

I guess I can add ```-v``` to ```ZREP_SEND_FLAGS```...I just forget about half the time.

**Comment by ppbrown** [comment]
erm... it already says
print sending $newsnap to $desthost:$destfs

so, you already know the snap name. the @xxxx part will always be the same
on both sides.

additionally, as you say, you can add -v already :}

**Comment by darkpixel** [comment]
I'll have to check the version I have deployed.  I don't get the start and end snapshots--I just get the end snapshot name.

```sending tank/myshare@zrep-remote_000007 to backup.mydomain.tld:tank/backups/myshare```

**Comment by ppbrown** [comment]
not sure what you mean by.  start and end.

**Comment by darkpixel** [comment]
When doing a 'sync all' zrep is issuing a command along the lines of ```zfs send -i @zrep-00001F tank/myshare@zrep-000020```.

The only output I get from zrep is ```sending tank/myshare@zrep-000020 to backup.mydomain.tld:tank/backups/myshare```

It doesn't reference the 'incremental source' (to use the ZFS man page terminology), just the 'incremental destination'.

**Comment by ppbrown** [comment]
still confused.
you seem to be saying you want to know the name of the prior snapshot.
why?
it should always be current-1, unless you’re having transfer issues.

if you ARE having transfer issues, there are better ways to detect that, in
my opinion.
ie: checking return status of the sync? :-)
or polling with the zrep option that checks for last sync time.
it’s not convenient for me to check the docs right now, but i seems to
recall there’s a way to check for “x number of seconds since last
successful sync”

**Comment by darkpixel** [comment]
Have you ever tried explaining hexidecimal to lower level techs? ;)

What's the previous snapshot to 000CF0?

Ob Silicon Valley reference: https://www.youtube.com/watch?v=_zTpwNR5Bf4

Additionally, like you said there may have been problems due to connectivity or something and the previous snapshot was unsent--making finding the previous snapshot from the output of a running job more tedious.

I've usually run ```ps uaxww``` to get the zfs send string and then run ```zfs send``` with the ```-vn``` flags so I can get the total transfer amount when I forget to run zrep with the ```-v``` flag in the first place.

We're using zrep for off-site backups, not hot-to-warm standby servers.  Occasionally a remote office will do something large like a conversion to a new piece of software and then our off-site backup ends up running all night and into the morning due to the amount of data changed.

From time to time we need to go in and see how much data is being transferred and how much is left to go and decide to continue or abort based on that.

i.e. if we've already transferred 750 GB from a total of 753, I'm going to let it continue running and tell the users to 'deal' with slow internet for another 30 minutes.  But if we're in 500 GB out of 2.1 TB, I'm going to stop the send, and remove the nightly cron job and manually kick off a sync on Friday afternoon after closing.

Another possible way around this might be to have a 'syncsize' command or something like that.
Have zrep basically do its normal logic--create a new snapshot, find the old snapshot, and then do a 'zfs send -nv' to get the total size of the transfer, then spit the result out and delete the temporary snapshot it used for calculating the size.

I would add some logic to cron to check the estimated size of the transfer, and if it's under 1 TB fire off a sync.  If it's over 1 TB abort.  Then the Friday evening job wouldn't have that size limitation.

It's just a minor annoyance for our weird edge-case.
If it's not a feature you want to add, I'll probably just put my own wrapper around the zrep cron job.

**Comment by ppbrown** [comment]
hmm.

explain to me why you seem to specifically want the last sent snapshot? It
sounds like I'm missing something, and it sounds potentially interesting.

On a side note, I just made this issue for myself you'll probably be
interested in:

https://github.com/bolthole/zrep/issues/130

Feel free to suggest more flags.


>

**Comment by darkpixel** [comment]
Specifically I want to be able to easily grab the last snapshot sent and the current snapshot that is being sent so I can calculate the amount of data being transferred.
I normally get this is I remember to set ```-v```, but I frequently forget because we don't need that detail in our cron output.  When I manually launch zrep, I frequently ```crontab -l``` to list the cron jobs and copy/paste.

Anyways, if zrep itself had a way to take a temporary snapshot (maybe something like @zrep-00000A-size), then calculate the transfer size, display the estimated transfer size, then delete @zrep-00000A-size) it could be used in calculations for scheduling transfers.
During the work week we launch off-site backups at 6 PM after the offices are closed.  Most diffs are a few GB (maybe 50 at most) which we can easily transfer before offices open at 7:30 AM.

But occasionally we run into offices that do a large data conversion that affects a few hundred GB of data.  If the estimated transfer size is over approximately 100 GB we can't transfer it all during closed hours.

Right now we fire off zrep without any checks at 6 PM.  The next morning when I come in, I run a quick command through salt to check if there are any jobs still running.  If there are, I try to estimate the amount remaining.  If it's going to finish within about 30 minutes of opening, I let it continue.

I suppose another way around it would be to start using pv (pipe viewer) and if I recall correctly it can create a socket that you can use to send commands to throttle the pipe.  I could just have a cron job that fires off a few minutes before opening to throttle back to 50% of the site's bandwidth, and then in the evening open it back up again.

**Comment by ppbrown** [comment]
sounds like what you actually want, is not “the last snapshot sent”, but a
convenience command  to calculate how much data is pending sync.

go ahead and make a new feature request for that one.

**Comment by ppbrown** [comment]
you are slow to make new relevant issues :-)
lucky for you I decided to make a "last snapshot sent" callin anyway, since it was only adding a wrapper to an internal function anyways:
b95bd99

**Comment by darkpixel** [comment]
It's been a busy week.  ;)

Thanks!

**Comment by ppbrown** [comment]
bump reminder

**Comment by darkpixel** [comment]
Waiting on me for something?

**Comment by ppbrown** [comment]
you didnt confirm that the new "last snapshot sent" feature is useful as written

**Comment by ppbrown** [comment]
also it owuld be nice if you validated the new "zrep status -m"

**Comment by darkpixel** [comment]
Confirmed--```lastsent``` is definitely handy.
I'll have to deploy the updated version later this week and test ```status -m```

**Comment by ppbrown** [comment]
caution: I tweaked the expire routine in the latest git. 
in theory no difference. but, fair warning.

**Comment by darkpixel** [comment]
....what is the ```-m``` flag supposed to do again?  It hangs on my test box until I get bored and CTRL+C...which is usually about 3 minutes depending on the amount of coffee I've consumed.

**Comment by ppbrown** [comment]
hmm.
sounds like theres a logic bug, infinite loop.
and also possibly an incomplete implementation.

my purpose for creating 
zrep status -m

was for "monitor" programs.
To detect if there are too many "unsent" snapshots.
Currently, looks like the code only prints out a warning, along side the normal status output.
(and update the usage message!)

But Im thinking I should set a diffrent return code as well,

**Comment by darkpixel** [comment]
Aah--understood.  I'll test when you're ready.

**Comment by ppbrown** [comment]
Checking back on this.
Can you confirm that adding -v to ZREP_SEND_FLAGS does what you want for theo ther stuff in this ticket?
If so I think I can close this one

**Comment by darkpixel** [comment]
I hate to say this, but I am unable to test it.  A few weeks ago we ended up switching to a different tool for syncing backups because we needed to ensure child datasets were enumerated and resumed properly as well as having the ability to run hooks and access variables (i.e. estimated bytes to transfer) in the zfs send pipeline.

**Comment by ppbrown** [comment]
ah well. good luck.

for purposes of documentation, I managed to test it myself. 

ZREP_SEND_FLAGS=-v
 gives the following style output.

sending scratch/src@zrep_000024 to localhost:scratch/newsrc
send from @zrep_000023 to scratch/src@zrep_000024 estimated size is 134M
total estimated size is 134M
TIME        SENT   SNAPSHOT
19:05:37   20.9M   scratch/src@zrep_000024
19:05:38   54.0M   scratch/src@zrep_000024
19:05:39    103M   scratch/src@zrep_000024
19:05:40    107M   scratch/src@zrep_000024

So, I shall close this issue.
