### ISSUE TITLE
zrep with ZREP_R=-R doesn't destroy old snapshots in child dataset

### ISSUE THREAD

**Issue by maurizio-emmex** [bolthole/zrep#13]
Thank you for your script.
I am using zrep in FreeBSD and I have noted the above bug.

I create a test dataset TMP and a child TMP2:
`# zfs list -r -t filesystem sys/no-backup/TMP`
NAME                     USED  AVAIL  REFER  MOUNTPOINT
sys/no-backup/TMP        192K   141G    96K  /mnt/no-backup//TMP
sys/no-backup/TMP/TMP2    96K   141G    96K  /mnt/no-backup//TMP/TMP2

I initialize the copy to the second computer named microserver
`# export ZREP_R=-R`
`# zrep init sys/no-backup/TMP microserver zdata/backup_ativ/TMP`

Repeating five times the command:
`# zrep sync sys/no-backup/TMP`
on the second computer microserver I have:
`# zfs list -r -t snapshot zdata/backup_ativ/TMP`
NAME                                     USED  AVAIL  REFER  MOUNTPOINT
zdata/backup_ativ/TMP@zrep_000001          8K      -    96K  -
zdata/backup_ativ/TMP@zrep_000002          8K      -    96K  -
zdata/backup_ativ/TMP@zrep_000003          8K      -    96K  -
zdata/backup_ativ/TMP@zrep_000004          8K      -    96K  -
zdata/backup_ativ/TMP@zrep_000005           0      -    96K  -
zdata/backup_ativ/TMP/TMP2@zrep_000000     8K      -    96K  -
zdata/backup_ativ/TMP/TMP2@zrep_000001     8K      -    96K  -
zdata/backup_ativ/TMP/TMP2@zrep_000002     8K      -    96K  -
zdata/backup_ativ/TMP/TMP2@zrep_000003     8K      -    96K  -
zdata/backup_ativ/TMP/TMP2@zrep_000004     8K      -    96K  -
zdata/backup_ativ/TMP/TMP2@zrep_000005      0      -    96K  -
where the snapshot "zdata/backup_ativ/TMP/TMP2@zrep_000000" was not cancelled.

Regards,
Maurizio

**Comment by ppbrown** [comment]
Ah, I see. the expire works for the top level, but does not touch the sub filesystems.
Thank you for the clean test case and output.
I'm working on a fix, and recommended clean up routine

**Comment by ppbrown** [comment]
Okay, fix turns out to be pretty easy :)
i just committted zrep 1.5.4

To clean up old mess, run zrep expire individually on each sub filesystem.

**DO_NOT_USE_CLEAR
I initially, wrongly, thought that running "zrep clear fs/sub/name" would be quickest. 
**DO_NOT_USE_CLEAR

use zrep expire only.

**Comment by maurizio-emmex** [comment]
Thanks it works! Tested in my office with FreeBSD 10.2-RELEASE.
