### ISSUE TITLE
zrep produces temp unavailability of dest FS

### ISSUE THREAD

**Issue by amateo** [bolthole/zrep#134]
Hi,

I don't know if this problem is with zrep or it is with zfs replication.

I have zrep replicating a zfs between two servers. Replication is working without any problem except that during the replication process, that is while the zfs send and zfs recv is running I have problems accessing the FS in the destination server. The problem I have found is files and directories that don't exist in the FS while the process is running (but they are when it is finished) even for files that don't change between the snapshots.

Is this normal? Is this a problem with with zrep or zfs?

**Comment by ppbrown** [comment]
unfortunately the non solaris implementations of zfs are stupid in many
ways when it comes to replication.
that is why it is recommended to actually have the destination fs
unmounted.
(at all times, until you want to activate it as primary)

I wish that just setting the read only flag was sufficient. IMO it should
be. but  it it isn’t.
please complain to your zfs vendor :-)

**Comment by amateo** [comment]
Ok. Thank you.
