### ISSUE TITLE
Send to different user account?

### ISSUE THREAD

**Issue by darkpixel** [bolthole/zrep#138]
The docs and parameters are a bit unclear, so I wanted to check with you first on this issue...

ZREP currently runs in my environment from a cron job as the root user and sends our central backup server using the root account...but I'd like each system to connect in under a different account.

Something like: ```SSH="ssh -p 224 -l backupuser" ZREP_SKIP_EXPIRE=1 ZREP_SEND_FLAGS="--raw" ZREP_RESUME=yes ZREP_R=-R ZREP_INC_FLAG=-i /usr/local/bin/zrep -t zrep-remote sync all```

Would adding the SSH flag ```-l backupuser``` hose things up?

The reason for this is that unprivileged accounts can be created with zfs permissions that only allow receiving data, but not deleting snapshots, datasets, volumes, etc...

The purpose being that the primary system could have a passwordless SSH key in /root/.ssh/id_rsa that can sign in to the backpuuser account on the remote system, but if the primary system was compromised it wouldn't allow backups to be destroyed.

**Comment by ppbrown** [comment]
zrep doesnt care about the actual transport, as long as it acts like ssh.
zrep doesnt care about what user it runs as, so long as it has perms to do what it needs to do.

so in principle I dont see anything wrong with what you plan.
That is in fact exactly why there is a 
"Using as non root user"
section at the end of the official doc page.

**Comment by darkpixel** [comment]
I figured based on the docs it wasn't going to be an issue--I just wasn't sure if there was a flag I should set (ZREP_USER or something) or if I should pass it as an arg to SSH.  Thanks for the info.

**Comment by ppbrown** [comment]
some people even create special creds for the transfer, and use
ssh -i non-default.key  ....
