### ISSUE TITLE
Snapshot filesystems with mysql databases on it.

### ISSUE THREAD

**Issue by deja-geek** [bolthole/zrep#140]
When doing a snapshot of a filesystem that a mysql (or maria)db lives on, it's best to flush and lock all the tables before doing the doing snapshot.  It's also very handy to record the binlog file and binlog position for recovery.  I've already figured out how to do the snapshot itself, but I'm not sure how to fit it into zrep.

For the snapshot, it looks something like this
```
dbsnapshot(){
                dbkillcount=0
                dbsnapshotcommand="sudo -i mysql --login-path=loginid -e \"FLUSH TABLES WITH READ LOCK; FLUSH LOGS; show master status\\G; SYSTEM /sbin/zfs snapshot $Z_SNAP_R $newsnap;UNLOCK TABLES;\""
                while [[ $dbkillcount -le 2 ]]; do
                             $dbsnapshotcommand > $Z_SNAP_R/snapshot_info 2>&1
                             dbsnappid=$!  #need the pid
                             exit &
                             sleep 5 #wait for lock
                             ps h -p $dbsnappid
                              if [[ $? -eq 0 ]]; then
                                       kill -9 $dbsnapid #waiting to long for a lock
                                        ((dbkillcount++))
                              fi
                              if [[ $dbkillcount -ge 2 ]]; then
                                         return 1 #couldn't get a lock
                              fi
                done
                return 0 
}
```

I think the value for login-path could be stored as a zfs property and another property would have to be set to let zrep know it is a database filesystem.  I guess this is half a feature requests and half help.

**Comment by darkpixel** [comment]
Maybe something like running scripts in /etc/zrep.presnap.d/* before taking snapshots and then /etc/zrep.postsnap.d/* after the snapshot is taken?

**Comment by ppbrown** [comment]
Dohhh.. i was going to reply to this and then got sidetracked.

here's my thoughts on this:

by default, I believe zrep uses the flag for (duplicate snapshots).
if yours doesnt.. then add it with ZREP_SEND_FLAGS or whatever.
then your procedure is:

1. pause database
2 take zfs snap mysql_snap@fs/here
3. continue database

and then just do a zrep sync any time after that.
the mysql_snap@fs will get replicated safely to the other side.

Just remember that you are responsible for snapshot management for the
non-"zrep_####" snapshots.
