### ISSUE TITLE
zrep sentsync does not seem to work as advertised

### ISSUE THREAD

**Issue by darkpixel** [bolthole/zrep#142]
```
root@uslaysdnas01:~# /usr/local/bin/zrep -t zrep-remote lastsent tank/officeshare
tank/officeshare@zrep-remote_000009
root@uslaysdnas01:~# /usr/local/bin/zrep -t zrep-remote sentsync tank/officeshare@zrep-remote_000006
root@uslaysdnas01:~# /usr/local/bin/zrep -t zrep-remote lastsent tank/officeshare
tank/officeshare@zrep-remote_000009
root@uslaysdnas01:~# 
```

My backup target has @zrep-remote_000006 as the latest snapshot.  I can't get the local box to stop trying to send from @zrep-remote_000009.

The 'lastsent' command is handy for exactly this kind of troubleshooting. :)

I don't believe the commit from last night (b2794b1) introduced the error because I've run into it before, but that's the version I'm testing with on this box.

My normal fix is to manually bring the remote box up-to-date with what zrep thinks should be there.

**Comment by ppbrown** [comment]
Seems like you need to edit the subject and contents of this issue, to be
along the lines of,
"zrep sentsync does not seem to work as advertised"

(and remind me to put it in the usage()  )

**Comment by ppbrown** [comment]
also what happens if you use -L

**Comment by ppbrown** [comment]
OHHhhh.

this only adds a value.
it doesnt remove OLD values. at present.
Maybe thats what is needed. you need to removed the *:sent property from
0009

lemme know if that fixes it

**Comment by darkpixel** [comment]
I had to dig through the source to find out what ```-L``` does.  Apparently it's the flag that causes a Comcast modem to die. I'll test removing the property sometime in the next 4-6 hours when the tech replaces the modem. ;)

**Comment by ppbrown** [comment]
WOW!
I've heard of "use the Source, Luke", but I never realized the source
had THAT much power!

**Comment by darkpixel** [comment]
I'm not sure if it's due to the updates or something on my side.  Now that the office is back online, I double-checked that the sent property set to inherit for snaps 007, 008, and 009 and then ran a sync and got an error about an unexpected ```@```

```
root@uslaysdnas01:~# SSH="ssh -p 224" ZREP_SEND_FLAGS="--raw" ZREP_OUTFILTER="pv -eIrab -L 1M" ZREP_RESUME=yes ZREP_R=-R ZREP_INC_FLAG=-i /usr/local/bin/zrep -t zrep-remote sync tank/officeshare
sending tank/officeshare@zrep-remote_00000b to --redacted--:tank/backups/uslaysd/officeshare
 167KiB [ 124KiB/s] [ 124KiB/s] 

Expiring zrep snaps on tank/officeshare
awk: 1: unexpected character '@'
Also running expire on --readacted--:tank/backups/uslaysd/officeshare now...
Expiring zrep snaps on tank/backups/uslaysd/officeshare
root@uslaysdnas01:~# 
```
I ran the sync a second time and it appears to be working...

I didn't have it in debug mode, so I don't have any details on why it didn't like the at character....and seeing as how all the datasets still exist on the source and the target boxes, I figure it can probably be chalked up to ghosts in the machine.

**Comment by darkpixel** [comment]
...anyways, having sentsync fix existing properties seems like a nice feature.

**Comment by ppbrown** [comment]
dohhh.. .I know what the problem is.
my test cases were too simple. I tested fs@snap.
not fs/sub/tree@snap.

smh.

**Comment by ppbrown** [comment]
well. i fixed the awk problem at least. Now I need to figure out the sentsync problem.

**Comment by ppbrown** [comment]
okay.

081f384

sentsync was already working for the original purpose it was designed for: easing transition of pre-existing syncs, to zrep.

but now it should work for your situation as well.
at the cost of losing the official timestamps of when a snapshot is synced.
on the flip side, normaly you dont lose too much information since it's mostly around creation time anyways.

**Comment by ppbrown** [comment]
PS: see also the newly added last paragraphs of
http://www.bolthole.com/solaris/zrep/troubleshooting.html
related to sentsync usage.

**Comment by darkpixel** [comment]
```
# WARNING: If you have nested zrep filesystem below this one.. you just hosed yourself.
#
```
LMAO!
