### ISSUE TITLE
 Internal Err caller did not hold fs lock

### ISSUE THREAD

**Issue by Nepoxx** [bolthole/zrep#143]
I have a cron running `DEBUG=1 zrep refresh glusterbck/fs` every day, and it will fail once in a while with the following stderr output:

```
DEBUG: zrep_lock_fs: set lock on glusterbck/fs
DEBUG: refresh step 1: Going to mars to snapshot glusterbck/fs
DEBUG: refresh step 2: Pulling gluster01@zrep_000022
_refreshpull: snapname=gluster01@zrep_000022, fs=gluster01
DEBUG: zrep_lock_fs: set lock on gluster01
DEBUG: Running local expires on glusterbck/fs
DEBUG: expiring glusterbck/fs@zrep_00001d
DEBUG: Running remote expires on gluster01
Expiring zrep snaps on gluster01
Error: zrep_expire Internal Err caller did not hold fs lock on gluster01
zrep_unlock_fs: unset lock on glusterbck/fs
```

I see quite a few github issues mentioning this but as far as I know they are all resolved, hence a new issue.

The strangest part is that I am not able to reproduce this when running `DEBUG=1 zrep refresh glusterbck/fs` manually. Here's the output when run manually:

```
root@pluto:/home/nepoxx# DEBUG=1 zrep refresh glusterbck/fs 
DEBUG: zrep_lock_fs: set lock on glusterbck/fs
DEBUG: refresh step 1: Going to mars to snapshot glusterbck/fs
DEBUG: refresh step 2: Pulling gluster01@zrep_000026
_refreshpull: snapname=gluster01@zrep_000026, fs=gluster01
DEBUG: zrep_lock_fs: set lock on gluster01
DEBUG: Running local expires on glusterbck/fs
DEBUG: expiring glusterbck/fs@zrep_000021
zrep_unlock_fs: unset lock on gluster01
DEBUG: Running remote expires on gluster01
DEBUG: zrep_lock_fs: set lock on gluster01
Expiring zrep snaps on gluster01
DEBUG: expiring gluster01@zrep_000021
zrep_unlock_fs: unset lock on gluster01
zrep_unlock_fs: unset lock on glusterbck/fs
```

If you require additional information or things you'd like me to try, I'll be happy to oblige!

Cheers!

**Comment by ppbrown** [comment]
weeelll...
ideally you would adjust your cronjob to grab additional details when zrep fails.
things like ps list, and the contents of the lock file.


One would PRESUME that there is a second zrep running still, and thats why it cant get the lock.

oh wait. this is about the FILESYSTEM lock, not the "Lock file".
so you would want to capture the value of the zfs property,

${ZREPTAG}:lock-pid

on the filesystem.

ie:
zfs get zrep:lock-pid  glusterbck/fs

**Comment by Nepoxx** [comment]
I'll investigate further and report back. Thanks for the pointer!

**Comment by Nepoxx** [comment]
I changed my cron to be
`ps aux; zfs get zrep:lock-pid glusterbck/fs; DEBUG=1 zrep refresh glusterbck/fs; zfs get zrep:lock-pid glusterbck/fs`
and this is what I got (without `ps aux` (it did not contain any instance of zrep))

```

NAME           PROPERTY       VALUE          SOURCE
glusterbck/fs  zrep:lock-pid  -              -
DEBUG: zrep_lock_fs: set lock on glusterbck/fs
DEBUG: refresh step 1: Going to mars to snapshot glusterbck/fs
DEBUG: refresh step 2: Pulling gluster01@zrep_000027
_refreshpull: snapname=gluster01@zrep_000027, fs=gluster01
DEBUG: zrep_lock_fs: set lock on gluster01
DEBUG: Running local expires on glusterbck/fs
DEBUG: expiring glusterbck/fs@zrep_000022
DEBUG: Running remote expires on gluster01
Expiring zrep snaps on gluster01
Error: zrep_expire Internal Err caller did not hold fs lock on gluster01
zrep_unlock_fs: unset lock on glusterbck/fs
NAME           PROPERTY       VALUE          SOURCE
glusterbck/fs  zrep:lock-pid  -              -
```

**Comment by ppbrown** [comment]
what version of zrep?

**Comment by Nepoxx** [comment]
1.7.7

**Comment by ppbrown** [comment]
Hello there,
coming back to this, it seems like your issue is a dup of
#148 
which has a patch.
Please try latest (in git) zrep and letme know if it fixes your problem

**Comment by tuempeltaucher** [comment]
I can confirm that sleep 1 after "_debugprint Running remote expires on $srcfs" solves the problem.

v 1.8
