### ISSUE TITLE
ZREP_CREATE_FLAGS does not work on zrep init

### ISSUE THREAD

**Issue by hostingnuggets** [bolthole/zrep#147]
Hello,

I am using zrep 1.8.0 where I have adapted the ZREP_CREATE_FLAGS to use compression as such:

```
ZREP_CREATE_FLAGS="-o compression=lz4"
```

then I start a `zrep init` but when I check once finished on the receiving side I see that compression is not enabed: 

```
data/myvolume  compression           off                                                                                           default 
```
I am using ZFS 0.7.12 on Debian stretch on both servers.

**Comment by ppbrown** [comment]
oh...
sorry about that. thats actually what you might call a documentation bug.
ZREP_CREATE_FLAGS only comse into play in old versions of ZFS, where zrep
cant work normally.

the normal case is that the remote side gets created with the same
properties as the source.
But keep in mind, you can always add compression manually, after zrep init.

**Comment by hostingnuggets** [comment]
I see, but the weird thing then is that my fileset has compression property set on the source side, as you ca see here:

```
# zfs get compression data/myvolume
NAME       PROPERTY     VALUE     SOURCE
data/myvolume  compression  lz4       inherited from data
``` 

So in theory zrep should take this into account but it doesn't seem to?

**Comment by ppbrown** [comment]
oh.
thats a pretty old version of debian, right?

this brings to mind two things:

1. it would be good if you did an experiment and manually created a
zfs, and then did a zfs send/receive with send -p, to see if it
normally duplicates compression.
if not, you might consider filing a bug with your zfs folks. or.. ya
know.. upgrading? :)

2. I need to update the documentation.. and probably add a NEW option,

ZFS_INIT_REMOTE_PROPERTIES

**Comment by jhesse** [comment]
> # zfs get compression data/myvolume
> NAME       PROPERTY     VALUE     SOURCE
> data/myvolume  compression  lz4       inherited from data

data/myvolume is inheriting it's compression setting.  I suspect that if you set it explicitly on the source dataset, or set compression on the parent dataset of the target you will get end up with the result you want.   In general, I always enable compression at the root pool level on all my pools and that gets inherited on all my datasets.  Except for really old hardware, compression will always be a performance improvement for zfs (according to conventional zfs wisdom).  

Hope that helps.  Obviously I'm not weighing in on the original issue of whether the create flag should work the way you expected, etc.    Just offering a workaround.

**Comment by ppbrown** [comment]
committed e5d746a that adds ZREP_INIT_REMOTE_PROPERTIES.
would be nice if you tested it for me ;)

**Comment by hostingnuggets** [comment]
@ppbrown thank you for your changes, I am just not sure if this is useful in the case of compression because you are setting this ZFS property after having sent the data which. So this means that the data is not compressed on the remote side. For compression to work the ZFS compression property needs to be set on the filesystem before any data is written.

**Comment by ppbrown** [comment]
oh. right, that problem :-}
Hmmm...

so what happens if you manually create the destination filesystem first,
with compression on?

**Comment by darkpixel** [comment]
> so what happens if you manually create the destination filesystem first,

I don't think ```zfs receive``` will overwrite an existing dataset unless you send the ```-F``` flag...and then it's basically destroying it and re-creating it.  Probably without the compression setting.

**Comment by ppbrown** [comment]
yeah thast what I would think....
but  I notice that my "old compat mode" does just that.
so I wonder if options stick.

I would think that -F destroys the DATA, but leaves the options.

**Comment by ppbrown** [comment]
If so...
maybe I need to *force* the old style of init, if ZREP_CREATE_FLAGS is set.
that might make everyone happy

**Comment by ppbrown** [comment]
Okay. Added commit 0459a1c
Testing would be appreciated.

**Comment by ppbrown** [comment]
Closing this for lack of feedback.
if it does not actually fix your issue please feel free to recomment here.

**Comment by hostingnuggets** [comment]
@ppbrown sorry did not have the opportunity to test this because I only have a production system and found another workaround to this issue in the mean time.

**Comment by hostingnuggets** [comment]
@ppbrown I finally got the chance to try out your 0459a1c commit but unfortunately the zrep init still does not work as you can see from the output below:

```
Setting zrep properties on pool/myzvol-disk
Creating readonly destination filesystem as separate step
Creating snapshot pool/myzvol-disk@zrep_000000
Sending initial replication stream to remoteserver:data-backup/myzvol-disk
invalid option 'o'
usage:
	receive [-vnFu] <filesystem|volume|snapshot>
	receive [-vnFu] [-d | -e] <filesystem>

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
warning: cannot send 'pool/myzvol-disk@zrep_000000': signal received
Destroying any zrep-related snapshots from pool/myzvol-disk
Removing zrep-related properties from pool/myzvol-disk
Error: Error transferring pool/myzvol-disk@zrep_000000 to remoteserver:data-backup/myzvol-disk. Resetting
```

**Comment by ppbrown** [comment]
thank you for testing.
I'll work on an update.
If you dont see anything from me, feel free to give me a nudge every now
and then :)

**Comment by hostingnuggets** [comment]
@ppbrown thank you too for taking a look. I guess here that zrep should check the ZFS version on the remote server too and if it is ZFS < 0.7 do not use the `-o` option to `zfs recv`.

**Comment by ppbrown** [comment]
oh wait a minute. So THATS the problem..

it’s up to the user/sysadmin  to keep the zfs versions in sync.
checking remote is too much overhead in my book.

**Comment by hostingnuggets** [comment]
@ppbrown probably yes. I just know for a fact that the `zfs recv` command of ZFS 0.6 does not have the `-o` option and your script is assuming that it has because it is assuming that both sides (server & remote) use exactly the same version of ZFS.

ZFS versions are supposed to be compatible between each other for example it is no problem to zfs send/recv between ZFS version 0.6 and 0.7 so in my opinion it would be nice if zrep also supports that.

If you do not want to adapt zrep for a including a version check during `zfs recv` I guess I will simply force `Z_HAS_REC_O=0` everywhere manually inside the script. That should work and could be useful for other people too.
