### ISSUE TITLE
 Race condition when running remote expires

### ISSUE THREAD

**Issue by domihirt** [bolthole/zrep#148]
I discovered the following. But only on one system.
We are calling zrep on our backup server. The backup server will connect to the live system.

Both servers are running Proxmox, which is based on Debian.

When zrep tries to expire the remote snapshots, it will generate the following error:
Error: zrep_expire Internal Err caller did not hold fs lock on

I added a "sleep 1" and everything is fine again:

_debugprint Running remote expires on $srcfs
sleep 1
zrep_ssh $srchost "$ZREP_PATH expire -L $srcfs"

Only difference to other live systems: This is a slow server. It will maybe set the lock to late.

**Comment by ppbrown** [comment]
Note: the patch was for the code path that the user requested, which is through zrep_refresh.
The normal zrep_sync might also benefit from this, but it has not been added at this time.
