### ISSUE TITLE
create tags when bumping release

### ISSUE THREAD

**Issue by samuelbernardo** [bolthole/zrep#15]
Thank you very mutch for your work with zrep!
I'm a gentoo user testing zfs in Linux. I was searching for a tool to replace rsync in my desktop backups and your script is just wonderful.

I have some things to ask you as a wish list to get better integration with ebuilds in gentoo.

It'll be usefull to use tags (like 1.5.5) to set a release.
With this I can create ebuilds from this repository more easily.

Latest stable release published in the site is 1.5.4. I think that it was generated from the following commit:
https://github.com/bolthole/zrep/commit/970add831f77dae0e5f4e66c9d2235995527be75

But I realize that there were many bug fixes that appear in version 1.5.5. Should I use head of branch master?

**Comment by ppbrown** [comment]
Hello, and thank you for your interest in zrep :)

My development cycle is usually something like this:

1. general experimentation on the component zrep_* files can happen at any
time
2. the compiled zrep script, only gets pushed to the repo, when I think
there is something reasonably safe for testing
3. If something has been reported good, then I copy that, to my website.

I made a special update for the latest 1.5.5 as you noticed, but I think I
was lacking feedback.
if you would like to grab it and verify its all happy, then i will copy it
to my main website.

As far as github tags go...
I actually tried to use them, but the (scarce) documentation was too
confusing to me,  so I gave up trying to use them :(

**Comment by ppbrown** [comment]
PS: Sometimes, I push versions of the compiled zrep script, that do not
have a "version bump" comment.
Those are the "user beware" ones that are basically alpha testing for
someone.
Otherwise, the headis usually fairly safe.
I dont tend to make branches in git. I just tweak with local copies when
I'm messing around.

**Comment by samuelbernardo** [comment]
Sorry for my answer delay.
There is a problem when compiling ksh in gentoo as referenced in following page:
https://bugs.gentoo.org/show_bug.cgi?id=573354

It seems that AT&T Research use some tools that aren't available in gnu/linux as nmake.

Anyway I test to compile ksh from debian source package and it just compiled without problem. Looking into package source I realize that there is so much hacking to put that source compiling in linux.

So, while I can't get ksh working in gentoo I can't give you any feedback about latest changes in release 1.5.5.

Anyway I had made an ebuild for zrep and so it'll be easier to be at sync with git zrep repo.
When release >1.5.5 go out I'll get commit id before that to place stable version for zref-1.5.5.ebuild.
I pretend to share my gentoo local overlay where stands zrep ebuild for everyone who needs it.
The related files are in this repository:
https://github.com/samuelbernardo/ssnb-overlay/tree/master/dev-util/zrep

thanks again for zrep!

**Comment by ppbrown** [comment]
HMM.

from what I remember trying to build that stuff in solaris... the important
thing is to try to compile the WHOLE package of tools. Not just the ksh
subtree.
They all work together.

i also note that at the end of the gentoo url, they give a solution. So you
could use that to build ksh on gentoo? L:)

**Comment by samuelbernardo** [comment]
The given solution in post is from me.
I have already zrep 1.5.5 working as expected.
sync is working fine.

thanks again ppbrown for you wonderful project!

**Comment by olgeni** [comment]
Hi, I was looking at the FreeBSD port of zrep - if you could add a versioned copy to the website (like zrep-1.5.4) it would be easier to get the correct file for each release :)

**Comment by ppbrown** [comment]
hi.
I think you asked me this before.
I will giv eyou the same reply:
i dont understand how to do that.

**Comment by ppbrown** [comment]
oh wait. you didnt change the subjectline, but your email doesnt match the
subject >.<

I already use versions. However, what specifically would you need to see on
the website for this?
*specifically*. at the html level.

**Comment by darkpixel** [comment]
I think he means on GitHub.  Once you have your release ready and all the changes committed, you can do ``git tag v1.2.3.4``` or whatever is appropriate and then git push --tags will push the tag to github.

Github creates downloads of tagged versions automatically.

If you go to a project like Bower (https://github.com/bower/bower), click the 'master' branch dropdown, then click 'tags', you will see they have a bunch listed.

It makes it easy for build tools to ensure they are always grabbing the proper version when packaging.

**Comment by ppbrown** [comment]
well, i gave it a shot :)

**Comment by olgeni** [comment]
Shiny! I saw it in the RSS feed. Thanks! :)
