### ISSUE TITLE
Flag to output status in hours, days, etc...

### ISSUE THREAD

**Issue by darkpixel** [bolthole/zrep#151]
I would love to see a flag to be able to output the status of the last backup in hours, days, etc...

For monitoring systems it would be handy to be able to do something like:
```zrep status -f days tank/officeshare```
...and get output like:
```
2
```
or
```zrep status -f days```
...and get output like:
```
tank/officeshare: 2
tank/mydata: 5
```

The current output:
```
tank/officeshare                                     last: 2020/02/28-18:42:52
```
requires a bit of manipulating to extract the data and get the data.

```dateutils.ddiff -f '%d' -i '%Y/%m/%d-%H:%M:%S' $(zrep status tank/officeshare | sed -E 's/tank\/officeshare[[:space:]]+last:[[:space:]]//') now```
or
```
dateutils.ddiff -f "%d" -i "%a %b %d %H:%M %y" "$(zfs get creation -o value -H $(zrep -t zrep-remote lastsent tank/officeshare))" now
```

I get that it would cause more work on your end because you would potentially have to interface with something like dateutils (or maybe there's some ksh magic for handling dates)...but "my way" gets more difficult when you have to pass those commands through a scripting engine in a monitoring system that requires its own escaping, then send it via SSH to bash which requires even more escaping...

It's easier to just deploy a script on the endpoint to do the majority of the grunt-work...and since we're at the point of deploying a script to each node to handle getting info out of zrep and then doing string and date parsing...it seems potentially reasonable to have zrep handle it all in the first place. :)

**Comment by ppbrown** [comment]
yikes.
sounds too bulky in zrep.
I dont think super-flexible date parsing stuff belongs in there.
If you want to suggest a more narrow hook that would make it easier for you
to do something thou, feel free.

**Comment by ppbrown** [comment]
i should mention that its pretty easy to convert the output to seconds
elapsed.
with ksh buildin time manipulation, mentioned at
http://www.bolthole.com/solaris/ksh-oddthings.html
;->

 for

tank/officeshare                                     last: 2020/02/28-18:42:52

printf "%(%s)T\n" '2020-02-28 18:42:52'
1582915372

**Comment by ppbrown** [comment]
oops:
PS, that also works for 20/02/18 format

**Comment by ppbrown** [comment]
a reasonable compromise might be:
supporting
export ZREP_DATEOUTPUT='%s'

and then you can see if

653c653
<                       date=`printf "%(%Y/%m/%d-%H:%M:%S)T" "#$sentseconds"`
---
>                       date=`printf "%($ZREP_DATEOUTPUT)T" "#$sentseconds"`

to output seconds, makes you happy.

after all, then  you could just check for the value being larger than (too_many_days x 86400)   
?

**Comment by darkpixel** [comment]
Would it be too much to ask for a machine-readable status output?

And if you're saying that it's not too difficult to convert the last backup date to seconds, it would make it a lot easier to integrate with monitoring systems.

i.e. ```tank/officeshare: 123456``` would be a lot easier to directly handle in most monitoring systems I've used.

**Comment by ppbrown** [comment]
doesnt my previous comment give you exactly that?

**Comment by darkpixel** [comment]
I thought you were talking about integrating that into zrep verses more complicated date math.
I'll just stick with deploying my own scripts to get the last backup dates and times.

**Comment by ppbrown** [comment]
You are being confusing today.  I offer you your half-way solution, and then you say you dont want it? :)
Anyways, I've commited and tested the change.
9b19dda

now has ZREP_DATEFORMAT

 ZREP_DATEFORMAT='%s' ./zrep status -v
scratch/src              ->localhost:scratch/newsrc            1575439226

**Comment by darkpixel** [comment]
Sorry if it wasn't clear.
I must have misunderstood you.  I thought you were saying it was easy for you to output the last backup time in seconds from zrep--which would make my life a whole lot easier....which it appears you did. I've never been one for meeting in the middle. ;)
