### ISSUE TITLE
support for nc

### ISSUE THREAD

**Issue by 4xoc** [bolthole/zrep#152]
Are there any plans to support sync via nc/netcat or particular reasons why not? Secure transmission is not always needed and with nc the overhead of encryption/decryption could be removed.

**Comment by ppbrown** [comment]
hello

modern ssh usually suports this already with option “cipher=none” or
something like that.
besides which the encrypt/decrypt is trivial compared to other matters.
look up info on using zrep with mbuffer for increased speed

**Comment by 4xoc** [comment]
SSH support for cipher=none doesn't exist by default. It needs to be compiled with the option enabled. I've done some tests and mbuffers over ssh hardly improves performance (using https://github.com/bolthole/zrep/blob/master/zrep#L85). Compared to nc it's about half as fast and that is on hardware supporting AES-IN and with multiple cores.

**Comment by ppbrown** [comment]
Have you done actual test with zfs send and receive + netcat?

how about comparing with using bbcp?

useful links:

https://github.com/bolthole/zrep/issues/20

https://zfs-discuss.zfsonlinux.narkive.com/SpozlPKR/zfs-send-receive-performance

**Comment by ppbrown** [comment]
oops. I see you did perf tests. but I still recommend comparing to bbcp as well.

**Comment by 4xoc** [comment]
Wow, I have to admit that I didn't expect much difference using bbcp compared to nc but it's intense. Here are a couple of metrics for comparison. From my side this issue can be closed as I'll stick with bbcp.

The same snapshot and devices have been used. 10 Gb/s leased line between locations, layer 2 transport, ~10 Km distance, MTU of 9000, SATA 3 (6 Gb/s) raidz2 vdevs. In all cases the speed is pretty constant with only small variations.

SSH: 1.3 Gb/s 
Netcat: 2.8 Gb/s
bbcp: 4.7 Gb/s

**Comment by ppbrown** [comment]
Thank you for providing the numbers.
Enjoy your highspeed transfer :)
