### ISSUE TITLE
frequent _unsent snapshots

### ISSUE THREAD

**Issue by vincentkersten** [bolthole/zrep#154]
Hello zrep,
Since a few months I run zrep. It runs hourly from a cron job , every ten minutes i start zrep on a dataset. Quite frequently I run into "...._unsent" snapshots from the master. I run zrep v1.7.7.

When I 'force' the dataset to replicate, I get:
```
 /usr/local/bin/zrep sync -f raid/home 
sending raid/home@zrep_0010ff to tokyo1.infiniband:raid/home
Expiring zrep snaps on raid/home
Also running expire on tokyo1.infiniband:raid/home now...
Error: Remote side also marked as master FIRMWARE-Mellanox gpg gpg.1 interfaces perf.data Tokyo1en2 tokyo1.infiniband:raid/home
```

There are a few questions here, maybe you can assist me with that:
1) Why do i run into _unsent snapshots every few days or so, while the rest of the time it runs fine (there is not activity on 'tokyo1')?
2) Remote side also marked as master .... I cannot seem to find how the remote is marked as master in the zfs properties, all the sets seem to have equal settings. 
3) Maybe a bug: after the above "Error: Remote side also marked as master" it lists the contents of the /root/ folder. 

I am really keen to see this go, and would appreciate your help. 

Here are the zfs ZREP properties (zrep v1.7.7)

```
### TOKYO2 (Master) ###

raid/home  zrep:dest-fs          raid/home              local
raid/home  zrep:master           yes                    local
raid/home  zrep:lock-time        20200331082932         local
raid/home  zrep:src-fs           raid/home              local
raid/home  zrep:src-host         tokyo2                 local
raid/home  zrep:dest-host        tokyo1.infiniband      local
raid/home  zrep:lock-pid         21103                  local
raid/home  zrep:savecount        5                      local

```

```
### TOKYO1 (slave) ###

raid/home  zrep:lock-time        20200323081202         local
raid/home  zrep:lastsent         raid/home@zrep_000907  local
raid/home  zrep:src-fs           raid/home              received
raid/home  zrep:savecount        5                      received
raid/home  zrep:dest-fs          raid/home              received
raid/home  zrep:master           yes                    local
raid/home  zrep:dest-host        tokyo1.infiniband      received
raid/home  zrep:lock-pid         27129                  local
raid/home  zrep:lastsenttime     1584360053             local
raid/home  zrep:src-host         tokyo2                 received
```

**Comment by ppbrown** [comment]
Hello,

the questions that come to mind are:

Why are you running it with -f in the first place?

and, I should be the one asking the question, "why do you have _unsent"
snapshots? :)
that is a sign that syncjobs are failing.so you would need to investigate
which ones and why they are failing.

You might want to clear the master status, with

zfs inherit zrep:master raid/home

and then see if it comes back the next time you use zrep sync -f.

(its not supposed to, but if it does, please let me know)

**Comment by vincentkersten** [comment]
Dear ppbrown,
thank you for coming back to me. 

Let me clarify: I only use "zrep -f"  if i have _unsent snapshots on the master. Normally I use zrep hourly in cron , without the -f flag. 
When the master starts to have  _unsent snapshots, I also do not get them anymore on the slave. That is to say, after having an _unsent in the next round it also does not send it anymore. 
It says that the other end has changed, which is weird, since that FS is not mounted and has no active users. 

 As to "zfs inherit zrep:master raid/home" 
Should i run this at the master, or at the slave end? Does this impact my backups? (the FS is quite a few terabytes, so not trivial to sync again)

Thank you again for your help!

**Comment by ppbrown** [comment]
interesting.

guaranteed, SOMETHING is changing the other end.
maybe something is doing a quick mount-tweak-unmount.
or maybe some autosnapshot thing going on.  I recommend you find out what
it is, and kill it.

Run the zfs inherit on the slave side. it clears the master flag, which
only belongs on the master side.
It should not affect backup sync. It's just a property.

It might even be that zrep itself is doing it somehow, since it thinks
the slave is the master.
So clear the flag on the slave, do a clean sync.. then carefully observe
the system for when sync gets screwed up again after that.

**Comment by vincentkersten** [comment]
ok did the 'inherit' on the slave side. No more 'Remote side also marked as master ...' - thank you for that tip! 
Checked all what could be tweaking the filesystem. Nothing found, and so far no _unsent yet. I'll keep you posted / reopen when stuff pops up. 

Thanks once more for the great script!
