### ISSUE TITLE
Error: zrep_expire Internal Err caller did not hold fs lock

### ISSUE THREAD

**Issue by darkpixel** [bolthole/zrep#16]
I'm running 1.5.5.

On a box containing existing data, I installed the zrep script and did a `zrep init` to sync files.  The initial sync appears to have run properly.  Next I did a `zrep sync all` and it failed.  I tried again, and it failed again.

I'm not sure what the error relates to:

Initial sync:

```
root@kvm1:~# ZREP_R=-R zrep -t zrep-local init tank/userprofiles localhost backup-pool/userprofiles
Setting properties on tank/userprofiles
Ancient local version of ZFS detected.
Creating destination filesystem as separate step
Creating snapshot tank/userprofiles@zrep-local_000000
Sending initial replication stream to localhost:backup-pool/userprofiles
Debug: Because you have old zfs support, setting remote properties by hand
Initialization copy of tank/userprofiles to localhost:backup-pool/userprofiles complete
root@kvm1:~#
```

Sync all:

```
root@kvm1:~# ZREP_R=-R zrep -t zrep-local sync all
sending tank/userprofiles@zrep-local_000002 to localhost:backup-pool/userprofiles
Expiring zrep snaps on tank/userprofiles
Also running expire on localhost:backup-pool/userprofiles now...
Expiring zrep snaps on backup-pool/userprofiles
Error: zrep_expire Internal Err caller did not hold fs lock
REMOTE expire failed
root@kvm1:~#
```

**Comment by ppbrown** [comment]
Ah. initial error is  presumably because

1. zrep uses a global locking mechanism (for now)
2. it presumably forgets to release the lock before doing expire .. to the
same machine. so there is a locking conflict.

Thanks for filing the bug.  Busy week, will get to it when i can


Er.. but in your output, I see an error on INITIAL sync yet no error on
sync all.
The opposite of what you describe?

**Comment by darkpixel** [comment]
Oops--I flipped my paste.  I'll edit it and correct it.  It's been a long week here too.  ;)

**Comment by ppbrown** [comment]
I may have fixed this issue.
Please see the latest on github.

**Comment by darkpixel** [comment]
I just pushed out 1.6.1 to all my hosts.  I'll let you know in a few days.

**Comment by darkpixel** [comment]
I'm still hitting it on several of my machines.

**Comment by darkpixel** [comment]
Here's an example from one box:
```
root@usvansdnas01:~# ZREP_R=-R ZREP_INC_FLAG=-i zrep -t zrep-local sync all
sending tank/officeshare@zrep-local_0011e2 to localhost:backup-pool/officeshare
Expiring zrep snaps on tank/officeshare
Also running expire on localhost:backup-pool/officeshare now...
Expiring zrep snaps on backup-pool/officeshare
Error: zrep_expire Internal Err caller did not hold fs lock
REMOTE expire failed
sending tank/virt@zrep-local_0011e0 to localhost:backup-pool/virt
(the send in still in progress)
```

```
root@usvansdnas01:~# head /usr/local/bin/zrep 
#!/bin/ksh -p

# For more detailed documentation, see zrep.txt or zrep.overview.txt
ZREP_VERSION=1.6.1

######## start of included files from zrep_top here
########### zrep_vars

# This should basically be included as common vars before all zrep stuff.
# It contains all 'constant' definitions, as well as a few crucial
root@usvansdnas01:~# 
```

**Comment by ianabc** [comment]
I'm using 1.6.1 and doing some tests on localhost. I see the same error (I think).

```
root@zfs1:/root# ZREP_R=-R zrep -i tank1 localhost tank2
Setting properties on tank1
Warning: zfs lacking -o argument
Creating destination filesystem as separate step
Creating snapshot tank1@zrep_000000
Sending initial replication stream to localhost:tank2/tank1
Initialization copy of tank1 to localhost:tank2/tank1 complete
```
Seems to be OK, then during the sync
```
root@zfs1:/root# ZREP_R=-R zrep sync all
sending tank1@zrep_000001 to localhost:tank2/tank1
Expiring zrep snaps on tank1
Also running expire on localhost:tank2/tank1 now...
Expiring zrep snaps on tank2/tank1
Error: zrep_expire Internal Err caller did not hold fs lock
REMOTE expire failed
```

**Comment by ppbrown** [comment]
Please check latest release v1.6.7

**Comment by ppbrown** [comment]
Addendum: please check latest git, which is newer than latest release :)

**Comment by ppbrown** [comment]
Also, please do
export DEBUG=1
before running

**Comment by devZer0** [comment]
i also have this problem with local zrep. using 1.6.7

**Comment by devZer0** [comment]
i found that filesystems have been locked probably because zrep runs were interrupted with ctrl-c or whatelse. i removed the locks with zfs set.   zrep should make that easier for the user, i.e. tell "zrep is already running with pid....if you are sure this is an error, please override with "--force" or "zrep removelock" or whatever

**Comment by ppbrown** [comment]
Funny that you should say that.

most recent github version has something very similar to your suggestion
already :)
you might want to try it out.

**Comment by ppbrown** [comment]
erm.. wait.

the FILESYSTEM level locks are already checked for staleness, and
automatically removed.
It's only the GLOBAL lock that needs manual intervention. You should not
have had to use "zfs set".

Now I'm concerned for what you did to your system :-/
good luck.
(you may or may not want to open a separate issue for this)

**Comment by ppbrown** [comment]
Soo.. multiple people have now weighed in on this, and it's getting a bit messy :(
Multiple OS's and multiple situations, sounds like.

I THINK I've improved the locking situation a lot.
If people still run into issues with new release v1.6.8 please open up a new issue, with full details such as your OS version and zrep version. THanks!
