### ISSUE TITLE
how to sync more than two server instead of two?

### ISSUE THREAD

**Issue by almoondsllc** [bolthole/zrep#161]
This is of course not an "issue", more a feauture request but I'm new on github so if I do something "wrong", fix me :)
I'm using for a while zrep and I'm very happy with it, I use it with encrypted dataset and all is working smooth.
Now I've the need to sync more than two server, for example I've a customer with one master zfs machine, a zfs slave machine in the same office and I would also have a remove zfs machine to have a remote backup.
So, is it possible implementing such configuration?
zfs_master <-----zrep------> zfs_slave  <-----------------zrep--------------> zfs_remote

Thanks,
Alessandro

**Comment by ppbrown** [comment]
Hello, and thank you for your interest in zrep :)

I  recommend against "chaining" replication.
However,  zrep has a "tag" feature to allow a master to replicate to more
than one server.
So you can do things like

ZREP_TAG=localrep zrep sync all
ZREP_TAG=remoterep zrep sync all

and it will keep 2 unique sets of snapshots up to date.
Note that you have to do two separate zrep init's as well.

**Comment by ppbrown** [comment]
hey, you're new to github, but you've been around for quite a while!
:)
