### ISSUE TITLE
Hoes does ZREP work with different versions of UB and ZFS?

### ISSUE THREAD

**Issue by ams-tschoening** [bolthole/zrep#167]
I'm currently running two systems with UB 16.04 LTS Server and ZREP `v1.7.6` hosting a few VMs using VirtualBox. Because UB 16.04 becomes end-of-life soon, I need to upgrade both hosts and thought about if I really need to process both at the "same time" or can do one after another, possibly with multiple weeks between both upgrades.

Looking at ZREP, it shouldn't care too much about the concrete versions of UB in use, correct? As long as SSH, the executing shell and ZFS work at all, I should be able to upgrade one after another? I'm currently not planning to change the pools on either host during the upgrade as well, so what did work in the past should keep working?

I've looked into the docs, but didn't find such situations explained. Thanks!

**Comment by ppbrown** [comment]
this should be true.

**Comment by ams-tschoening** [comment]
Thanks, I'll report back in case of problems. :-)
