### ISSUE TITLE
zrep does not rename/clear unsent recursive snapshots

### ISSUE THREAD

**Issue by asciiphil** [bolthole/zrep#17]
If zrep fails to send a snapshot, it renames that snapshot to `zrep-000000_unsent`.  Unfortunately, if `ZREP_R=-R` is set, it does not rename the children's snapshots.  This has the additional effect that when the unsent snapshots are removed from the parent, they are not removed from the children (because they still have their old name).

zrep should rename the child snapshots when it renames the parent one.

**Comment by ppbrown** [comment]
Ick.
no way I can make zrep reasonably recurse for that. 
I think most reasonable thing to do is not do the rename if that var is set.

**Comment by ppbrown** [comment]
waaait..  zfs rename also takes a "-r"?!?!
huh.

guess I'll do that then :-D

**Comment by ppbrown** [comment]
Okay. committed a fix for this finally :-/
