### ISSUE TITLE
Include ZREP_RESUME in user tunable section

### ISSUE THREAD

**Issue by kocio-pl** [bolthole/zrep#177]
`ZREP_RESUME` looks like a user-specific setting, but it's not present in a user tunable section. There is only `ZREP_RESUME_FLAGS=-v` example:

https://github.com/bolthole/zrep/blob/master/zrep#L107

but this means something else and might make user wonder how to enable resume at all.

**Comment by ppbrown** [comment]
I think what you are really saying, is, "how do I use resume? it isnt documented?"

the answer is "use zrep send -r, or zrep refresh -r".
so I should probably make this ticket, "document -r properly".
yes?

**Comment by kocio-pl** [comment]
Thanks, that's what I'd like the most. However adding this as an example setting helps making it permanent, which is slightly different problem (and that was easier to find out and propose).

Your reaction time is amazing BTW... :astonished:

**Comment by ppbrown** [comment]
doc updated
http://www.bolthole.com/solaris/zrep/zrep.documentation.html#resumereplication
