### ISSUE TITLE
delete non existing datasets on destination

### ISSUE THREAD

**Issue by crispyduck00** [bolthole/zrep#180]
Hi,

would it be possible to add a feature to destroy datasets or clones on the destination that no more exist on the source host?

I often add clones and destroy them, if I do not destroy them also on the dest, they will stay there and after a takeover the sync back fails.

Or any other way to to get them automatically destroyed on the dest?

Also I just saw that newly added datasets are synced correctly, but the ro flag is not set for them.

Br,

**Comment by crispyduck00** [comment]
Sorry, my fault seems the -f is doing it. 

Is -f (force) documented somewhere? If I read it correctly in the script it is just passing -F to zfs?

Br
cd

**Comment by ppbrown** [comment]
Correct on both counts. it is not currently documented.

do you have any suggestions on best section of the documentation to add it to?

**Comment by crispyduck00** [comment]
Good question. Maybe directly in the usage() function, as it does different things, e.g. for sync and changeconfig.

**Comment by ppbrown** [comment]
-f is already in the usage, so I added the details of what it does, to the replication section in the official docs at 

http://www.bolthole.com/solaris/zrep/zrep.documentation.html#forcedreplication
