### ISSUE TITLE
don't sync if not master

### ISSUE THREAD

**Issue by crispyduck00** [bolthole/zrep#183]
Maybe zrep is not really functioning the way I initially expected. 
But I will add it anyway as issue.

I initially always used "zrep -S all" and thought that it will anyway skip fs where not master.  As I later found out that when using "all" zrep will exit on error and skip the other fs in the row I switched to calling "zrep -S fs" for each fs, also expecting zrep will do nothing for fs where it is not master, but this is not the case.

For me as I only use sync, I added a check in the zrep_sync():

```
zrep_sync(){
	typeset srcfs destfs desthost sentsnap newsnap
	typeset quiettime=0

	if [[ "$1" == "-c" ]] ; then
		export ZREP_CHANGEDONLY="yes"
		shift
	fi

	if [[ "$1" == "-q" ]] ; then
		quiettime="$2"
		shift
		shift
		if (( quiettime < 30 )) ; then
			zrep_errquit "-q must use value greater than 30"
		fi
	fi

	if [[ "$1" == "all" ]] ; then
		set -- `zrep_list_master`
		if [[ "$1" == "" ]] ; then
			# Stay quiet, so we dont spew if in cron
			#print No zrep mastered filesystems found
			exit
		fi
###crispyduck
#do nothing if not local master for this fs
	else
		if [[ $($ZFSGETLVAL ${ZREPTAG}:master $1) != "yes" ]] ; then
			# Stay quiet, nothing to do here
			exit
		fi
###
```

For sure this should also be added on other places to cover also other cases.

**Comment by ppbrown** [comment]
the "sync all"(but not for slave) functionality, is one of the oldest parts of the zrep code. it hasnt changed in a very long time.
Are you sure something you have changed, has not broken it?

When I look at the top level "zrep_sync" function currently, it seems logically correct.
Maybe you do not understand that
set -- `zrep_list_master`

expands so that retroactively, the argument list for zrep_sync gets changed, so instead of

zrep_sync all

it is now called as

zrep_sync master_fs_1  master_fs_2  master_fs_3 ....

**Comment by crispyduck00** [comment]
Hi, yes this is clear, and therefore in the arguments are only fs that are master, as "set -- `zrep_list_master`" already only returns master fs.

This is fine, and I would also use the all function, but as a failure in e.g. zrep_sync master_fs_1, will exit zrep and so the other master fs master_fs_2 master_fs_3 .... will not be synced if the first in the loop fails, I will not use all, instead I always call zrep -S  master_fs_1, zrep -S master_fs_2,....

But if I run now "zrep -S fs_not_master" zrep tries to sync the fs even if it is not master, okay, with the check from the "don't sync on split brain" it will connect to dest-host and realize that it is master, but I think this is not necessary, as if we are not master for the fs we don't have to do anything when sync is called.

Sure, we can also say you should not call zrep -S if you are not master, or we add a check so that it will anyway not do anything.
The second one fits the way I would like to run zrep. Systemd timer runs zrep -S on all my hosts, for all fs, and zrep knows what to do.

To don't mess with "all", I added it as else to the if [[ "$1" == "all" ]], so only if not "all", the check if local master prop is not "yes" is done. If not yes, so also if the fs does not exist at all zrep exits as nothing is to do here.

If this should be added, I think it is needed on other places too. 

As I wrote, maybe it is not intended to use it the way I do, and I can anyway try to make some changes for myself. On the other hand, I thought it will be good to share my findings. As you are also working on a bash version, maybe i could be considered there.

Br,
cd

**Comment by ppbrown** [comment]
you said what you describe, "fits the way I would like to run zrep".
So I guess you are doing some version of

for fs in (zfs list -t fs) zrep sync
but the thing is, you can easily do it for just masters with

for fs in (zrep list -L)  zrep sync

Maybe this will change your thinking?

**Comment by crispyduck00** [comment]
Sorry, I don't get it at the moment. 

The issue is that "zrep -S [-f] [-v] fs_not_master_prop_local" should not do anything.

**Comment by ppbrown** [comment]
Please check out the latest commit

**Comment by crispyduck00** [comment]
Perfect. Tested it in all possible sync ways.
