### ISSUE TITLE
don't destroy local fs if init is used wrong

### ISSUE THREAD

**Issue by crispyduck00** [bolthole/zrep#189]
I don't know if my stupidity is also valid as issue,

Anyhow, doing a `host1# zrep -i pool1/prodfs host1 pool1/prodfs` destroys actually the prodfs.

I don't think anything is needed here, a zfs destroy wrongfs will also distroy my fs. :-)

Just thought I still mention it. Would be a simple check, as you anyway rewrite it for bash, maybe some extra to protect me from such mistakes. ;-)

**Comment by ppbrown** [comment]
wait..;your subject line says "destroy local fs". I don't see how that is
possible.
REMOTE fs, maybe.
but local??
that seems impossible.

**Comment by crispyduck00** [comment]
`host1# zrep -i pool1/prodfs host1 pool1/prodfs `

It is local host to local host, so so yeah, "remote host=local host"

Doing so many testing I started to often make some mistakes, typos,... this was one of them. ;-)

**Comment by ppbrown** [comment]
Hmm.
So.. looks like zrep init does not currently have a -f option.
Which to me suggests that if it is NOT set, then do a check to see if $destfs already exists.
IF it is set, then just do current normal behaviour.

**Comment by ppbrown** [comment]
added in 5fc4d24
