### ISSUE TITLE
Multiple Destinations zrep - Not removing Snapshots on destination filesystem.

### ISSUE THREAD

**Issue by ximenac** [bolthole/zrep#19]
Hello there, we're testing zrep on our testing systems before we go live in production and while testing I found the issue where one filesystem being replicated in another server in 2 different pools, is not removing the snapshots (the tagged ones) on the first synced filesystem (destination).

For a better understanding of my situation, here's an example:

Origin Server:
root@origin:~# zfs list -t all
NAME                           USED  AVAIL  REFER  MOUNTPOINT
pool01                         850K  48.2G    31K  /pool01
pool01/fs01                     30K  48.2G    30K  /pool01/fs01
pool01/fs01@zrep_000008           0      -    30K  -
pool01/fs01@zrep_2tag_000008      0      -    30K  -
pool01/fs01@zrep_000009           0      -    30K  -
pool01/fs01@zrep_2tag_000009      0      -    30K  -
pool01/fs01@zrep_00000a           0      -    30K  -
pool01/fs01@zrep_2tag_00000a      0      -    30K  -
pool01/fs01@zrep_00000b           0      -    30K  -
pool01/fs01@zrep_2tag_00000b      0      -    30K  -
pool01/fs01@zrep_00000c           0      -    30K  -
pool01/fs01@zrep_2tag_00000c      0      -    30K  -
pool02                        1.24G  47.0G    31K  /pool02
pool02/fs02                   1.24G  47.0G  1.24G  /pool02/fs02
pool1                         7.62M  19.2G    31K  /pool1
pool1/st1                     7.33M  19.2G  7.33M  /pool1/st1
root@origin:~# 

Destination Server:
root@destination:~# zfs list -t all
NAME                           USED  AVAIL  REFER  MOUNTPOINT
pool01                        1.22M  48.2G    31K  /pool01
pool01/fs01                     46K  48.2G    30K  /pool01/fs01
pool01/fs01@zrep_2tag_000000     1K      -    30K  -
pool01/fs01@zrep_2tag_000001     1K      -    30K  -
pool01/fs01@zrep_2tag_000002     1K      -    30K  -
pool01/fs01@zrep_2tag_000003     1K      -    30K  -
pool01/fs01@zrep_2tag_000004     1K      -    30K  -
pool01/fs01@zrep_2tag_000005     1K      -    30K  -
pool01/fs01@zrep_2tag_000006     1K      -    30K  -
pool01/fs01@zrep_2tag_000007     1K      -    30K  -
pool01/fs01@zrep_000008          1K      -    30K  -
pool01/fs01@zrep_2tag_000008     1K      -    30K  -
pool01/fs01@zrep_000009          1K      -    30K  -
pool01/fs01@zrep_2tag_000009     1K      -    30K  -
pool01/fs01@zrep_00000a          1K      -    30K  -
pool01/fs01@zrep_2tag_00000a     1K      -    30K  -
pool01/fs01@zrep_00000b          1K      -    30K  -
pool01/fs01@zrep_2tag_00000b     1K      -    30K  -
pool01/fs01@zrep_00000c           0      -    30K  -
pool02                        1.48M  48.2G    31K  /pool02
pool02/fs01                     34K  48.2G    30K  /pool02/fs01
pool02/fs01@zrep_2tag_000008     1K      -    30K  -
pool02/fs01@zrep_2tag_000009     1K      -    30K  -
pool02/fs01@zrep_2tag_00000a     1K      -    30K  -
pool02/fs01@zrep_2tag_00000b     1K      -    30K  -
pool02/fs01@zrep_2tag_00000c      0      -    30K  -
root@destination:~# 

Here you can see the Cronjob:
*/1 \*   \* \* \*   root    zrep -S pool01/fs01; zrep -t zrep_2tag -S pool01/fs01

Here are the Filesystem properties:
root@origin:~# zrep -l -v pool01/fs01
pool01/fs01:
xattr   sa
zrep_2tag:master        yes
zrep:src-host   vs1o
zrep_2tag:dest-fs       pool02/fs01
zrep_2tag:src-fs        pool01/fs01
zrep_2tag:dest-host     backupip@vs2o.ipandmore.de
zrep:savecount  5
zrep:dest-fs    pool01/fs01
zrep_2tag:savecount     5
zrep:master     yes
zrep_2tag:src-host      vs1o
zrep:dest-host  backupip@vs2o.ipandmore.de
zrep:src-fs     pool01/fs01
last snapshot synced: pool01/fs01@zrep_000013
root@origin:~# 

As you may have noticed, on the origin I have Snapshot from: @zrep_2tag_000008 to: @zrep_2tag_00000b but on the destination, I have snapshots from @zrep_2tag_000000 to: @zrep_2tag_00000b

Is this a real issue here or am I missing something while setting up and/or initializing zrep?

Thanks a lot for your amazing contribution!

**Comment by ppbrown** [comment]
Hmm.  odd.
i have two questions:

1. what is the specific version of zrep you are using
2. do you see the problem if you try replicating a single filesystem with
only the custom tag?

**Comment by ximenac** [comment]
Hi There, 

1. I'm using the 1.6 zrep Version.
2. The problem is not there when I replicate the filesystem with only one custom tag, and also with 2 custom tags.
Although, the problem is still there when I have the normal replication + 1 custom tag replication.

Regards,
Ximena.

**Comment by ppbrown** [comment]
hi,
Please try version 1.7 to see if it helps.

**Comment by ppbrown** [comment]
closing due to age and no feedback.
