### ISSUE TITLE
Is there an issue with zrep sync filesystem@snapshot?

### ISSUE THREAD

**Issue by mlan** [bolthole/zrep#194]
With 1.8.0 `zrep sync filesystem@snapshot` worked as advertised. I upgraded zrep to version 2.0.1 and now there seems to be some kind of issue (both master and slave have the snapshot):

```bash
# zrep sync rpool/filesystem@zrep_000000
ERROR: synctosnap did not receive all required args
Error: args=
```

Is it just me?

**Comment by ppbrown** [comment]
oops. didnt mean to close this, just reference it :-}

Please confrm that my latest push, fixes the problem for you?

**Comment by mlan** [comment]
Hi @ppbrown 

Yes, the latest push fixed the problem.

Many thanks for excellent support!  😀
