### ISSUE TITLE
enhancement request: able to replicate directly over mbuffer channel

### ISSUE THREAD

**Issue by mailinglists35** [bolthole/zrep#20]
I have observed that ssh is quite slow and I don't want to use a non-default patched version.

Instead I use a poor home made script that does replicate local to remote filesytems but connects with mbuffer over openvpn encrypted channel. I am saturating a 100Mbit link, something that ssh can not be expected to.

It would be nice to drop my poorly written home script and use this popular script instead.

roughly on receiving side I do this in rc.local and ensure nobody can talk to it except the sender

```
while true; do (mbuffer -s 128k -m 64M -I 9090 | lz4 -d - |zfs receive -Fvdu big); done
```

while on the sending side

```
zfs send -vI @$FROMSNAP $localdataset@$TOSNAP | lz4 -c -9 - | mbuffer -s 128k -m 500M -O $remotehost:9090
```

thanks!

**Comment by ppbrown** [comment]
hello,

zrep already supports mbuffer

please read the comments at the top of the script for sample usage.

please also note that bbcp is even faster, if you have the spare cpu, since
it can use multiple streams automatically

**Comment by stuartthebruce** [comment]
It looks like mbuffer is only supported for optionally adding additional buffering at the end points, and not network transfers as it supported for bbcp. It might be useful to support the mbuffer -I and -O options for network transport as well, or have I misunderstood?

**Comment by ppbrown** [comment]
It's been a while since I touched this, but I vaguely recall trying to play
with -I and -O.
What is shown in the commented out options, is the best way I found to use
mbuffer.

If you test and find a better way, please let me know.
In a seperate, new request

**Comment by stuartthebruce** [comment]
I installed bbcp and that worked well. I have used mbuffer -O and -I to transfer larger zfs send images in the past with a home grown script that worked well. I am happy enough to use bbcp on Linux, however, mbuffer is slightly easier to install on Solaris as it is available via OpenCSW. If you think it is worth the effort the basic idea is to have ssh start mbuffer -I on the destination machine, and then use mbuffer -O on the source machine to push to the specific port.

**Comment by ppbrown** [comment]
Errr.. you seem to be asking for mbuffer support.
there already is mbuffer support.
please read the comments in the script, and uncomment the variables as appropritate.

**Comment by stuartthebruce** [comment]
When I ran my first test with mbuffer it appeared to me that zfs data was being sent over ssh and the mbuffer was being used to provide extra buffering at the two end points. Rather than using mbuffer as just INFILTER and OUTFILTER can ssh initiate an mbuffer -I process on the target machine at a specific port and then have the source machine run mbuffer -O to that port?

**Comment by ppbrown** [comment]
Oh.

you want to do raw transfer.

Short answer: no.

I tried it. things got very ugly.

if you reALLYY want to do raw transfer, you shoudl be able to simulate it
by configuring ssh to connect with no encryption or compression.


But you're probably better off just using bbcp.

**Comment by stuartthebruce** [comment]
OK. I will stick with raw transfers via bbcp (rather than mbuffer). Note, OpenSSH does not support the cipher type "none", which is unfortunate in my opinion.

**Comment by ppbrown** [comment]
so install a patched version.
you can tell zrep to use a different path to ssh, after all.

**Comment by mailinglists35** [comment]
i find it is unpractical to install a patched ssh.

**Comment by thedarb** [comment]
Curious about what you meant by ugly?  I'm currently trying to patch in mbuffer for the raw transfer right now, with ssh kicking it off on the remote host.  Found an old old patch to ver 1.0.1 for inspiration.  Not working, I can't get the quoting through ssh properly intact.

**Comment by thedarb** [comment]
Nevermind, tried bbcp and yeah... more than good enough.  Thank you!
