### ISSUE TITLE
Changeconfig -d  not working

### ISSUE THREAD

**Issue by tortuegenialez** [bolthole/zrep#204]
Hello

Changing the configuration with `-d` fails:
```
No pre-existing zrep snapshots found on -d
-d is not initialized for zrep. cannot change config.
Error: Use zrep init on -d instead
```

The  [zrep_changeconfig](https://github.com/bolthole/zrep/blob/master/zrep#L1497) function seems lacking to handle the `-d` switch.
`-d` is handled as the `srcfs` variable, failing the pass the check `getlastsnap`

**Comment by ppbrown** [comment]
Thanks for reporting. I'll get to it when I can.

**Comment by ppbrown** [comment]
please try latest push and confirm it is good for you

**Comment by tortuegenialez** [comment]
Hello,
I confirm it's working as expected :ok_hand: 

Thanks!
