### ISSUE TITLE
zfs is too old for zrep

### ISSUE THREAD

**Issue by gkyildirim** [bolthole/zrep#21]
I have a recent version of smartos. `zrep -i zones/disk 10.1.60.30 zones/disk`results

```
Sorry, your zfs is too old for zrep to safely handle volume initialization
Error: Please initialize volume target by hand, if you won't upgrade
```

zones/g is a zfs `volume` created as `zfs create -V 10G zones/disk`.  
However zfs `filesystem` is doing OK.  
This the latest zrep 1.6.1.  Is this supposed to be or a bug?

**Comment by ppbrown** [comment]
rfHello,

Does your zfs support

zfs recv -o readonly=on

?

**Comment by gkyildirim** [comment]
Sorry for late response.  
It does not support -o readonly option. But my illumos kernel is 1 month old and I could not find a recent illumos commit related. I am not sure if this is ZoL specific.

**Comment by RC1140** [comment]
Sorry to tag onto this , but it looks like smartOS does have the readonly=on option ( based on output from zfs get output). Is there a safe way I can test this without running a sync.

**Comment by RC1140** [comment]
Sigh apologies for the previous message , i was checking the zfs properties on the receiving machine only and didnt check the sending machine. In my scenario the sending doesn't have -o while the receiving does. Would that still be unsafe ?

**Comment by ppbrown** [comment]
I woudl strongly recommand that you keep the zfs on both ends at the same
version. Not just because of zrep, but because perhaps you will hit
inconsistencies between zfs send stream versions or something.
Is this transfer between completely different operating systems? I think
you mentioned illumos(solaris) and ZiL(ZFS on LINUX) ?

**Comment by RC1140** [comment]
The operating systems are the same , just different releases , the actual os is smartos (smartos.org) which is based on illumos

**Comment by ppbrown** [comment]
great!
then I suggest you upgrade :)

**Comment by RC1140** [comment]
Heh there in lies the catch 22 , need to migrate the data off to a new machine while its being upgraded, hence the use of zrep. At the moment I am just testing manually sending the zfs datasets to disk then rsyncing to the remote host and restoring

**Comment by ppbrown** [comment]
okay.
weeeelll...
If there's no data on the volume yet... you could try initializing the
volume from the OTHER side instead.
Then once the replication is set up, do a failover,and you'll be whre you
want to be :)

**Comment by ppbrown** [comment]
closing due to no response from bug filer
