### ISSUE TITLE
Thoughts on handling a missed ZREP_R=-R

### ISSUE THREAD

**Issue by darkpixel** [bolthole/zrep#23]
I stupidly left ```ZREP_R=-R``` out of my latest ```sync all```.
It synced ```tank/virt```, but obviously not all the zvols under it.

Trying a second sync *with* ```ZREP_R=-R``` results in ```ZREP_R=-R ZREP ZREP_INC_FLAG=-i zrep -t zrep-local sync all```.

Should I manually snapshot with the appropriate snapshot name and manually sync it and continue on, or should I give up and start over?  (I'd hate to have to re-sync ~4.8 TB of data over a slow Comcast connection.)

**Comment by ppbrown** [comment]
hi. sorry I havent replied to your other ones... I havent had the focus to
dig into tricky problems lately.


oh.

hmm.

thinking it through... yeah, it could be messy.
very messy. not sure how it would behave.

basicaly, you need to sync it from the last FULL snapshot of EVERYTHING.
I would imagine.



erm...
you might wanna rename the latest zrep top-only snapshot to something else,
then bump back the number on the zrep "lastsent" property.
then run the recursive zrep sync
hmm...

but you'd also have to rollback the remote side to that snapshot first.






On Mon, Aug 15, 2016 at 9:34 PM, Aaron C. de Bruyn <notifications@github.com

**Comment by darkpixel** [comment]
Bumping the lastsent property and rolling back snapshots on the remote end worked perfectly.

No rush on the other tickets--things are working well.
