### ISSUE TITLE
Problem when running via periodic

### ISSUE THREAD

**Issue by stephrdev** [bolthole/zrep#24]
It appears to me that zrep might have a problem when running via periodic.
In the daily output email i can see the following:

```
sending tank/media@zrep_000007 to monique:zroot/media
missing value in property=value argument
usage:
    set <property=value> <filesystem|volume|snapshot> ...

... more output from "zfs set" ...

Expiring zrep snaps on tank/media
Also running expire on monique:zroot/media now...
Expiring zrep snaps on zroot/media
sending tank/projekte@zrep_000007 to monique:zroot/projekte
```

Intresting part here: I think some data is transfered as I can see traffic on the interface. But: zrep status says its quite old. When I run zrep sync all manually via ssh it works fine.

My periodic runner looks like this:

```
cat /usr/local/etc/periodic/daily/800.zrep
#!/bin/sh

/usr/local/bin/zrep sync all
```

Could there be a problem with a "zfs set" call which stores the last synced snapshot?

Master system is FreeBSD 10.1, target is FreeBSD 11.0.

**Comment by ppbrown** [comment]
Your summary of the situation sounds correct.
Dont run (vastly) different versions of zfs on each end of a zrep
replication pair.
It's saying, "oh, i have a reasonably modern system on this end, so it's
safe for me to use the normal way", .. except that way fails on the other
side.

workaround would be to do a "pull" from the other side.

that's in the docs somewhere.

**Comment by stephrdev** [comment]
But why does it work just fine when I run it via SSH in an shell?

**Comment by ppbrown** [comment]
maybe /usr/local/bin isnt in the default path?
make a symlink /usr/bin/zrep -> /usr/local/bin/zrep

**Comment by ppbrown** [comment]
closed due to no followup from user
