### ISSUE TITLE
FreeNAS: proc fs must be functional to use zrep

### ISSUE THREAD

**Issue by Teepareep** [bolthole/zrep#25]
Hello,

Thanks for your efforts on this script. I adjusted the ksch shebang as per your recommendations for FreeNAS (9.3.1). 

```
[root@freenas] ~# ./zrep -i Backup8TB localhost Backup8TB/zrepPool
Setting properties on Backup8TB
Creating snapshot Backup8TB@zrep_000000
Sending initial replication stream to localhost:Backup8TB/zrepPool
Initialization copy of Backup8TB to localhost:Backup8TB/zrepPool complete
[root@freenas] ~# ./zrep -S Backup8TB
Error: /proc fs must be functional to use zrep
[root@freenas] ~# stat /proc/
978896654 92804 drwxr-xr-x 2 root wheel 4294967295 2 "Aug 28 11:38:41 2016" "Aug 28 11:38:41 2016" "Aug 28 11:38:41 2016" "Aug 28 11:38:41 2016" 4096 3 0x800 /proc/
```

Any ideas? I made a zpool called Backup8TB and the dataset has the same name so it seems like this is the proper syntax as calling it with Backup8TB/Backup8TB returned an error. 

```
[root@freenas] ~# zfs list
NAME                                                    USED  AVAIL  REFER  MOUNTPOINT
Backup8TB                                               520K  7.02T    96K  /mnt/Backup8TB
Backup8TB/zrepPool                                       96K  7.02T    96K  /mnt/Backup8TB/zrepPool
[root@freenas] ~# zpool list
NAME           SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
Backup8TB     7.25T   580K  7.25T         -     0%     0%  1.00x  ONLINE  /mnt
```

**Comment by ppbrown** [comment]
you showed that /proc exists. but you didnt show that "procfs" is actually
functional.

What does

ls -l /proc/$$

show ?

**Comment by Teepareep** [comment]
```
[root@freenas] /# ls -l /proc/$$
ls: /proc/29809: No such file or directory
```

**Comment by ppbrown** [comment]
so as I said: procfs is not actually installed.
or, installed but not mounted/working.

Get it working, and then zrep will be happy

**Comment by Teepareep** [comment]
seems like I just need to add it to fstab but i'm going to just stick with the GUI version for now even though it forces it through ssh even for local replication. thanks again.

**Comment by ppbrown** [comment]
FYI: latest commit of zrep no longer requires procfs

83cabd6

**Comment by jdh13** [comment]
Hello all,
i'm using zrep 1.7.3 on FreeNAS-11.2, and unfortunately, it requires procfs, or i missed something.
My context:
host 1: debian 9 + zol + zrep 1.7.3
host 2: FreeNAS-11.2 + zrep 1.7.3

i got this error:
```
root@host1:/# zrep -S datas/partage1
sending datas/partage1@zrep_000001 to host2:datas/partage1
Expiring zrep snaps on datas/partage1
Also running expire on host2:datas/partage1 now...
Error: /proc fs must be functional to use zrep
REMOTE expire failed
```

Adding procfs on host2:

```
[root@host2 /usr/local/bin]# cat /etc/fstab
fdescfs /dev/fd fdescfs rw      0 0
proc    /proc           procfs          rw      0       0
/dev/da1p1.eli  none    swap    sw      0       0
[root@host2 /usr/local/bin]# mount /proc

```
After that, it works
```
root@host1:/datas/partage1# zrep -S datas/partage1
sending datas/partage1@zrep_000002 to host2:datas/partage1
Expiring zrep snaps on datas/partage1
Also running expire on host2:datas/partage1 now...
Expiring zrep snaps on datas/partage1

```

Gérard

**Comment by jdh13** [comment]
really, i missed something, 1.7.4 is the latest release, called "the latest dev version ". I prefer to let my precedent comment, in case it helps freenas user like me. This tool is great!

Thanks
Gérard

**Comment by ppbrown** [comment]
you need to use the latest git version.
not the 1.7.3 release.

**Comment by ppbrown** [comment]
to be clear: you can get the latest git update from here:

https://github.com/bolthole/zrep/raw/master/zrep

the no-procfs version was after 1.7.4
So, after the latest official release.
