### ISSUE TITLE
initial sync failing

### ISSUE THREAD

**Issue by devros42** [bolthole/zrep#27]
I'm running ZFS on linux on two Cent 7.2 boxes.  When I do an initial sync with a small test filesystem it works fine, as do subsequent syncs.  I have now tried it twice on our production fs, which is 13T going from our colo to our office server room and it has failed both times.

ssh keys are setup, and it's working fine on the small fs.  There was no network issues both times I ran it.  It appears that it does complete the transfer of the 1st snap, but then fails. Here is the output.  Any thoughts?

zrep -i xxx/results kbackup.yyy.com chunky
Setting properties on xxx/results
Warning: zfs lacking -o argument
Creating destination filesystem as separate step
Creating snapshot xxx/results@zrep_000000
Sending initial replication stream to kbackup.yyy.com:chunky/results
root@kbackup.yyy.com's password:
Write failed: Broken pipe
cannot open 'Could': dataset does not exist
cannot open 'Could': dataset does not exist
Destroying any zrep-related snapshots from Could
cannot open 'Could': dataset does not exist
Removing zrep-related properties from Could
cannot open 'Could': dataset does not exist
Error: not set readonly for kbackup.yyy.com:chunky/results

**Comment by ppbrown** [comment]
Weell.. for starters, looks like you dont have ssh key trust set up
properly. You THINK you do. but you dont :)
Otherwise, you wouldnt see the pasword prompt.

"root@kbackup.yyy.com <root@kbackup.yyy.com>'s password:"
