### ISSUE TITLE
After zrep Failover we get Unsent Snapshots.

### ISSUE THREAD

**Issue by ximenac** [bolthole/zrep#28]
Hi,

today we did a failover of 2 Filesystems from the Secondary Node to the Primary, and after that, one of the Filesystems on the primary Node created many "Unsent" Snapshots, which of course were not visible on the Secondary Node.
So, the failover of one of the 2 Filesystems worked and the other not.

Here is the Overview:

`Error: Problem doing sync for pool1/apachelogs@p1_apachelogs_000135. renamed to pool1/apachelogs@p1_apachelogs_000135_unsent`

Primary and Secondary Node after the Failover:
- Primary Node:
  `NAME                                                 USED  AVAIL  REFER  MOUNTPOINT
  pool1                                               17.3G  59.8G    32K  /pool1
  pool1/apachelogs                                    54.5M  4.95G  44.3M  /pool1/apachelogs
  pool1/apachelogs@p1_apachelogs_000118          251K      -  43.2M  -
  pool1/apachelogs@p1_apachelogs_000119          256K      -  43.2M  -
  pool1/apachelogs@p1_apachelogs_00011a          260K      -  43.2M  -
  pool1/apachelogs@p1_apachelogs_00011b          266K      -  43.2M  -
  pool1/apachelogs@p1_apachelogs_00011c          243K      -  43.2M  -
  pool1/apachelogs@p1_apachelogs_00011d          210K      -  43.2M  -
  pool1/apachelogs@p1_apachelogs_00011e_unsent   230K      -  43.2M  -
  pool1/apachelogs@p1_apachelogs_00011f_unsent   278K      -  43.3M  -
  pool1/apachelogs@sp1_apachelogs_000120_unsent   288K      -  43.3M  -
  pool1/apachelogs@p1_apachelogs_000121_unsent   294K      -  43.4M  -
  pool1/apachelogs@p1_apachelogs_000122_unsent   296K      -  43.4M  -
  pool1/apachelogs@p1_apachelogs_000123_unsent   328K      -  43.6M  -
  pool1/apachelogs@p1_apachelogs_000124_unsent   370K      -  43.7M  -
  pool1/apachelogs@p1_apachelogs_000125_unsent   364K      -  43.9M  -
  pool1/apachelogs@p1_apachelogs_000126_unsent   376K      -  43.9M  -
  pool1/apachelogs@p1_apachelogs_000127_unsent   370K      -  43.9M  -
  pool1/apachelogs@p1_apachelogs_000128_unsent   372K      -  43.9M  -
  pool1/apachelogs@p1_apachelogs_000129_unsent   376K      -  43.9M  -
  pool1/apachelogs@p1_apachelogs_00012a_unsent   380K      -  43.9M  -
  pool1/apachelogs@p1_apachelogs_00012b_unsent   382K      -  44.0M  -
  pool1/apachelogs@p1_apachelogs_00012c_unsent   400K      -  44.0M  -
  pool1/apachelogs@p1_apachelogs_00012d_unsent   414K      -  44.1M  -
  pool1/apachelogs@p1_apachelogs_00012e_unsent   400K      -  44.2M  -
  pool1/apachelogs@p1_apachelogs_00012f_unsent   403K      -  44.2M  -
  pool1/apachelogs@p1_apachelogs_000130_unsent   406K      -  44.2M  -
  pool1/apachelogs@p1_apachelogs_000131_unsent   412K      -  44.2M  -
  pool1/apachelogs@p1_apachelogs_000132_unsent   402K      -  44.2M  -
  pool1/apachelogs@p1_apachelogs_000133_unsent   405K      -  44.2M  -
  pool1/apachelogs@p1_apachelogs_000134_unsent   426K      -  44.3M  -
  pool1/apachelogs@p1_apachelogs_000135_unsent   326K      -  44.3M  -
  `
- Secondary Node:
  `NAME                                          USED  AVAIL  REFER  MOUNTPOINT
  pool1                                        17.2G  59.8G    32K  /pool1
  pool1/apachelogs                             44.7M  4.96G  43.3M  /pool1/apachelogs
  pool1/apachelogs@p1_apachelogs_000118   252K      -  43.3M  -
  pool1/apachelogs@p1_apachelogs_000119   256K      -  43.3M  -
  pool1/apachelogs@p1_apachelogs_00011a   262K      -  43.3M  -
  pool1/apachelogs@p1_apachelogs_00011b   266K      -  43.3M  -
  pool1/apachelogs@p1_apachelogs_00011c   244K      -  43.3M  -
  pool1/apachelogs@p1_apachelogs_00011d    77K      -  43.3M  -`
- Primary Node FS Properties: 
  `pool1/apachelogs  readonly                       off                            default
  pool1/apachelogs  p1_apachelogs:dest-fs    pool1/apachelogs               local
  pool1/apachelogs  p1_apachelogs:src-fs     pool1/apachelogs               local
  pool1/apachelogs  p1_apachelogs:savecount  5                              received
  pool1/apachelogs  p1_apachelogs:master     yes                            local
  pool1/apachelogs  p1_apachelogs:src-host   sweb1a                         local
  pool1/apachelogs  p1_apachelogs:lock-time  20160930103015                 local
  pool1/apachelogs  p1_apachelogs:dest-host  sweb1b                         local
  pool1/apachelogs  p1_apachelogs:lock-pid   11663                          local`
- Secondary Node FS Properties:
  `pool1/apachelogs  readonly                       on                             local
  pool1/apachelogs  p1_apachelogs:src-host   backupip@sweb1a.ipandmore.de   local
  pool1/apachelogs  p1_apachelogs:dest-host  sweb1b                         local
  pool1/apachelogs  p1_apachelogs:src-fs     pool1/apachelogs               local
  pool1/apachelogs  p1_apachelogs:dest-fs    pool1/apachelogs               local
  pool1/apachelogs  p1_apachelogs:savecount  5                              local`

I didn't see this behavior in our previous test while doing failover or takeover.

Can be that apache was the cause of the problem, while still reading/writing in the filesystem?

In cases like this one, how can we repair the Replication without having to re-do it all over again?

Thanks!
Ximena.

**Comment by ppbrown** [comment]
Well, there are multiple "issues" there.. but the one you should really
care about is, why did the sync fail?
figure that one out, and other stuff should ideally clean up.
apache being active should not be an issue, if your zfs isnt buggy :)

most likely a network problem or ssh key trust issue ?

**Comment by ppbrown** [comment]
no user reply after 5 months. closing.
