### ISSUE TITLE
snapshot sequence exhaustion

### ISSUE THREAD

**Issue by onlime** [bolthole/zrep#3]
Hi Philip

We started using zrep in production and are pretty happy with it so far.
One thing we were concerned of was **snapshot sequence exhaustion**. What happens after we have arrived at sequence "ffffff"? zrep will not catch up the last snapshot sequence correctly in **getlastsnap()**. Proof:

```ksh
#!/bin/ksh -p

oldseq="fffffe"
snapshots=""

for((i=1;i<=5;i++)); do
    snapshots="rpool/demo@zrep_$oldseq\n$snapshots"
    newseq=$((0x$oldseq))
    newseqX=$(printf "%.6x" $(($newseq + 1))  )
    print "$i: $oldseq -> $newseqX"
    oldseq=$newseqX
done

echo
echo "### SNAPSHOTS"
echo -ne "$snapshots"

echo
echo "### LAST_SNAPSHOT"
lastsnap=`echo -ne $snapshots | sed -n '/@zrep_[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]/'p | sort | tail -1`
echo $lastsnap
```

Output of this test:

```
1: fffffe -> ffffff
2: ffffff -> 1000000
3: 1000000 -> 1000001
4: 1000001 -> 1000002
5: 1000002 -> 1000003

### SNAPSHOTS
rpool/demo@zrep_1000002
rpool/demo@zrep_1000001
rpool/demo@zrep_1000000
rpool/demo@zrep_ffffff
rpool/demo@zrep_fffffe

### LAST_SNAPSHOT
rpool/demo@zrep_ffffff
```

Expected last snapshot would be rpool/demo@zrep_**1000002** instead of rpool/demo@zrep_**ffffff**.

If you can fix this easily, please go ahead. If not, no worries - I am perfectly aware that in 32yrs we will no longer be running zrep, even if it's gonna be one of the best scripts in the world. :)
maths under the assumption of running zrep every minute:
```(16^6)/(365*24*60) = ~ 32 years```

Cheers, Philip

**Comment by ppbrown** [comment]
Umm.. yes.
I picked that value, assuming that noone would be insane enough to run the
same filesystem.. LITERALLY the same filesystem.. in production, for 30
years.

And even if they did, the workaround is not too hard. simple renumber the
snapshots on both sides (okay and tweak the property), and you're done.

I hate overly long identifiers, so i find the workaround preferable to a
code change :)
