### ISSUE TITLE
zrep refresh doesn't expire old snapshots

### ISSUE THREAD

**Issue by fmattheus** [bolthole/zrep#30]
after running zrep refresh (from backup server), the old snapshots still exist on both master and slave.  The _expire function is never called.

**Comment by ppbrown** [comment]
Hm.

note to self:

call _expire locally, but "expire -L" on remote master.
also dont forget to call out expiration start.

**Comment by ppbrown** [comment]
added expire calls in latest github version.

please confirm it works for you

**Comment by ppbrown** [comment]
no response. Closing as "probably fixed".  feel free to reopen if this is not true.
