### ISSUE TITLE
Can't initialize zvol on SmarOS

### ISSUE THREAD

**Issue by foxycode** [bolthole/zrep#37]
As we discussed here https://github.com/bolthole/zrep/pull/35 sending zvol on SmartOS doesn't crash, so I'd like to allow initialize for SmartOS. I believe `uname -v` output could be used to identify SmartOS. Sample output:
```
joyent_20161222T003450Z
```

**Comment by ppbrown** [comment]
hmm.

Well, current versions of solaris dont crash with it either.
i'd need to know that even the OLD versions of smartos dont crash.
Do you feel like loading up a historical version somewhere and testing it?
(for the record though, I have a feeling they DO crash. That is to say, old
versions of illumos/opensolaris had that bug too)

if you are interested, here's where I posted about it back in 2012 to the
solaris newsgroup :)
It has technical details n stuff.

https://groups.google.com/forum/#!topic/comp.unix.solaris/-5bcZFInozk

**Comment by foxycode** [comment]
@ppbrown Oldest SmartOS version I was able to download was from 2013-07-06, Don't you if it was fixed before this date?

**Comment by ppbrown** [comment]
I dont know.

If you test on that "oldest version available", and it doesnt crash, I will consider that reasonable enough to justify using a "if joyent_x then okay"  check.

**Comment by foxycode** [comment]
I could, but it's lot of work for me. With other issues I need to solve it's faster for me write own script. Sorry.
