### ISSUE TITLE
Recursive syncing

### ISSUE THREAD

**Issue by nysasounds** [bolthole/zrep#4]
Hi,

I've been looking around for something like this - congrats on a nice solution.

I have a pool that has lots of zfs file systems, some and some of them are what you might call nested :)
What I really want to do is just sync the top level of the pool recursively to an fs in another pool, otherwise I'll have to manually manage a large list file systems as they come and go.

I see from your info that nested file systems are not supported, but a version of this script that can replicate a whole pool using recursive zfs send would be great.

I have created a modified version that does this, it's just some small changes so far, and testing seems fine.

Two questions:

What are the technical reasons for not supporting nested fs syncing?
Would you be interested in incorporating the recursive functionality I've added, details to be discussed?

Thanks in advance.

**Comment by ppbrown** [comment]
yeah its somethign i've been meaning to do.

one problem:

**Comment by ppbrown** [comment]
ARG STUPID GMAIL RETURN!!

One problem.

have you tested it under failure conditions?
What happens when you have successfully synced30 out of your 50
filesystems...
and then something breaks the connection?

everything has to start again.
(and I'm not sure it will recover gracefully. havent tested it...)

**Comment by nysasounds** [comment]
I must admit I hadn't tested failure, but I have now :)

Seems ok.
You end up with some fs with and without the latest zrep snapshot after failure, but on the next sync it seems to recover fine.  All fs then contain the snapshot from the previous sync and the current [ latest one ].
So on initial investigation it seems pretty graceful.

I was worried what would happen if failures went over savecount, but because the snapshots aren't deleted when if the process fails, it copes fine.
I just tested 10 failures in a row, and it recovered properly.

Do you have preference regarding how to implement it in the script?
Make it a global option?  Or an option at sync time that's preserved in a zrep: volume attribute?
Or something else?

I can do the work, fork it, and make a pull request.
Then you can merge it if you like it :)

**Comment by depasseg** [comment]
This would be incredibly helpful.  Any update?

nysasounds - would you be willing to share your version?

**Comment by ppbrown** [comment]
It's that moment you've all been waiting for...

Support for recursive snaps!

Please gimme feed back from

https://github.com/bolthole/zrep/raw/master/zrep

**Comment by darkpixel** [comment]
+1

**Comment by ppbrown** [comment]
Oh. I... aheheheh.. havnet documented how to use it yet :D

set env var of

ZREP_R=-R

as mentioned in the comments near the top.

**Comment by ppbrown** [comment]
erm... I suppose I should mention that transitioning from a previously NOT recursive layout.. to a single-snapshot-baed recursive layout.. is... shall we say.... untested.

i just realized that could get ugly.  Hmm...
mainly from the ZFS side. I'm not sure if it will even let you. 
Will have to test...
(happily, i also made the zrep changeconfig command more friendly to this sort of thing. and also recently added the new sneaky comand "sentsync", to set the "zrep:senttime" property  )

**Comment by ppbrown** [comment]
I have not received any official feedback from others on this requested feature....? Please add one here?

**Comment by nysasounds** [comment]
Sorry - I was doing my own thing for a bit.

Yes, tested and it works well for me on freebsd.
Great work :)
