### ISSUE TITLE
Use nice when sending/receiving data

### ISSUE THREAD

**Issue by foxycode** [bolthole/zrep#41]
I need to run zrep with `nice -n19`, or system is unresponsive. When initialising, that can be long time. It would be nice to have support fir nice command directly in script.

**Comment by ppbrown** [comment]
Sorry, I disagree on this one. It's up to you, to call
"nice zrep xxxx", or not. 
Putting that inside zrep, does not add any missing functionality, so I wont just bloat the code like that.
