### ISSUE TITLE
Not init

### ISSUE THREAD

**Issue by VovanSSS** [bolthole/zrep#42]
Hello

nas4free: zrep# zrep -i raid10/ubuntu1 192.168.40.109 P4Tb/ubuntu1
Sorry, your zfs is too old for zrep to safely handle volume initialization
Error: Please initialize volume target by hand, if you won't upgrade

nas4free: zrep# zfs get -H -o value type raid10/ubuntu1
volume

Is not sent volume.

nas4free: zrep# zfs get -H -o value type raid10/storage
filesystem

nas4free: zrep# zrep status -v
raid10/storage           ->192.168.40.109:P4Tb/storage         Mar  7  4:58 2017

filesystem is ok.

master 192.168.40.110
nas4free: zrep# uname -a
FreeBSD nas4free.local 11.0-RELEASE-p5 FreeBSD 11.0-RELEASE-p5 #0 r309722M: Thu Dec  8 22:52:57 CET 2016     root@dev.nas4free.org:/usr/obj/nas4free/usr/src/sys/NAS4FREE-amd64  amd64

slave 192.168.40.109
nas4free: ~# uname -a
FreeBSD nas4free.local 11.0-RELEASE-p7 FreeBSD 11.0-RELEASE-p7 #0 r312343M: Tue Jan 17 15:41:49 CET 2017     root@dev.nas4free.org:/usr/obj/nas4free/usr/src/sys/NAS4FREE-amd64  amd64

Why not transmitted volume?

**Comment by ppbrown** [comment]
Hmm.

Are you using the latest github version of zrep, or an official released
version?

**Comment by ppbrown** [comment]
nvmind, you arent using latest.
Please use latest version and test it out. :)

https://raw.githubusercontent.com/bolthole/zrep/master/zrep

**Comment by VovanSSS** [comment]
Version updated
`nas4free: zrep# zrep
zrep v1.6.7: a program to replicate a zfs filesystem to another
in an ongoing basis.`


But there was another problem, the transmission happens but ...
`nas4free: zrep# zrep -i raid10/ubuntu1 192.168.40.109 P4Tb/ubuntu1
WARNING: no proper recv -o detected
WARNING: extremely old versions of ZFS crash with volume init
Continuing in 5 seconds....
Setting properties on raid10/ubuntu1
Warning: zfs recv lacking -o readonly
Creating readonly destination filesystem as separate step
Creating snapshot raid10/ubuntu1@zrep_000000
Sending initial replication stream to 192.168.40.109:P4Tb/ubuntu1
cannot mount 'P4Tb/ubuntu1': Invalid argument
Destroying any zrep-related snapshots from raid10/ubuntu1
Removing zrep-related properties from raid10/ubuntu1
Error: Error transferring raid10/ubuntu1@zrep_000000 to 192.168.40.109:P4Tb/ubuntu1. Resetting
`

**Comment by ppbrown** [comment]
Hmm. Previously never-hit code paths! Fun! :)

I just pushed a new version to git. please give it a go.

**Comment by drewer** [comment]
Hi, for your information

FreeBSD 11.0 cant also do init zrep ... same "too old"
with the last version from github now it works...

**Comment by ppbrown** [comment]
Thanks for the confirmation :)
official fix, release v1.6.8
