### ISSUE TITLE
zrep refresh  stopped working after upgrade to 1.7.1.

### ISSUE THREAD

**Issue by moon-hawk** [bolthole/zrep#47]
The following error occurred after (on backupserver node):
` /usr/local/bin/zrep refresh tank01`
> DEBUG: zrep_lock_fs: set lock on tank01
> DEBUG: refresh step 1: Going to jdsstorage01-zrep to snapshot tank01
> DEBUG=1: Befehl nicht gefunden.
> Error: snap of src tank01 on jdsstorage01-zrep failed

So the "command not found" looks like it is not able to make a snapshot on the primary side, what is odd, because both systems are on the same software level.

enviroment:
* FreeBSD 11.0-RELEASE-p2
* zrep-1.7.1 (installed over ports)

setup:
* zrep in backup server scenario (http://www.bolthole.com/solaris/zrep/zrep.documentation.html#backupserver )
* nested filesystems
* recursive replication (every 5 min)

The resolution for now was a rollback to the old version zrep-1.6.2 where it works fine.

The main reason why we want to upgrade to a newer version is that we have another curios problem. We replicate every 5 min and on mondays 03:00 am, the replication stops working. But i'm unsure if it is zrep related so i wanted to check if an upgrade helps.. (so maybe more from that to another time). ;)

**Comment by ppbrown** [comment]
This is very odd. Your error sounds like an EARLIER error, which I fixed, around 1.6.
The diff in the code was:

@@ -399,7 +418,7 @@ zrep_ssh(){
                        ;;
                *)
                        # by default, DEBUG doesnt get passed through ssh
-                       ssh_cmd="$SSH DEBUG=${DEBUG} $1"
+                       ssh_cmd="$SSH $1 DEBUG=${DEBUG}"
                        ;;


So it seems like either you are somehow using that OLD bad code release, or something extremely odd is going on.
adding 
set -x

as the first line of zrep_ssh()
might shed some light there

**Comment by moon-hawk** [comment]
this was kind of related..

after setting "set +x", this was the output:
`DEBUG: zrep_lock_fs: set lock on tank01`
`DEBUG: refresh step 1: Going to jdsstorage01-zrep to snapshot tank01`
`+ typeset ssh_cmd`
`+ ssh_cmd='ssh jdsstorage01-zrep DEBUG=1'`
`+ shift`
`+ ssh jdsstorage01-zrep DEBUG=1 zrep snaponly tank01`
`DEBUG=1: Befehl nicht gefunden.`
`Error: snap of src tank01 on jdsstorage01-zrep failed`

After testing the problem showed up, it is the loginshell on the remote server, it is not ksh but csh.
When the ssh command is invoked, its from inside a ksh shell but the loginshell on remote side breaks this.
zrep would be executed normally with ksh because of the shebang of the script itself, so it never was a problem bevor for us.

i change my 1.7.1 version in a little way to make it work for us again:
`@@ -418,7 +418,7 @@ zrep_ssh(){`
`                        ;;`
`                *)`
`                        # by default, DEBUG doesnt get passed through ssh`
`-                       ssh_cmd="$SSH $1 DEBUG=${DEBUG}"`
`+                       ssh_cmd="$SSH $1 /usr/local/bin/ksh93 -p DEBUG=${DEBUG}"`
`                        ;;`

I added simply the same thing whats the shebang is for zrep here on freebsd.
Changing the login-shell for the replication user was not an option for us.

**Comment by ppbrown** [comment]
Hmmmm...

Thank you for the followup details.
I guess I made a bad assumption that root shell will be derived from
/bin/sh in all cases.
So that means I will have to add some kind of debug commandline flag.
Usually, choices are -v, -V, -d, -D.
Cant use -v or -d, since they are already in use as subcommand flags :-/

So I will probably either have go with -D, or break my own conventions and
use --debug.
Neither make me really happy though. Sigh....

**Comment by ppbrown** [comment]
okay. I just pushed a newer version to git. Please let me know if it works for you or not.

**Comment by moon-hawk** [comment]
sorry for that :/

calling:
`/usr/local/bin/zrep -D refresh tank01`
gives me the debug output:
`DEBUG: zrep_lock_fs: set lock on tank01`
`DEBUG: refresh step 1: Going to jdsstorage01-zrep to snapshot tank01`
`DEBUG: zrep_lock_fs: set lock on tank01`
`zrep_unlock_fs: unset lock on tank01`
`DEBUG: refresh step 2: Pulling tank01@zrep_00e6bc`
`DEBUG: Running local expires on tank01`
`DEBUG: Running remote expires on tank01`
`Expiring zrep snaps on tank01`
`zrep_unlock_fs: unset lock on tank01`

so now i can look into my first problem, hope its not zrep related ;)
ty for your fast help :) 👍

**Comment by ppbrown** [comment]
Would you mind testing my latest-latest git version please?
If it also works fine for you, I will then make an official version bump of zrep.

you'll know it is the new version because in debug, after it says it's "Running remote expires",
it should have another line or two of "DEBUG:" output

**Comment by moon-hawk** [comment]
you are right there is a litle bit more output now:

`DEBUG: zrep_lock_fs: set lock on tank01`
`DEBUG: refresh step 1: Going to jdsstorage01-zrep to snapshot tank01`
`DEBUG: refresh step 2: Pulling tank01@zrep_00eae0`
`_refreshpull: snapname=tank01@zrep_00eae0, fs=tank01`
`DEBUG: zrep_lock_fs: set lock on tank01`
`zrep_unlock_fs: unset lock on tank01`
`DEBUG: Running local expires on tank01`
`DEBUG: Running remote expires on tank01`
`DEBUG: zrep_lock_fs: set lock on tank01`
`Expiring zrep snaps on tank01`
`DEBUG: expiring tank01@zrep_00eadb`                                                                                                                                                                                                           
`zrep_unlock_fs: unset lock on tank01`
`zrep_unlock_fs: unset lock on tank01`

**Comment by ppbrown** [comment]
Thanks. pushing version 1.7.2
