### ISSUE TITLE
Problem replicating top-level default dataset in pool

### ISSUE THREAD

**Issue by stuartthebruce** [bolthole/zrep#48]
Is there a syntax that will allow replication to the top level dataset that by default has the same name as the pool?

For example, after running "zpool create test" I would like to replicate the dataset "test". However, when I run,

zrep -i test rhost test
...
Sending initial replication stream to rhost:test/test

whereas I would like it to replicate to rhost:test rather than rhost:test/test.

Thanks.

**Comment by ppbrown** [comment]
i'm afraid not.
in theory, you could do a manual initialization of the first run. then subsequent syncs might work.

**Comment by stuartthebruce** [comment]
OK. I am just beginning to test zrep and will push my dataset down one level.

**Comment by moon-hawk** [comment]
i can confirm ppbrown's assumtion
we have tested that and using it in production for nearly a year now

as ppbrown said, to get it working you have to do the initialization manually (as discribed in documentation)
along the way you have to manipulate the **zrep:dest-fs** two times to fit your needs
the first time at the sending site, before first sending the initial snapshot, in your case something like:
`zfs set zrep:dest-fs=test test`

and the same thing you have to do at the recieving site after the initial manual send
`zfs set zrep:dest-fs=test test`

after that feel free to also implement recursive syncing, thats what we do with that. this way you can have completly synced pools :)

(but as always do a proper testing before pushing it to production.)

**Comment by stuartthebruce** [comment]
Good to know this can be worked around in practice. Even better would be if zrep directly supported replication at the top-level default dataset name == pool name.

**Comment by ppbrown** [comment]
After a bit of experimentation, it turns out that supporting this is quite straightforward, so long as it isnt an ancient version of ZFS.
So, latest git version supports direct-to-pool replication now.

Note that as a side effect, it umounts the pool, if it was already mounted.
please confirm it works for y'all

**Comment by stuartthebruce** [comment]
This now fails with an error about a missing dataset name for destination filesystem, e.g., on a system with a zpool named dcc attempting to replicate that generates,

# zrep version
zrep 1.7.3
http://www.bolthole.com/solaris/zrep
http://www.github.com/bolthole/zrep

# zrep init dcc dcc3 dcc
Setting properties on dcc
WARNING: forcing override sync to top level pool dcc3:dcc
Not using a usual sub-filesystem
Warning: zfs recv lacking -o readonly
Creating readonly destination filesystem as separate step
cannot create 'dcc': missing dataset name
Error: Cannot create dcc3:dcc

**Comment by ppbrown** [comment]
The behaviour might change now that the "recv -o" detection has been updated.
Please recheck against latest git?

**Comment by ppbrown** [comment]
ping.... 
please recheck for me, or will close soon presumed fixed.
