### ISSUE TITLE
Avoid snapshots when no filesystem change?

### ISSUE THREAD

**Issue by stuartthebruce** [bolthole/zrep#49]
Is there an option for "zrep sync" to avoid creating and sending snapshots when there have been no changes to the source filesystem since the last sync? For example, use zfs diff (or some other ZFS mechanism) to check if there have been any changes before making a snapshot? Or add an option to wait for inotify to indicate there has been a change?

**Comment by ppbrown** [comment]
Why would you want this?

**Comment by stuartthebruce** [comment]
The motivation is minimizing latency while taking into account SSD write endurance. In my first at scale test of a continuous "zrep sync" loop for an infrequently modified filesystem that uses read-optimized SSD each SSD drives is sustaining 2MByte/s write from zrep (300 IOPS according to iostat). This exceeds the long-term write endurance of the drives by a factor of 2.

While I can obviously add a sleep between sync calls it would be nice to not introduce that latency or have to hand tune that number.

Another option, would be to have the application that modifies the filesystem initiate zrep sync when most appropriate, however, it would be nice to think of zrep is just doing the optimal thing at the filesystem layer independent of the running application.

**Comment by ppbrown** [comment]
Hmm.

Well, some poeople would like this behaviour, and some people would prefer
the current behaviour.
Perhaps I'll add a flag to sync, that says only copy on change.
Suggestions for a flag letter?

**Comment by stuartthebruce** [comment]
How about -f for force, i.e.,

zrep (sync|-S) (force|-f) [-q seconds] all

where force indicates that even if there are no changes to the filesystem since the last snapshot that a new snapshot should be created and the empty incremental snapshot sent to the destination. However, if there are no changes and force is not specified then now snapshot is created.

**Comment by ppbrown** [comment]
nope. you went the opposite way i was asking for :-}

I added sync -c. 
please check latest git push

**Comment by stuartthebruce** [comment]
Thanks for the quick update to test. It looks like "sync -c" is creating a new snapshot to run "zfs diff" against before deciding whether or not to send. How about running zfs diff against the current live dataset to decide even earlier if a snapshot needs to be made?

I think it also makes sense to not save the zfs diff output to a temporary file that has to be cleaned up, but rather just check if the output is non-empty, e.g., "zfs diff | wc -l".

I also see a zfs usage message indicating a missing dataset name, e.g.,

# ./zrep sync -c dcc/data
[root@dcc-new1 ~]# ./zrep sync -c dcc/data
+ [[ yes != '' ]]
+ _sync_nochanges dcc/data@zrep_00c243 dcc/data@zrep_00c245
+ tmpfile=/tmp/zrep.23251.c
+ typeset changecheck tmpfile
+ rm -f /tmp/zrep.23251.c
+ zfs diff -H dcc/data@zrep_00c243 dcc/data@zrep_00c245
+ 1> /tmp/zrep.23251.c
+ [[ 0 -ne 0 ]]
+ test -s /tmp/zrep.23251.c
+ _debugprint sync_nochanges updating dcc/data@zrep_00c243 and returning true
+ [[ '' != '' ]]
+ rm -f /tmp/zrep.23251.c
+ return 0
+ _debugprint '_sync updating timestamp but NOT doing sync since no change'
+ [[ '' != '' ]]
+ (( Z_HAS_SNAPPROPS ))
+ zfs set 'zrep:sent=1495153523'
missing dataset name
usage:
	set <property=value> <filesystem|volume|snapshot> ...
...

**Comment by ppbrown** [comment]
Good point about doing a diff against current data. i forgot you can do
that.

I have to use tempfile though because I also need to check whether zfs
actually SUPPORTS doing diff.
You cant check if the zfs command failed, when you use a pipe at the end.

**Comment by stuartthebruce** [comment]
It looks like ksh can capture the exit status of "zfs diff" and pipe the output, e.g.,
https://unix.stackexchange.com/questions/76162/how-do-i-capture-the-return-status-and-use-tee-at-the-same-time-in-korn-shell

**Comment by ppbrown** [comment]
holey yuck!
according to that article, only zsh and bash have clean ways to do that. ksh does not have a *clean* way.
So I'll stick to my existing way.

**Comment by stuartthebruce** [comment]
What about checking stdout and stderr separately rather than using the exit() status of zfs? Presumably a version of ZFS that doesn't support diff will output an error message on stderr?

The reason I am suggesting avoiding a temporary file, is I suspect the output of zfs diff could be quite large if there have been a lot of changes. However, I haven't run any tests.

**Comment by ppbrown** [comment]
possibly. but that would itself also need to use a temp file I think :-}

**Comment by stuartthebruce** [comment]
I think process substitution may be the way to go with ksh, e.g.,

read out < <(zfs diff ...)
status=$?

status will then have the zfs exit status and out will have the first line of stdout output to determine if there was any differences.

**Comment by ppbrown** [comment]
please show a full example of that, rather than a truncated one

**Comment by ppbrown** [comment]
I think I fixed the "missing dataset" bug

**Comment by stuartthebruce** [comment]
Here is an example ksh script that distinguishes the 3 possibilities of running zfs diff on the argument(s) presented: unrecognized command, diff output, and no diff output.

Note, zfs diff can take a long time to run if there are significant differences, so this only reads the first line of diff output to determine if there are any differences. You can change "zfs diff" to "zfs bogus" to see that stderr is captured and displayed on stdout.

#!/bin/ksh

tmpfile="/tmp/zrep.$$.c"

# Save original stderr and redirect to tmpfile
exec 4<&2;
exec 2> $tmpfile

# Read the first line of output from zfs diff
read diff < <(zfs diff $*)

# Restore original stderr
exec 2<&4

# Distinguish the 3 cases of zfs diff being an invalid command, no diff, or diff output
if test -s $tmpfile ; then
	echo "zfs diff command generated the following error:"
	cat $tmpfile
else
	if [ -z "$diff" ]; then
		echo "No zfs diff detected"
	else
		echo "zfs diff detected"
	fi
fi
rm -f $tmpfile

**Comment by ppbrown** [comment]
its kind of a neat idea.
however, when I tested it with a simplified version, of:

read value <$(zfs help)
echo status is $?
value is $value


the read, did not stop at one line.

So, there's problems.

also, I really dont like all that exec switching.

**Comment by stuartthebruce** [comment]
That first example does not require the use of $? as the error condition is determined by the content of the tmpfile. However, it occurred to me that what is needed is simply a test of whether: a) zfs diff ran successfully and had no output, in which case no need to take a zfs snapshot; or b) if zfs diff generated and error or a list of differences, in which case a zfs snapshot must be taken. Here is a much simpler example that does that without creating any temporary files, using $?, or using exec:

#!/bin/ksh
read diff < <(zfs diff $* 2>&1)

if [ -z "$diff" ]; then
    echo "Skip snapshot: zfs diff determined there where no filesystem changes to replicate"
else
    echo "Create a snapshot: zfs diff either found filesystem changes or failed to run"
fi

**Comment by ppbrown** [comment]
But what happens when output is really long?
Does it early truncate?
or does it keep running?
also, your test does not behave predictably when "zfs diff" is invalid.
Since you dont differentiate between "here's some diff output" vs "here's
some ERROR messages".

**Comment by stuartthebruce** [comment]
My example truncates after the first line. Without that, zfs diff will take too long to be useful.

I don't see why you need to distinguish. If "zfs diff" generates an error message (e.g., unsupported option", or if "zfs diff" generates output indicating there have been changes in the filesystem, then I believe zrep should take the same action. In particular, take a snapshot and send the incremental update. Or am I missing something?

**Comment by ppbrown** [comment]
thing is, on my system, the <$() does not read ONE line. it merges them for
some reason.
Has a bunch of ^Js in the variable, which is UNIX linefeed.

as to why I need to distinguish....
ah.
hm. good point. requires same handling either way.

Well, in THAT case, i dont even need the fancy redirection.
just

checkval=`zfs diff .. 2>&1 |head -1`

**Comment by stuartthebruce** [comment]
The zfs CLI has annoying stdout buffering when run non-interactively, at least on Linux. Therefore, I think the following is the most robust way to quickly get the first line of "zfs diff" output and then stop it from scanning any further (since zfs diff can run for a long time).

#!/bin/ksh
diff=$(unbuffer zfs diff $* 2>&1 | head -1)
pkill -P $$

if [ -z "$diff" ]; then
    echo "No zfs diff detected"
else
    echo "Need to create a snapshot, eiteher a zfs diff failed to run or found a difference"
    echo "$diff"
fi

**Comment by stuartthebruce** [comment]
I had naively assumed zfs diff was a readonly operation. Unfortunately, it creates a temporary snapshot so that doesn't solve the original problem of avoiding unnecessary write operations to read-optimized SSD drives when there are no filesystem changes. Furthermore, the performance of zfs diff appears to be problematic while active changes are being made.

The best read-only hack I have found is to monitor the output of zdb and track changes to transaction groups in the uberblock. However, that is probably not a good way to go in general as that is not part of the public ZFS API.

It looks like I will end up running zrep sync relatively infrequently (perhaps 1 per minute) and if that latency is not good enough add an application specific trigger to call zrep sync when it knows a filesystem change has been made.

 It is a shame there is not readonly variable exposed via zfs get that exposes the timestamp of the last dataset change, or even just the appropriate txg values available via zdb.

Can you think of any other way (even if outside of zrep itself) to check whether there have been any changes that make it necessary to call zrep sync?

**Comment by mailinglists35** [comment]
you don't need to `zfs diff` if the only thing you want to check is if there is a modification. `zfs get -p written` is way faster.

from manual:

````
       written

           The amount of space referenced by this dataset, that was written since the previous snapshot (i.e. that is not referenced by the  previous
           snapshot).

       written@snapshot

           The amount of referenced space written to this dataset since the specified snapshot.  This is the space that is referenced by this dataset
           but was not referenced by the specified snapshot.

           The snapshot may be specified as a short snapshot name (just the part after the @), in which case it will be interpreted as a snapshot  in
           the  same  filesystem  as this dataset.  The snapshot be a full snapshot name (filesystem@snapshot), which for clones may be a snapshot in
           the origin's filesystem (or the origin of the origin's filesystem, etc).

````

**Comment by stuartthebruce** [comment]
Perfect. The written attribute is not available on all versions of ZFS, but it would be great if sync -c used this if available rather than zfs diff. Thanks.

**Comment by ppbrown** [comment]
sighhh..
I figured this sounded too easy.

I need some efficient way of determining whether or not to use that
property.

**Comment by stuartthebruce** [comment]
If it helps, on a Solaris 11 system that does not have this attribute an attempt to run "zfs get -p written dataset" generates a stderr message and exit value of 2, e.g.,

root@samhome1:~# cat /etc/release
                             Oracle Solaris 11.3 X86
  Copyright (c) 1983, 2016, Oracle and/or its affiliates.  All rights reserved.
                            Assembled 03 August 2016

root@samhome1:~# zfs get -p written rpool > /dev/null
bad property list: invalid property 'written'
For more info, run: zfs help get

root@samhome1:~# echo $?
2

**Comment by tschoening** [comment]
> Can you think of any other way (even if outside of zrep itself) to check whether there have been any changes that make it necessary to call zrep sync?

Interesting discussion and feature request... Does `zfs get -p written` take things like only timestamp/ attribute/ACL changes etc. into account? Can there even be any change in ZFS which doesn't result into at least some amount of data newly written? In the end it's CoW.

How about using [inotifywait](https://linux.die.net/man/1/inotifywait) or something comparable? If you are really heavy read-only and are able to organize you writes into some monitored directories/files mainly, you could only call `zrep` as needed, maybe with some additional time delay. All writes outside your monitored writes could be synced less frequently once an hour or whatever using `cron`.

**Comment by olevole** [comment]
With inotifywait, zrep turn into the another Linux-only software. Also, set up stuff  to monitor changes on full FS will cost much more than ZFS snapshot which are very cheap

**Comment by tschoening** [comment]
I might have been not clear: I was not suggesting to implement usage of `inotifywait` into `zrep` directly, but was just suggesting something @stuartthebruce or anyone else with that problem might not had in mind yet. One doesn't necessarily need `zrep` to detect changes on it's own, if the platform used provides other tools to do so and just call `zrep` on events one is interested in. Might even be more flexible in some use cases.

**Comment by stuartthebruce** [comment]
> Interesting discussion and feature request... Does zfs get -p written take things like only timestamp/ attribute/ACL changes etc. into account?

`zfs get -p written` does indeed take into account metadata only changes.

**Comment by ppbrown** [comment]
Note for future:
I could potentially support this by adding some special additional flag to the sync, to do the (is modified?)
check.
Then the extra overhead for os-specific hacks could be justified IMO.


Something like "zrep sync -m ..."

**Comment by stuartthebruce** [comment]
@ppbrown that would be great. I am still interested in avoiding the extra overhead of creating a snapshot and checking for changes when there are none (on systems that support the written flag).

**Comment by ppbrown** [comment]
thanks for the bump.

Please send me sample output for the following commands:

zfs get written  somefs@snap     # no changes
zfs get -p written  somefs@snap  # no changes
zfs get written  somefs@snap        # changes present
zfs get -p written  somefs@snap    # changes present

**Comment by stuartthebruce** [comment]
It is "zfs gert -p written somefs" this is of interest as that will show a 0 if there is no change since the last snapshot.

<pre>
[root@dcc2 ~]# zfs get written home/s3
NAME     PROPERTY  VALUE    SOURCE
home/s3  written   96K      -
[root@dcc2 ~]# zfs get -p written home/s3
NAME     PROPERTY  VALUE    SOURCE
home/s3  written   98304    -
[root@dcc2 ~]# zfs snapshot home/s3@test
[root@dcc2 ~]# zfs get written home/s3
NAME     PROPERTY  VALUE    SOURCE
home/s3  written   0        -
[root@dcc2 ~]# zfs get -p written home/s3
NAME     PROPERTY  VALUE    SOURCE
home/s3  written   0        -
[root@dcc2 ~]# zfs get written home/s3@test
NAME          PROPERTY  VALUE    SOURCE
home/s3@test  written   96K      -
[root@dcc2 ~]# zfs get -p written home/s3@test
NAME          PROPERTY  VALUE    SOURCE
home/s3@test  written   98304    -
[root@dcc2 ~]# echo abc > /home/s3/abc
[root@dcc2 ~]# zfs get written home/s3
NAME     PROPERTY  VALUE    SOURCE
home/s3  written   64K      -
[root@dcc2 ~]# zfs get -p written home/s3
NAME     PROPERTY  VALUE    SOURCE
home/s3  written   65536    -
[root@dcc2 ~]# zfs get written home/s3@test
NAME          PROPERTY  VALUE    SOURCE
home/s3@test  written   96K      -
[root@dcc2 ~]# zfs get -p written home/s3@test
NAME          PROPERTY  VALUE    SOURCE
home/s3@test  written   98304    -
</pre>

**Comment by ppbrown** [comment]
okay thanks.

going to dinner. note to self in case I get distracted:

implement "zrep uptodate" then base around that.

**Comment by ppbrown** [comment]
please check latest, to see if "zrep uptodate" works as expected.
I can then optimize further.

**Comment by ppbrown** [comment]
Bump

**Comment by stuartthebruce** [comment]
`zfs uptodate` in zrep version 1.7.6 works as expected on SL7 running zfs 0.8.1, i.e., it returns a 0 if and only if there have been no changes since the last `zrep sync`.
