### ISSUE TITLE
Auto clear after failed initializtion

### ISSUE THREAD

**Issue by stuartthebruce** [bolthole/zrep#50]
zrep does a nice job cleaning up if "zrep -i" is interrupted once the initial snapshot begins transferring, however, it might make sense to have it also clean up (zrep clear) the source dataset if there are any initial error conditions before then, e.g., unable to SSH to the destination machine, or an incorrect remote dataset specified.

**Comment by ppbrown** [comment]
sometimes, this could be convenient. but other times, it might interfere with debugging efforts.
So I think i'm going to count this as a "wontfix".
