### ISSUE TITLE
zrep clear internal error

### ISSUE THREAD

**Issue by stuartthebruce** [bolthole/zrep#54]
[root@dcc3 ~]# zrep version
zrep 1.7.3
http://www.bolthole.com/solaris/zrep
http://www.github.com/bolthole/zrep

[root@dcc3 ~]# zrep list
dcc/data

[root@dcc3 ~]# zrep clear |& head
WARNING: Removing all zrep configs and snapshots from
 (for TAG=zrep)
Continuing in 10 seconds
Destroying any zrep-related snapshots from
Error: zrep internalerror: no arg for list_autosnaps
Removing zrep-related properties from
missing dataset argument
usage:
	inherit [-rS] <property> <filesystem|volume|snapshot> ...

However, explicitly specifying the dataset to clear worked,

[root@dcc3 ~]# zrep clear dcc/data
WARNING: Removing all zrep configs and snapshots from dcc/data
 (for TAG=zrep)
Continuing in 10 seconds
Destroying any zrep-related snapshots from dcc/data
Removing zrep-related properties from dcc/data

If zrep clear has a hard requirement for a dataset argument then the error message should come from zrep rather than an underlying zfs command. However, I think it makes sense for "zrep clear" with no argument imply clearing all zrep  info.

Thanks.

**Comment by ppbrown** [comment]
I strongly disagree that no arguments means "clear EVERYTHING". 
But, point taken about better error messages.
git updated.
