### ISSUE TITLE
How to initialize recusively pre-synced filesystem?

### ISSUE THREAD

**Issue by SanderM2** [bolthole/zrep#56]
I have two systems that were synced manually and are now like this:

SOURCE:
/pool/folderA/folder1
/pool/folderA/folder2
/pool/folderA/folder3

TARGET:
/pool/backup/folderA/folder1
/pool/backup/folderA/folder2
/pool/backup/folderA/folder3

The latest snapshots are named "@zrep-backup_000000" 
SOURCE and TARGET were synced using zfs send/recv manually

So folder1, folder2 and folder3 are in sync but I want to start using zrep for them now.

What would be the correct way to initialize this for zrep?

The documentation talks about setting flags like this:

srchost# "zrep changeconfig -f srcfs desthost destfs"
desthost# "zrep changeconfig -f -d destfs  srchost srcfs"

Should I do this for all 3 folders or just for the parent folder "folderA" ?

Thanks for any help!

**Comment by ppbrown** [comment]
Hello,

you cant just decide to change sync point when you feel like it. Nor can
you just do it on a "folder" basis. It's a whole-filesystem operation.
So, you would have to do the zrep change config for each of the 3
filesystems you previously synced.

For ongoing replication, you can choose to either have 3 separate jobs, or
you can have a single run run with

zrep sync all

**Comment by SanderM2** [comment]
I got it working -:)

Thanks!
