### ISSUE TITLE
local sync fails: REMOTE expire failed

### ISSUE THREAD

**Issue by mmcoolc** [bolthole/zrep#57]
Hi!
I have an external hard disk attached to my NAS, running nas4free (based on free bsd). "Zrep init" works well with the argument "localhost". But "zrep sync all" gives me the following message:

sending pool1/test@zrep_000004 to localhost:backup1/test
Expiring zrep snaps on pool1/test
Also running expire on localhost:backup1/test now...
./zrep[429]: eval[1]: zrep: not found [No such file or directory]
REMOTE expire failed

As you can see in the snapshot no zrep_000004 I have tried it several times and the snapshots are generated, but transferring them to the external does not work.

Thanks for your help in advance.

**Comment by ppbrown** [comment]
hello,
you need to either put zrep in one of the standard locations for your $PATH variable, or you need to set
ZREP_PATH to be the full path to where you have zrep
