### ISSUE TITLE
 ZREP_R=-R zrep sync all does not delete remote target if source/sub1 is removed

### ISSUE THREAD

**Issue by truatpasteurdotfr** [bolthole/zrep#58]
```
zfs create pool/top
zfs create pool/top/sub1
zfs create pool/top/sub2
ZREP_R=-R zrep init   pool/top  remoteserver pool/backup/top
ZREP_R=-R zrep sync all
```
pool/top/{sub1,sub2} are now synced
```
zfs create pool/top/sub3
ZREP_R=-R zrep sync all
```
pool/backup/top/sub3 is created and
pool/top/{sub1,sub2,sub3} are now synced with pool/backup/top/{sub1,sub2,sub3}

now if I do:
```
zfs destroy -r pool/top/sub1
ZREP_R=-R zrep sync all
ZREP_R=-R zrep sync status
```
the original pool/top/sub1 is gone from the source server but it is not deleted on remoteserver.
source: pool/top/{sub2,sub3}
remoteserver: pool/backup/top/{sub1,sub2,sub3}

expected result: pool/backup/top/sub1 is deleted or some warning error messages.

**Comment by ppbrown** [comment]
interesting.
however... zrep just uses ZFS replication for this. The behaviour you describe, could be considered a "bug in zfs" ;-)
So, you might complain to the ZFS people if you care strongly about this :)
Sorry, I have no plans to write a lot of code to fix or detect this behaviour. That sounds like it could get way out of hand.

**Comment by truatpasteurdotfr** [comment]
Fair enough, that is ZoL 0.6.5.10 in case that matters.

**Comment by truatpasteurdotfr** [comment]
zfs man page seems toimply that one needs -F flag to allow removal of the deleted from sources filesystems/snapshot.

```
           -R

               Generate a replication stream package, which will replicate the
               specified  filesystem,  and  all descendent file systems, up to
               the named snapshot. When received, all  properties,  snapshots,
               descendent file systems, and clones are preserved.

               If the -i or -I flags are used in conjunction with the -R flag,
               an incremental replication stream  is  generated.  The  current
               values  of  properties,  and  current  snapshot and file system
               names are set when the stream is received. If the  -F  flag  is
               specified when this stream is received, snapshots and file sys‐
               tems that do not exist on the sending side are destroyed.

```
