### ISSUE TITLE
Multiple backup targets

### ISSUE THREAD

**Issue by darkpixel** [bolthole/zrep#6]
I have been using zrep for a few months now.  Thanks for such an insanely useful script.

We recently had a client lose 5 out of 8 drives in a RAIDZ2 all within 38 hours.  We couldn't replace and resilver drives fast enough before the pool was destroyed.

We use zrep to sync data off-site, and it worked perfectly.  After the drives were replaced and the pool was re-created, we were able to restore from the off-site backup.  Unfortunately the restore took ~13 hours and my client wants options for restoring faster.

They didn't like Andrew's option of a fully-loaded station wagon laden down with tapes...(https://en.wikipedia.org/wiki/Sneakernet#Non-fiction)

One option I am considering is having an external USB backup drive and having zrep sync to it.  As far as I can tell, zrep can only sync to one target...

Any thoughts on having it support multiple backup targets?

**Comment by ppbrown** [comment]
Hello,

I guess you didnt check back to see if zrep has been updated?
I recently released zrep 1.3.1 that supports multiple targets :)
Online documentation has been updated.

http://www.bolthole.com/solaris/zrep/zrep.documentation.html#multi

On Tue, Sep 8, 2015 at 11:25 PM, Aaron C. de Bruyn <notifications@github.com

**Comment by darkpixel** [comment]
*Awesome*!

Can I buy you a beer?

**Comment by ppbrown** [comment]
heh, heh...
well its a long way from Washington State, to Los Angeles. But feel free to
paypal me something, or buy something on my amazon wishlist :)

**Comment by darkpixel** [comment]
Done.  I'll send tracking numbers to your e-mail address.  Thanks again.
