### ISSUE TITLE
RFE adding http://bolthole.com/solaris/zrep to github repository

### ISSUE THREAD

**Issue by truatpasteurdotfr** [bolthole/zrep#60]
Adding http://bolthole.com/solaris/zrep/index.html to https://github.com/bolthole/zrep.

- missing usual README.md on the github page
- provide example usage and source at a single place

does that make sense? :P

**Comment by ppbrown** [comment]
index.html is not readme.md :)
single place for everything, is actually unusual. to me. Most nice software tends to have a "real" webpage, and then a pointer to github.

other than full docs, what things do you think would benefit from having readme.md?

**Comment by ppbrown** [comment]
Closing due to lack of user feedback
