### ISSUE TITLE
ZREP_R=-R needs and additionnal  -F flag is one want to propage deleted filesystems

### ISSUE THREAD

**Issue by truatpasteurdotfr** [bolthole/zrep#61]
Maybe just add a comment in the zrep script? (see comments added in the closed #58 issues)

**Comment by ianabc** [comment]
I've got an existing zrep setup and I occasionally something related (I think)
```
ZREP_PATH=/usr/local/sbin/zrep ZREP_R=-R /usr/local/sbin/zrep sync tank/fs1
sending tank/fs1@zrep_00002d to 37zfs2:tank/37zfs1/fs1
cannot receive new filesystem stream: destination 'tank/37zfs1/fs1/chold/fs' exists
must specify -F to overwrite it
```
The target machine (37zfs1) only exists as a backup so I'm not sure how this can happen.

For the moment I've just been destroying the named destination and restarting the zrep, but -F seems appropriate to what I'm trying to do.

**Comment by truatpasteurdotfr** [comment]
I only fear that pushing the -F on the receiver side might destroy already existing zfs filesystems if one mistype the target pool...

**Comment by ppbrown** [comment]
well, not if you're using zrep.
worst case it will do an unscheduled refresh of a source system to a target
fs?

**Comment by ppbrown** [comment]
oops. old issue and seems like I made a workaround/unsafety flag a long time ago already.

You can either use zrep sync -f ....  , or set environtment var ZREP_FORCE=-f
It will then add -F, to the zfs receive
