### ISSUE TITLE
DEBUG mode prints usage message

### ISSUE THREAD

**Issue by stuartthebruce** [bolthole/zrep#63]
Is it a bug or a feature that DEBUG=1 results in print the zrep usage message? For example,

[root@dcc1 ~]# env DEBUG=1 zrep -t zrep-dcc2 sync dcc/data
DEBUG: zrep_lock_fs: set lock on dcc/data
sending dcc/data@zrep-dcc2_000029 to dcc2:dcc/data
Expiring zrep snaps on dcc/data
DEBUG: expiring dcc/data@zrep-dcc2_000024
Also running expire on dcc2:dcc/data now...
ERROR: Dont know what to do with: -D -t zrep-dcc2 expire dcc/data

zrep v1.7.3: a program to replicate a zfs filesystem to another
in an ongoing basis.

  Philip Brown, 2012-2017

Simple usage summary:
zrep (init|-i) ZFS/fs remotehost remoteZFSpool/fs

**Comment by ppbrown** [comment]
I'm guessing you didnt upgrade other side to latest version?

**Comment by stuartthebruce** [comment]
Both systems are running version 1.7.3.

[root@dcc1 ~]# zrep version
zrep 1.7.3
http://www.bolthole.com/solaris/zrep
http://www.github.com/bolthole/zrep

[root@dcc2 ~]# zrep version
zrep 1.7.3
http://www.bolthole.com/solaris/zrep
http://www.github.com/bolthole/zrep

**Comment by ppbrown** [comment]
To look into this further, id' need you to tweak the remote side, and add in:

diff --git a/zrep b/zrep
index 21d2813..8d68cbe 100755
--- a/zrep
+++ b/zrep
@@ -2158,6 +2158,9 @@ usage(){
        print 'See the above documentation for details on using the -t flag'
 }

+echo zrep args are: $@
+set -x
+
 #special case this. sigh...
 if [ "$1" == "-D" ] ; then
        DEBUG=1

**Comment by stuartthebruce** [comment]
That patch results in the following output.

[root@dcc1 ~]# env DEBUG=1 zrep -t zrep-dcc2 sync dcc/data
DEBUG: zrep_lock_fs: set lock on dcc/data
sending dcc/data@zrep-dcc2_0004cd to dcc2:dcc/data
Expiring zrep snaps on dcc/data
DEBUG: expiring dcc/data@zrep-dcc2_0004c8
Also running expire on dcc2:dcc/data now...
zrep args are: -t zrep-dcc2 -D -t zrep-dcc2 expire dcc/data
ERROR: Dont know what to do with: -D -t zrep-dcc2 expire dcc/data

zrep v1.7.3: a program to replicate a zfs filesystem to another
in an ongoing basis.

  Philip Brown, 2012-2017

+ [ -t '==' -D ]
+ [ -t '==' -t ]
+ [ zrep-dcc2 '==' '' ]
+ ZREPTAG=zrep-dcc2
+ shift
+ shift
+ [[ zrep-dcc2 != zrep ]]
+ ZREP_INC_FLAG=-i
+ [ zrep-dcc2 '!=' '' ]
+ ZREP_PATH='zrep -t zrep-dcc2'
+ ZREP_INC_FLAG=-i
+ print 'ERROR: Dont know what to do with: -D' -t zrep-dcc2 expire dcc/data
+ print ''
+ usage
+ print zrep v1.7.3: a program to replicate a zfs filesystem to another
+ print in an ongoing basis.
+ print ''
+ print '  Philip Brown, 2012-2017'
+ print ''
+ print Simple usage summary:
Simple usage summary:
zrep (init|-i) ZFS/fs remotehost remoteZFSpool/fs
zrep (sync|-S) [-q seconds] ZFS/fs
zrep (sync|-S) [-q seconds] all
zrep (sync|-S) ZFS/fs@snapshot    -- temporary retroactive sync
zrep (status|-s) [-v] [(-a|ZFS/fs)]
zrep refresh ZFS/fs               -- pull version of sync
zrep (list|-l) [-Lv]  [fs/names]
zrep (list|-l) -s     [fs/names]  -- list snapshots
zrep (expire|-e) [-L] (ZFS/fs ...)|(all)|()
zrep (changeconfig|-C) [-f] ZFS/fs remotehost remoteZFSpool/fs
zrep (changeconfig|-C) [-f] [-d] ZFS/fs srchost srcZFSpool/fs
zrep failover [-L] ZFS/fs
zrep takeover [-L] ZFS/fs
zrep version
zrep clear [-f] ZFS/fs  -- REMOVE ZREP CONFIG AND SNAPS FROM FILESYSTEM

   -q option says to Quietly ignore locked filesystems that have synced
      more recently than the given amount of seconds

Paired commands for high-transaction systems:
   zrep snaponly ZFS/fs
   zrep synconly ZFS/fs
The above two commands split the simple sync subcommand, into two
separate steps, so that a database, etc. may resume while the sync
completes in the background

zrep defaults to using ssh. However, if remotehost is set to localhost,
zrep will use a simple pipe instead.

 More detailed examples can be found at:
http://www.bolthole.com/solaris/zrep/zrep.documentation.html

See the above documentation for details on using the -t flag
+ print 'zrep (init|-i) ZFS/fs remotehost remoteZFSpool/fs'
+ print 'zrep (sync|-S) [-q seconds] ZFS/fs'
+ print 'zrep (sync|-S) [-q seconds] all'
+ print 'zrep (sync|-S) ZFS/fs@snapshot    -- temporary retroactive sync'
+ print 'zrep (status|-s) [-v] [(-a|ZFS/fs)]'
+ print 'zrep refresh ZFS/fs               -- pull version of sync'
+ print 'zrep (list|-l) [-Lv]  [fs/names]'
+ print 'zrep (list|-l) -s     [fs/names]  -- list snapshots'
+ print 'zrep (expire|-e) [-L] (ZFS/fs ...)|(all)|()'
+ print 'zrep (changeconfig|-C) [-f] ZFS/fs remotehost remoteZFSpool/fs'
+ print 'zrep (changeconfig|-C) [-f] [-d] ZFS/fs srchost srcZFSpool/fs'
+ print 'zrep failover [-L] ZFS/fs'
+ print 'zrep takeover [-L] ZFS/fs'
+ print 'zrep version'
+ print 'zrep clear [-f] ZFS/fs  -- REMOVE ZREP CONFIG AND SNAPS FROM FILESYSTEM'
+ print
+ print '   -q option says to Quietly ignore locked filesystems that have synced'
+ print '      more recently than the given amount of seconds'
+ print
+ print 'Paired commands for high-transaction systems:'
+ print '   zrep snaponly ZFS/fs'
+ print '   zrep synconly ZFS/fs'
+ print 'The above two commands split the simple sync subcommand, into two'
+ print 'separate steps, so that a database, etc. may resume while the sync'
+ print 'completes in the background'
+ print ''
+ print 'zrep defaults to using ssh. However, if remotehost is set to localhost,'
+ print 'zrep will use a simple pipe instead.'
+ print ''
+ print ' More detailed examples can be found at:'
+ print http://www.bolthole.com/solaris/zrep/zrep.documentation.html
+ print ''
+ print 'See the above documentation for details on using the -t flag'
zrep_unlock_fs: unset lock on dcc/data

**Comment by ppbrown** [comment]
oh.
yeah.
well that would explain it :-}

Please try latest git version.

summary: patched in https://github.com/bolthole/zrep/commit/5fa0009fb5c6184763a82abd39d1614fc4213e3c

**Comment by stuartthebruce** [comment]
That looks better.

[root@dcc1 ~]# env DEBUG=1 zrep -t zrep-dcc2 sync dcc/data
DEBUG: zrep_lock_fs: set lock on dcc/data
sending dcc/data@zrep-dcc2_0004d4 to dcc2:dcc/data
Expiring zrep snaps on dcc/data
DEBUG: expiring dcc/data@zrep-dcc2_0004cf
Also running expire on dcc2:dcc/data now...
DEBUG: zrep_lock_fs: set lock on dcc/data
Expiring zrep snaps on dcc/data
DEBUG: expiring dcc/data@zrep-dcc2_0004cf
zrep_unlock_fs: unset lock on dcc/data
zrep_unlock_fs: unset lock on dcc/data
