### ISSUE TITLE
Pre-Compressed ZFS send

### ISSUE THREAD

**Issue by stuartthebruce** [bolthole/zrep#65]
RFE for zrep to detect and use when available the "-c" compressed zfs send/receive option in zfsonlinux version 0.7.0,
https://github.com/zfsonlinux/zfs/releases

**Comment by ppbrown** [comment]
oh. well that actually is useful. 
I've updated the title on this to be more accurate

**Comment by ppbrown** [comment]
I cant find documented usage on this feature. 
open-zfs.org is annoyingly wordy, and surprisingly unhelpful, in this area.

**Comment by stuartthebruce** [comment]
To enable this feature add "-c" to zfs send. Here is the description from the ZoL 0.7.0 release, 

* Compressed zfs send/receive - Use the zfs send -c option to directly send the compressed data in the ARC or on-disk to another pool without needing to decompress it.Here is the man page entry

Here is the man page entry,

       -c, --compressed
           Generate a more compact stream by using compressed WRITE records for blocks which are compressed
           on disk and in memory (see the compression property for details).  If the lz4_compress feature is
           active on the sending system, then the receiving system must have that feature enabled as well.
           If the large_blocks feature is enabled on the sending system but the -L option is not supplied in
           conjunction with -c, then the data will be decompressed before sending so it can be split into
           smaller block sizes.

**Comment by ppbrown** [comment]
hmm.
it doesnt explicitly SAY it sends it as-is from disk. it implies. but doesnt explicitly say.

Also, it seems to imply that the receive will just handle it. 
Do you really need to add -c to the recv as well?

**Comment by stuartthebruce** [comment]
There is no "-c" option for "zfs receive".

**Comment by ppbrown** [comment]
That makes things easier then.
I can in theory just add a -c option to zfs sync

**Comment by stuartthebruce** [comment]
@ppbrown are you willing to consider adding this option?

**Comment by ppbrown** [comment]
Hello again! Thanks for the nudge.
Odd..I thought I remember starting coding for this.. and even finishing it. but maybe that was confused with the "changed only" option.
My current test systems dont seem to support this. So, with a quick implementation hack in mind, let me ask you this:

will it work  on your system, if we just add "-c" to every time "zfs send" is called?

**Comment by stuartthebruce** [comment]
Yes.

**Comment by ppbrown** [comment]
Try latest git, and set ZFS_SEND_FLAGS=-c

**Comment by stuartthebruce** [comment]
Do you mean ZREP_SEND_FLAGS?

**Comment by stuartthebruce** [comment]
<pre>
# env ZREP_SEND_FLAGS=-c ./zrep init -v test1 dcc3 dcc/test1
</pre>

does not show a -c argument for zfs send in the process table on the source machine,

<pre>
# ps -ef | grep zfs
root     179815 179708 88 17:27 pts/0    00:00:36 ssh dcc3  zfs recv -u  -F dcc/test1
root     179816 179814 12 17:27 pts/0    00:00:05 zfs send -v -p test1@zrep_000000
</pre>

**Comment by ppbrown** [comment]
the comments say "this does not get used for init", lol

**Comment by ppbrown** [comment]
oh wait. hmm. i guess thats the most important time to use it. dohhh..
I'll have to rewrite.

**Comment by ppbrown** [comment]
btw I also redid this bit so you can retest this too :)

**Comment by ppbrown** [comment]
My turn to nudge you?
:)

**Comment by ppbrown** [comment]
Hey Stuart.. you still there?
latest version has nice separate ZREP_SEND_FLAGS implementation...
?

**Comment by stuartthebruce** [comment]
Sorry for the slow response. I can confirm that setting `ZREP_SEND_FLAGS=-c` for `zrep init` results in `zfs send -c` being run on an SL7 system using zrep 1.7.6 and zfs 0.8.1. Thanks.

**Comment by ppbrown** [comment]
Awesome. I'm glad your issue was solved.
CLOSING, at last :)
