### ISSUE TITLE
Snapshot naming possible?

### ISSUE THREAD

**Issue by r0k5t4r** [bolthole/zrep#67]
Hi,

I'm currently testing your script and it looks really promising to me. One thing I do miss is the possibility to name snapshots like daily,weekly,monthly etc. Maybe there is already an option for this and I have missed it? Furthermore I would be very interested to know the correct steps to run a pull from a backup server from an already existing dataset. I saw there is already an open issue for that but no real solution yet.

Thanks and Best Regards,
Oliver

**Comment by ppbrown** [comment]
well, you can make your own, separate snapshots of that sort if you like.
no way to have zrep custom named snapshots though.
As for your other question, you dont give enough detail. you should open a
separate thing with more details for that.
rule #1 of being a good user: never put two issues into a single ticket :p

**Comment by r0k5t4r** [comment]
Wow thanks for the very fast answer. And sorry for beeing a bad user. I will open a separate issue for that.

So I could take my own snapshots like:

zfs snapshot fridge/test@1-daily

and just run zrep to sync all existing snaps without it having to create another snap?

**Comment by ppbrown** [comment]
YUP.
So long as you're using the default behaviour.

there is a certain mode I forget at the moment, that deliberately turns
OFF, "and copy all snapshots", due to replication issues in some
circumstances.
