### ISSUE TITLE
Backup Server already existing data

### ISSUE THREAD

**Issue by r0k5t4r** [bolthole/zrep#68]
Hi,

which steps do I have to take if let's say I have a already existing production systems as follows:

fridge/test 

- with many many snapshots

and a backup system that I want to use to pull those snapshots. I don't want to start all over and initialize the dataset from backup server.

**Comment by ppbrown** [comment]
Straight forward method is for you to first enable the client to ssh into
the backup server.

Then initialize with client as master, backup server as slave.

Once init is done, you can then continue with the backup server pulling (as
documented in that section of docs), rather than doing any more pushes from
the client.
(so you can turn off ssh from client to backup server after that)

**Comment by r0k5t4r** [comment]
Sorry, I forgot to mention that the dataset on backup already exists. So running init from the client doesn't work. :(

I have done the following so far but I'm missing something here.

omniosce01 is the production system (client)
omnios01 is the backup system (backup)

on omniosce01 (production system): 

zfs snapshot -r fridge/test@zrep_000000

root@omniosce01:/fridge/test# zfs list -t snapshot
NAME                                      USED  AVAIL  REFER  MOUNTPOINT
fridge/test@daily                            0      -   262M  -
fridge/test@weekly                           0      -   262M  -
fridge/test@monthly                          0      -   262M  -
fridge/test@zrep_000000                      0      -   262M  -
rpool/ROOT/omnios-1@2017-08-25-00:28:25   114M      -   774M  -

on omnios01 (backup server): 
root@omnios01:/volumes# zfs list -t snapshot
NAME                                                       USED  AVAIL  REFER  MOUNTPOINT
omnitank/test@daily                                           0      -   255M  -
omnitank/test@weekly                                          0      -   255M  -
omnitank/test@monthly                                         0      -   255M  -

ssh root@omniosce01 "zfs send -i fridge/test@monthly fridge/test@zrep_000000" | pv | zfs recv -e oomnitank

root@omnios01:/volumes# zfs list -t snapshot
NAME                                                       USED  AVAIL  REFER  MOUNTPOINT
omnitank/test@daily                                           0      -   255M  -
omnitank/test@weekly                                          0      -   255M  -
omnitank/test@monthly                                         0      -   255M  -
omnitank/test@zrep_000000                                     0      -   255M  -

Now I have all snaps on production and backup :)

on omniosce01 (production system):

zrep changeconfig -f fridge/test omnios01 omnitank/test

root@omniosce01:/fridge/test# zrep list -v
fridge/test:
sharenfs        on
sharesmb        name=test
zrep:dest-fs    omnitank/test
zrep:dest-host  omnios01
zrep:savecount  5
zrep:src-host   omniosce01
zrep:src-fs     fridge/test
last snapshot synced:

on omnios01 (backup server): 

zrep changeconfig -f -d omnitank/test omniosce01 fridge/test

root@omnios01:/volumes# zrep list -v
omnitank/test:
sharenfs        on
sharesmb        name=test
zrep:src-fs     fridge/test
zrep:dest-fs    omnitank/test
zrep:savecount  5
zrep:dest-host  omnios01
zrep:src-host   omniosce01
last snapshot synced:

root@omnios01:/volumes# zrep sentsync omnitank/test@zrep_000000
root@omnios01:/volumes# zrep list -v
omnitank/test:
sharenfs        on
sharesmb        name=test
zrep:src-fs     fridge/test
zrep:master     yes
zrep:dest-fs    omnitank/test
zrep:savecount  5
zrep:dest-host  omnios01
zrep:src-host   omniosce01
last snapshot synced: omnitank/test@zrep_000000

But then I get this:

root@omnios01:/volumes# zrep sync omnitank/test
ERROR: we are not master host for omnitank/test
master is omniosce01, we are omnios01
Error: zrep_sync could not create new snapshot for omnitank/test

So something must be wrong with my steps?

**Comment by r0k5t4r** [comment]
Ok got it working after consulting the troubleshooting page. I just had to get rid of master =Yes on the backup:

zfs inherit zrep:master omnitank/test
zfs inherit zrep:lock-pid omnitank/test
zfs inherit zrep:lock-time omnitank/test

These three commands did the trick. :)

**Comment by ppbrown** [comment]
ouch. you did things the roundabout way :-}
but glad you got it working finaly

**Comment by r0k5t4r** [comment]
Are there easier (less) steps to achieve this? :)

**Comment by ppbrown** [comment]
well, you somehow duplicated those properties over.
 if you did it right, you wouldnt have to delete any properties. So think
about the order you did things.
