### ISSUE TITLE
Enable verbose messages?

### ISSUE THREAD

**Issue by darkpixel** [bolthole/zrep#7]
When I run ```/usr/local/bin/zrep -t zrep-local sync tank/officeshare``` from the command line, everything syncs appropriately.

When I put that same command into my crontab, I get the following response through e-mail:
```
Error: Problem doing sync for tank/officeshare@zrep-local_000024. renamed to tank/officeshare@zrep-local_000024_unsent
```

Is there a way to enable verbose messages?  I'm not familiar with ksh, but bash has the option to run ```set -x``` and the executing script will print out every line that it's executing so you can look for the failure.

**Comment by ppbrown** [comment]
same thing. use set -x

bash and ksh are probably 90% identical. I just like the additional
builtins that ksh has.

Although note that , just like bash, it is scoped.
Top level is one scope, but inside functions is another.
So, if you find that there is a particular shell function that needs
verbose output, you need to put the set -x, inside that function.
(and, pretty much everything in zrep is done inside a function.)

So, in your case, you'd want to use set -x, inside

_sync()



On Thu, Sep 10, 2015 at 9:36 AM, Aaron C. de Bruyn <notifications@github.com

**Comment by darkpixel** [comment]
*grumble*
Running from the command line produces the appropriate debug output.
Running from cron still produces the non-debug output.
Running /usr/bin/ksh -x /usr/local/bin/zrep... produces the non-debug output.
Stupid cron...

**Comment by darkpixel** [comment]
Cron apparently won't return the STDERR output even with ```2>&1```, but it will log it to a log file with ```>> /tmp/cron.log 2>&1```.  Weak sauce.  It appears that it can't find the SSH private key for automatically logging in to the box.

I added an environment variable ```SSH=ssh -i /root/.ssh/id_rsa``` and it's finding it now.

Thanks for the help.

**Comment by ppbrown** [comment]
That's rather an ugly solution, in my opinion.
I would suggest that, to make it more compatible with other future potential cron jobs, you instead set environment var
HOME=/root

That should sort it out, I imagine.

**Comment by darkpixel** [comment]
Thanks @ppbrown.
I realize cron jobs have a sanitized environment, but I figured $HOME was still available.  Oops.
