### ISSUE TITLE
sync problem after rebooting target

### ISSUE THREAD

**Issue by stuartthebruce** [bolthole/zrep#71]
zrep 1.7.3 fails to sync to an SL7 target running zfs-0.7.1 after rebooting the target. In particular, it reports,

"cannot receive incremental stream: destination XXX has been modified"

and it is necessary to set ZREP_FORCE="-f" for the first zrep sync instance after a reboot, but not for subsequent instances.

Is this a known issue, or any recommendations on how to track down the problem further?

**Comment by ppbrown** [comment]
sorry, no idea. i suggest you contact your ZFS/linux vendor.
After all, that error comes from zfs, not zrep.
zrep just passes it along.

**Comment by stuartthebruce** [comment]
FYI, this issue occurs with zfs umount; zfs mount on the target machine, and does not require a  reboot. I have just posted a query to the zfs-discuss list,
http://list.zfsonlinux.org/pipermail/zfs-discuss/2017-October/029538.html

**Comment by ppbrown** [comment]
Wow.
Sounds like a bad bug on the zfsonlinux implementation.
Thanks for sharing the knowlege with me here.
I look forward to hearing updates.

**Comment by ppbrown** [comment]
PS: you should probably also specific in the bug report whether
read-only mode was set (as zrep defaults to doing)

If so, it is even twice over a bug.

**Comment by stuartthebruce** [comment]
Excellent point. This is happening with readonly set so the zfs receive issue is just a side effect. I will file a github ticket that focusses on modifications to a readonly dataset.

**Comment by stuartthebruce** [comment]
This is now reported at,
https://github.com/zfsonlinux/zfs/issues/6741
