### ISSUE TITLE
Backup server zpool looks empty

### ISSUE THREAD

**Issue by reelsense** [bolthole/zrep#72]
I had a working sync between a _Linux production server_ and a _FreeBSD 11.1 zrep-backup server_

`oak` sends to -> `root@bit` It was **always successful** and I could list the file contents with `ls`.

I had to clear the snapshots and start fresh on a new _FreeBSD 11.1 zrep-backup server_, lets call it `doom`.

`oak` sends to -> `root@doom` It **appears to succeed** but _I can't list any files_ with `ls`.

I make sure I clear both sides: `zrep clear doom` & `zrep clear oak`

I initialize everything, and after it succeeds (in many hours) I can see the zpool replicated and the size matches, but I can no longer list files on the `doom` zpool.
`zrep -i oak root@doom tank01/oak`

---
Additional notes:

I installed the dependencies needed with `pkg`:  `pkg install ksh93 perl5`. 

I installed zrep via ports: `portsnap fetch ; portsnap extract ; cd /usr/ports/sysutils/zrep ; make install clean`

**Comment by ppbrown** [comment]
Perhaps you dont realize that zrep attempts to UNMOUNT the destination
filesystem by default?
I dont see you mounting it :)

**Comment by reelsense** [comment]
You're right. It's showing up now, out of the blue... The problem is me I guess...
