### ISSUE TITLE
Privileges repeated in documentation

### ISSUE THREAD

**Issue by flungo** [bolthole/zrep#73]
In the [zrep documentation](http://www.bolthole.com/solaris/zrep/zrep.documentation.html) the list of privileges are repeated.

> create,destroy,hold,mount,receive,rename,rollback,send,snapshot,userpropcreate,destroy,hold,mount,receive,rename,rollback,send,snapshot,userprop

should be:

> create,destroy,hold,mount,receive,rename,rollback,send,snapshot,userprop

**Comment by ppbrown** [comment]
Lol.... thanks for noticing that.
