### ISSUE TITLE
Failing to sync one of datasets

### ISSUE THREAD

**Issue by pawel-t** [bolthole/zrep#74]
Hi,

I'm starting refresh from backup server once a day. I sync few datasets. All of them are synchronizing but one. Last but one is handing for 2H and after that I can see in logs "Error: Unforseen error pulling snapshot dataset@snapshot_name from XXX". Is there any particular reason that it could happen? Every dataset but this one is no larger than 50G. This once is almost 500G (but don't have many changes per day so snapshot is not that big).

When I try to re-run it by hand it also hangs. Then when I start it from main server using sync it works. After that I can use refresh on backup server and it also works. But then in the evening ... it hangs again. 

Any idea how to find cause of this problem?

**Comment by ppbrown** [comment]
Hello,

sounds to me like one of two things:

1. some kind of commandline shell timeout/network timeout on your machines
2. Some kind of odd bug in the ZFS that you are using.

side note:
sync it more often

**Comment by pawel-t** [comment]
Hi,

Thank you for your feedback. Today I've spotted that same problem occurred for smaller dataset. Again, sync from backup server hangs, but refresh works properly. 

I will try to update it more often. In mean time I will try to find cause of this hanging, maybe there is indeed strange bug in zfs. 

If it doesn't help I guess I need to do refresh from server rather than sync from backup server, but it's not good practice.

**Comment by ppbrown** [comment]
Old ticket. I dont think this is an issue in zrep, and havent heard from user in over a year. so..
closing.
