### ISSUE TITLE
/var/run/zrep.lock printed to stderr from time to time

### ISSUE THREAD

**Issue by jeff-dagenais** [bolthole/zrep#75]
Using master (1.7.3).

I have zrep setup in a cron job as so:
`zrep sync -q 900 rpool/vz/kvm/vm-103-disk-1 >/dev/null`

It was setup to run every minute. The point was to get quasi-HA replicate of the VM. Every so often (typically 2-3 times/day), the cron job sends me an email with only this text: "/var/run/zrep.lock".

So it looks like something slips by the pipe redirection in the script and it reaches stderr, and thus my inbox. I've briefly looked at the places `Z_GLOBAL_LOCKFILE` is used but couldn't figure out which usage could cause that.

I have since dropped it to every 5 min to reduce the probability of this occurring.

**Comment by ppbrown** [comment]
I have noticed that linux handling of stderr output is.. shall we say.. inconsistent. sometimes unreliable.
you are most likely getting TRUNCATED output of a message group in zrep_get_global_lock(), 
saying that it cannot get the lock at that time.
(most likely due to overlap)

If you dont want to see any error message, i suggest you add "2>&1" to the end of the cronjob.
If you DO want to see them, then I suggest you redirect output to a logfile and check it occasionally :)

**Comment by jeff-dagenais** [comment]
How is one supposed to see if something is truely going wrong with `2>&1 >/dev/null` ? Remember that since zrep doesn't have a true quiet mode, one must redirect stdout to >/dev/null.

About the unreliable output... are you saying I should see these 3 lines:
```
                        _errprint ERROR: stale global lock file
                        _errprint ERROR: shut down ALL zrep instances, then manually remove
                        _errprint $Z_GLOBAL_LOCKFILE
```
instead of just the last one?

I've worked for over 15 years on linux with various scripts and cronjob, never have I seen "inconsistent" or "unreliable" stderr output... unless it was my fault. Perhaps it's something to do with ksh?

Normally, my error print functions look like this
```
_errprint(){
        echo "$@" >&2       
}
```
would this not work?

**Comment by ppbrown** [comment]
As I said, you would want to redirect to a logfile, rather than /dev/null,
in that case.

the stderr issue got mentioned in another bug report. I dont know whether
it is specifically "ksh on linux", or linux in general, but I seem to
recall it was more of a linux problem, in certain uses.
The issue comes with printing multiple lines in a row to stderr. Linux
doesnt cleanly buffer them, like a proper UNIX should. It just throws away
earlier lines sometimes.
You probably have only used one-liners.

Feel free to tweak the error printing functions in your zrep copy as you
see fit. Just remember your changes will get blown away by a newer zrep
version :-}

**Comment by jeff-dagenais** [comment]
Hi again,

Thanks btw for taking the time... and for the great tool ;)

I'm just wondering why `> /dev/fd/2` was used instead of the POSIX compliant ` >&2`, and if it may have played a role in the mis-buffering you are referring to?

Or perhaps even the ksh-centric `print -u2 "$@"` would perform more reliably?

I know `echo "$@" >&2` works flawlessly on my debian system. That is, I am getting all the error messages. I will give the `print -u2` a whirl and report back.

**Comment by jeff-dagenais** [comment]
Actually, Now that I have the printing "fixed", there are two things that are weird in the trace I get:
```
ln: failed to create symbolic link ‘/var/run/zrep.lock/8705’: No such file or directory
ln: failed to create symbolic link ‘/var/run/zrep.lock/8705’: No such file or directory
/usr/local/sbin/zrep[295]: -d: not found [No such file or directory]
ERROR: stale global lock file
ERROR: shut down ALL zrep instances, then manually remove
/var/run/zrep.lock
ln: failed to create symbolic link ‘/var/run/zrep.lock/8705’: No such file or directory
/usr/local/sbin/zrep[295]: -d: not found [No such file or directory]
ERROR: stale global lock file
ERROR: shut down ALL zrep instances, then manually remove
/var/run/zrep.lock
ln: failed to create symbolic link ‘/var/run/zrep.lock/8705’: No such file or directory
/usr/local/sbin/zrep[295]: -d: not found [No such file or directory]
ERROR: stale global lock file
ERROR: shut down ALL zrep instances, then manually remove
/var/run/zrep.lock
ln: failed to create symbolic link ‘/var/run/zrep.lock/8705’: No such file or directory
/usr/local/sbin/zrep[295]: -d: not found [No such file or directory]
ERROR: stale global lock file
ERROR: shut down ALL zrep instances, then manually remove
/var/run/zrep.lock
ln: failed to create symbolic link ‘/var/run/zrep.lock/8705’: No such file or directory
/usr/local/sbin/zrep[295]: -d: not found [No such file or directory]
ERROR: stale global lock file
ERROR: shut down ALL zrep instances, then manually remove
/var/run/zrep.lock
ln: failed to create symbolic link ‘/var/run/zrep.lock/8705’: No such file or directory
/usr/local/sbin/zrep[295]: -d: not found [No such file or directory]
ERROR: stale global lock file
ERROR: shut down ALL zrep instances, then manually remove
/var/run/zrep.lock
ln: failed to create symbolic link ‘/var/run/zrep.lock/8705’: No such file or directory
/usr/local/sbin/zrep[295]: -d: not found [No such file or directory]
ERROR: stale global lock file
ERROR: shut down ALL zrep instances, then manually remove
/var/run/zrep.lock
ln: failed to create symbolic link ‘/var/run/zrep.lock/8705’: No such file or directory
/usr/local/sbin/zrep[295]: -d: not found [No such file or directory]
ERROR: stale global lock file
ERROR: shut down ALL zrep instances, then manually remove
/var/run/zrep.lock
ln: failed to create symbolic link ‘/var/run/zrep.lock/8705’: No such file or directory
/usr/local/sbin/zrep[295]: -d: not found [No such file or directory]
ERROR: stale global lock file
ERROR: shut down ALL zrep instances, then manually remove
/var/run/zrep.lock
ln: failed to create symbolic link ‘/var/run/zrep.lock/8705’: No such file or directory
/usr/local/sbin/zrep[295]: -d: not found [No such file or directory]
ERROR: stale global lock file
ERROR: shut down ALL zrep instances, then manually remove
/var/run/zrep.lock
```

First, because it's an easy one, https://github.com/bolthole/zrep/blob/542f3115529884597cf00acfa467058c73557548/zrep#L295

There are missing `[ ! -d ... ]` here, hence the "-d no such file".

Second, why is it trying to use `/var/run/zrep.lock` as a directory when doing `ln: failed to create symbolic link ‘/var/run/zrep.lock/8705’: No such file or directory` ?? How can it generate this path?

**Comment by ppbrown** [comment]
Interesting.

I used /dev/fd/2, becuase it is SUPPOSED to be a ksh builtin, so I thjought
it would be the most compatible cross platform, in theory.

But I think newer versions of ksh messed up multiple things.
I wasnt really aware of >&2  . so I might migrate to using that. Thanks for
the suggestion.

**Comment by ppbrown** [comment]
Ooo!
Thanks for finding those missing [] test brackets. WOw, thats an OOOLD bug,
introduced around 1.6.8. Ouch.
Fixing that first, then will look at the other thing you mentioned

**Comment by ppbrown** [comment]
As far as that "/var/run/zrep.lock/8705" thing...
sounds like Z_GLOBAL_LOCKFILE has gotten corrupted.

It looks like it only gets assigned in one place in my script. and
it's pretty vanilla. So Dont see how that could go wrong.
Did you perhaps tweak it?

**Comment by jeff-dagenais** [comment]
I did not tweak it no... only the `_errprint()`. Mmmh odd. I'm trying and trying to see how it's even possible for this variable to get what looks like a pid appended to it's value... and with a proper `/` separator mind you!

With the [[]] fix I had on top of 1.7.3 I was getting this instead of the large dump:
```
ln: failed to create symbolic link ‘/var/run/zrep.lock/27164’: No such file or directory
ln: failed to create symbolic link ‘/var/run/zrep.lock/27164’: No such file or directory
ln: failed to create symbolic link ‘/var/run/zrep.lock/27164’: No such file or directory
```

(SO weird) I will keep an eye out for this, I have the scenario to reproduce it. I updated to your latest master (with the two nice fixes. ;)

**Comment by ppbrown** [comment]
well, shove this in the top of
zrep_get_global_lock()


_errprint global lockfile is starting as  $Z_GLOBAL_LOCKFILE
 set -x

**Comment by jeff-dagenais** [comment]
I have hacked zrep so that when started, it immediately global_locks, then spins around for 30 seconds, then releases. In the mean time, I added the print, started a second zrep and here's what I got:
```
root@prox1:~# zrep
global lockfile is starting as /var/run/zrep.lock
+ [[ -d /proc/8729 ]]
+ ln -s /proc/8729 /var/run/zrep.lock
ln: failed to create symbolic link ‘/var/run/zrep.lock/8729’: No such file or directory
+ (( retry_count > 0 ))
+ sleep 1
+ ln -s /proc/8729 /var/run/zrep.lock
ln: failed to create symbolic link ‘/var/run/zrep.lock/8729’: No such file or directory
+ retry_count=2
+ zrep_global_lock_pid
+ awk -F/ '{print $NF}'
+ ls -l /var/run/zrep.lock
+ 2> /dev/null
+ lockpid=8652
+ [[ ! -d /proc/8652 ]]
+ (( retry_count > 0 ))
+ sleep 1
+ ln -s /proc/8729 /var/run/zrep.lock
ln: failed to create symbolic link ‘/var/run/zrep.lock/8729’: No such file or directory
```

I'm freaked out a bit. I will dig into ksh and the ln command maybe?

**Comment by ppbrown** [comment]
Errr...
whut.

I'm glad I had you do the set -x.
cause otherwise, I wouldnt believe that output :-/
That makes absolutely NO sense. The program is acting perfectly normal, but your system is nuts.

Have you done something crazy like put in a ROOT level alias for the ln command?

what happens if you do on command line

ln -s /proc/8729 /var/run/zrep.lock

?

Also, try putting at the top of the zrep script:

(after the #!/bin/ksh of course)

PATH=/bin:/usr/bin:$PATH

**Comment by jeff-dagenais** [comment]
fixed! see #77

**Comment by jeff-dagenais** [comment]
My system is not nuts.

You can do this test in any shell:
```
$mkdir somedir
$ln -s $(pwd)/somedir my_symlink
$ ln -s $(pwd)/any_target my_symlink
$ ls my_symlink/
any_target
$ ls somedir/
any_target
$ 
```
So when the target link is a directory, and it exists, ln will interpret that as you have not specified the symlink name, hence it takes the last part of the link target (here it's "any_target") as the symlink name and it nests this link inside the linked directory (here it's somedir, the link target of "my_symlink").

:)

**Comment by ppbrown** [comment]
patched in https://github.com/bolthole/zrep/commit/d2acc8cc6f5f7c82d6ec9626873b9bc4e6b6d676
