### ISSUE TITLE
Mountpoint not cleared for subdirectories when using ZREP_R=-R

### ISSUE THREAD

**Issue by holgerfriedrich** [bolthole/zrep#76]
When using `ZREP_R=-R zrep init` on my `/home/`directory, the subdirectories on the remote machine keep the mountpoint and thus stay mounted on the remote machine.

My pool layout is as follows:
`srcpool/home              none`
`srcpool/home/user    /home/user`

`dstpool/backup/home   none`
`dstpool/backup/user    /home/user`

The following workaround was fine for me, but I removed the if statement which might have some implications.
I did not create a PR, here is a patch file:

```
--- zrep.orig   2017-11-21 10:14:37.400450561 +0100
+++ zrep        2017-11-21 10:14:02.766471524 +0100
@@ -1125,10 +1125,8 @@
                zfs set ${ZREPTAG}:lastsent=${snap} $srcfs
                zrep_ssh $desthost zfs set ${ZREPTAG}:lastsent=${snap} $destfs
        fi
-       if [[ "$mountpoint" != "" ]] ; then
-               print "clearing mountpoint value for remote"
-               zrep_ssh $desthost zfs inherit mountpoint $destfs
-       fi
+       print "clearing mountpoint value for remote"
+       zrep_ssh $desthost zfs inherit ${Z_SNAP_R} mountpoint $destfs
 
        # make sure the above ' set 's (sent, lastsent)
        # match what zrep_sync() does !!!
```

**Comment by ppbrown** [comment]
closing due to no reply from user, for 6 months.
