### ISSUE TITLE
zrep refresh works manual but not in cron

### ISSUE THREAD

**Issue by chrwei** [bolthole/zrep#78]
just upgraded to version 1.7.3 on both sides from 1.6.x (I didn't record the old number, 1.6 is from memory), this worked before

cron sends me an email  with just ```Error: snap of src on failed ```, even with 2>&1

what should I try next?

**Comment by ppbrown** [comment]
interesting.
First thing I would suggest, is upgrading to github latest, rather than official 1.7.3 release.
Then we need to figure out why it's missing the name of the filesystem it is attempting to snapshot.

**Comment by chrwei** [comment]
well, that did a thing.  not sure why it didn't before
it seem my cron's $PATH does not include /sbin and thus it cannot find the zfs command

changed my cron to ```PATH=$PATH:/sbin:/usr/sbin /usr/bin/zrep refresh tank/backup``` and it refreshed properly
