### ISSUE TITLE
zrep status options issue

### ISSUE THREAD

**Issue by almoondsllc** [bolthole/zrep#80]
Hello,
I noticed a different result running "zrep status -a -v" and "zrep status -v -a".
debian9 is a central zfs system

root@debian9:~# zrep status -a
dataz/backup/cri/public                        last synced 2017/12/26-09:36:15
dataz/backup/dinelli/alterego                  last synced [NEVER]
dataz/backup/dinelli/backup                    last synced [NEVER]
dataz/backup/dinelli/public                    last synced [NEVER]
dataz/backup/mercatini/kvm                     last synced [NEVER]
dataz/backup/morganti/kvm                      last synced [NEVER]

root@debian9:~# zrep status -a -v
dataz/backup/cri/public                        last synced 2017/12/26-09:36:15
dataz/backup/dinelli/alterego                  last synced [NEVER]
dataz/backup/dinelli/backup                    last synced [NEVER]
dataz/backup/dinelli/public                    last synced [NEVER]
dataz/backup/mercatini/kvm                     last synced [NEVER]
dataz/backup/morganti/kvm                      last synced [NEVER]

root@debian9:~# zrep status -v -a
cannot open 'dataz/public': dataset does not exist
dataz/public             ->:dataz/backup/cri/public            2017/12/26-09:36
**cannot open 'dataz/alterego': dataset does not exist**
dataz/alterego           ->:dataz/backup/dinelli/alterego      2017/12/26-09:36
dataz/backup             ->-:dataz/backup/dinelli/backup       2017/12/26-09:36
**cannot open 'dataz/public': dataset does not exist**
dataz/public             ->:dataz/backup/dinelli/public        2017/12/26-09:36
dataz/kvm                ->-:dataz/backup/mercatini/kvm        2017/12/26-09:36
dataz/kvm                ->-:dataz/backup/morganti/kvm         2017/12/26-09:36

I can't understand from where that "cannot open xxxxxx dataset does not exist".
Thank you

**Comment by ppbrown** [comment]
Huh.
thats interesting.

To start with,  technically, "zrep -a -v"
 is user error :)
Usage message says:

 'zrep (status|-s) [-v] [(-a|ZFS/fs)]'

Order matters.
Anything after -a, gets ignored.

So, this is saying that the actual status -v got broken somehow.
Hmm.

Im guessing that

_master_fs_names(){
	zfs get -H -o name -s local ${ZREPTAG}:master "$@"
}

is giving unexpected output.
So...
zfs get -H -o name -s local zrep:master
must be listing dataz/alterego
as supposedly having the property zrep:master
even though it is not an actual zrep filesystem?

**Comment by almoondsllc** [comment]
zfs get -H -o name -s local zrep:master
gives as output nothing...

**Comment by mlavkin** [comment]
This problem appears when remote and local filesystem have different names and local is not master.
In current release 1.7.4 line 566
desthost=`$ZFSGETVAL ${ZREPTAG}:dest-host $fs`
fixes issue.
We need to get dest-host parameter from local filesystem path not remote.

**Comment by ppbrown** [comment]
erm....
it SOUNDS like you are saying,
"when local host is not master, zrep:master is not set".

yes.  Exactly. That is the design :) it's a flag.
If you want to find out the NAME of the master, then get the src-host
properly.

**Comment by ppbrown** [comment]
closing this as basically informational, and apparently fixed in later releases. 
But to close the loop, in case it is unclear:
"src-host" and "dest-host" normally have the same values on both sides.
So it doesnt matter if you get it from local (ie: master) side, or remote side.
