### ISSUE TITLE
Syncing subdataset of synced dataset?

### ISSUE THREAD

**Issue by kvoit** [bolthole/zrep#81]
I am trying to to sync a subdataset
pool/dataset/subdataset
of an already synced dataset
pool/dataset

The initialization failed because it seems the subdataset inherits the zrep:dest-fs property from pool/dataset
so zrep recognized it as partially configured.

If, however, I first initialize pool/dataset/subdataset and then pool/dataset, everything seems to work fine, so the only technical issue seems to be the inherited property. 

I am not a zfs expert, but it seems inheritance is inevitable for such a property. Maybe zrep should omit the -o switch to see if the returned value is inherited or local? 
May more checks because of ZREP_R would be required?
(Talking about ZREP_R, why is that not a property to be read by zrep sync?)

**Comment by ppbrown** [comment]
Hello,

i'm afraid there are documented problem with nesting (due to issues with
zfs properties).
 bottom line is, dont do it.
If you need to replicate nested filesystems, you need to use the -R option
with a single invocation of zrep.

**Comment by kvoit** [comment]
Ok, thanks. Could you point me to the documentation?

**Comment by ppbrown** [comment]
you are correct, it is all or nothing.

google "zrep documentation" will take you directly to it.

**Comment by kvoit** [comment]
Yes thanks -_- I know that documentation. But neither does it clearly tell me not sync nested datasets (I guess this is meant by the "don't mix and match" sentence?) nor does it document what the actual problem is. It looked like it could be solved by ignoring inherited properties, I hoped to find an answer on why it apparently cannot.
