### ISSUE TITLE
Error: zrep_expire Internal Err caller did not hold fs lock

### ISSUE THREAD

**Issue by sysadmama** [bolthole/zrep#82]
Hi,

we have some `zrep` related questions - and I hope to get some answers or ideas here :) 

We have a `zrep` V1.7.3 running on two SunOS 5.11 machines (OpenIndiana Hipster
release 2017.10) and the following setup

* we are replicating 8 datasets (flat structure, no nested replication)
* we are using `zrep` for replication only, no failover configured
* `zrep` initialization was done on our primary node a for all datasets
* node B is our backup node, so ZFS snapshots are replicated from node A to B
in pull mode (node b initiates `zrep`)

The replication processes are working fine, but we are encountering these
errors on all datasets for a while now:
```
DEBUG: Running remote expires on Data01/services
Expiring zrep snaps on Data01/services
Error: zrep_expire Internal Err caller did not hold fs lock on Data01/services
zrep_unlock_fs: unset lock on Data01/services
```
```
DEBUG: Running local expires on Data01/archives
DEBUG: expiring Data01/archives@zrep_00005d
DEBUG: Running remote expires on Data01/archives
Expiring zrep snaps on Data01/archives
Error: zrep_expire Internal Err caller did not hold fs lock on Data01/archives
zrep_unlock_fs: unset lock on Data01/archives
```

When we have a look at the `zrep` related snapshots on both sides:
* for `Data01/services`: has 5 `zrep` snapshots on node B (as it should have) but
it has 16 `zrep` snapshots on node A
* for `Data01/archives`: has 5 `zrep` snapshots on node B (as it should have) but
it has 8 `zrep` snapshots on node A

How can we get rid on this?

And, just to mention it, this is how we came to a detailed look at this
problem: we are encountering problems with our weekly `scrub` process on node A.
This `scrub` normally needs about 12h to run, but the last scrub process is
running for 9 days now and is at 54% actually :-/ So we are now checking
everything on our primary node A, as the `scrub` performance is going worse and
worse everyday, while the system itself seems to be ok in all matters.

Thanks in advance and thanks for any ideas,
  Marianne

**Comment by ppbrown** [comment]
My apologies: i just noticed that I have never replied to this issue :(
(dont even remember seeing it!)
I recall tweaking the locking mechanisms in the last few revisions, so I suggest you try out the latest version.

**Comment by sysadmama** [comment]
We changed our workflow, using push mode now instead of pull. I can't say whether this problem persists or not, but I'll close this issue now. Thank you very much.
