### ISSUE TITLE
Add "all" keyword to "snaponly" and "synconly" commands

### ISSUE THREAD

**Issue by vinca** [bolthole/zrep#83]
Would it be possible to use `all` for `snaponly` and `synconly` commands?
   
There's currently no way to use `synconly` for serial sync of all filesystems like when using `sync all`. Chaining commands per FS with `&&` runs them in parrallel, what makes them vulnerable to connection failure etc.

**Comment by ppbrown** [comment]
Well, if you're worried about connection failure, im not sure this is realy
an improvement.

two things:

first off, you dont need to do long ugly chain of &&.
you can set your shellscript to exit on error. In ksh/sh I think it is set
-e

Secondly, that being said:  sure, I'll officially add this to my list of
future enhancements to zrep :)
Seems like an appropriate ease-of-use enhancement

**Comment by ppbrown** [comment]
Added in commit cc43bac
