### ISSUE TITLE
Load defaults from a file

### ISSUE THREAD

**Issue by qcfabrizio** [bolthole/zrep#84]
If the following snippet were added to the top of `zrep_var`, it would allow for defaults to be set for the script's variables without having to modify the script directly. I would much rather keep the script identical to the upstream one and make my modification in an externally sourced file as this will make upgrading in the future simpler.

```
# Load defaults if they are available
if [ -f /etc/default/zrep ]; then
  . /etc/default/zrep
fi
```

**Comment by ppbrown** [comment]
Actually, I designed zrep so that you could set defaults in your
environment.
So this seems a little redundant?
You can use setenv or things like that, in root's profile?

**Comment by qcfabrizio** [comment]
Yes, this is not strictly required - it just felt to me like a more reliable way of ensuring that the correct defaults were set for a system regardless of user or invocation method. If you think it's redundant then no need to implement.

**Comment by ppbrown** [comment]
I dislike adding a system call to every invocation of zrep, when for 99% of cases, it will never even be used.
I MIGHT consider adding an additional flag to force reading in configs if you like. eg:

zrep -C /etc/default/zrep ....
Not sure whether to use -c, -C, or -f there.

**Comment by ppbrown** [comment]
Thoughts on that alternative?
I realize that depending on your reasons, it could either be fine, or inadequate.

Design choices are annoying at times. Sometimes, there are mutually conflicting goals.
This is one pair:  immutable configuration, vs "everything can be overridden on command line".
For my programs, I choose "everything can be overridden".
I suspect you wish the opposite, but I'm afraid you will have to hand-customize for that.

**Comment by qcfabrizio** [comment]
Sorry for the delay. Yes, for me it would be preferable to not have to provide any command line args, but I may be able to work with this providing it works to set this flag in `ZREP_PATH` for the remote zrep to pick up the desired environment variables - which is where it was easier to do by having the script source the defaults.

**Comment by ppbrown** [comment]
hmm. hadnt thought about that aspect.
I think perhaps you might be best off creating I think a "fork" in github, with that one patch. then you can always pull from your fork and it will be up to date, but have your desired tweak consistently?

**Comment by ppbrown** [comment]
I'm reconsidering adding this functionality.

**Comment by ppbrown** [comment]
The reason being, there are now a LOT of potential variables.
A bunch that make sense as site defaults, rather than "temporary" overrides.

Need to ponder this carefully though.  I dont want to have to remove something, after adding it in.

**Comment by ppbrown** [comment]
If I do, add comment about using same "if set" syntax in /etc/default that is used in zrep_vars.
Otherwise, it will blow away user environment.

**Comment by darkpixel** [comment]
@qcfabrizio not sure if it helps in your situation, but I created a file ```/usr/local/etc/zrep.env``` that contains things like:
```
export ZREP_R=-R
export ZREP_INC_FLAG=-i
export ZREP_OUTFILTER="pv -eIrabL 800K"
```

I launch a backup like this:
```
source /usr/local/etc/zrep.env
zrep sync all
```
