### ISSUE TITLE
BBCP support for `zrep refresh` broken

### ISSUE THREAD

**Issue by lukegb** [bolthole/zrep#87]
zrep refresh doesn't pass the `-N io` flag to BBCP in `zrep_refresh`, so BBCP immediately fails.

I notice you mentioned you don't merge patches to avoid copyright issues, so I've opened an issue instead.

**Comment by ppbrown** [comment]
Thank you for reporting this, and for picking up the specific cause of the problem!
Commited fix in 137becee7a03673a2819d1800026edf09abd2aba
