### ISSUE TITLE
zrep sync failing with error on remote host

### ISSUE THREAD

**Issue by sergeCapwell** [bolthole/zrep#88]
we have a only homepool / home1 file system that fails while it was working yesterday

host1 # zrep status -v -a
homepool / home1 last synced [NEVER]
homepool / home2 last synced Thu Mar 15 11:10 2018
homepool / home3 last synced Thu Mar 15 11:10 2018

we had to run a snapshot clean and do a initialization

host1 # zrep -i homepool/home1 host2 homepool/home1
Setting properties on homepool/home1
Creating snapshot homepool/home1@zrep_000000
Sending initial replication stream to host2:homepool/home1

but after several hours the homepool / home1 file system on the remote machine is deleted when it existed

host2 # zfs list -r -t all homepool / home1
can not open 'homepool / home1': filesystem does not exist

host2 # zfs list
NAME USED AVAIL REFER MOUNTPOINT
homepool / home2 27.1G 161G 21.2G / export / home2
homepool / home3 128M 161G 122M / export / home3

Can you help me?

**Comment by ppbrown** [comment]
using cutnpaste for error reporting is very important.
in this case, your report seems garbled, because it indicates SPACES in
places where there should not be any spaces.

please redo your bug report, ensuring that your cutnpaste output is 100%
accurate.

**Comment by sergeCapwell** [comment]
ok this is the bug report
we have a only homepool / home1 file system that fails while it was working yesterday

zrep status -a -v
homepool/home1                                 last synced [NEVER]
homepool/home2                                 last synced Thu Mar 15 11:10 2018
homepool/home3                                 last synced Thu Mar 15 11:10 2018

we had to run a snapshot clean and do a initialization
zfsreplicator@bbgciprod:~$ zrep -i homepool/home1 bbgcibkp-rep homepool/home1
Setting properties on homepool/home1
Creating snapshot homepool/home1@zrep_000000

but after several hours the homepool / home1 file system on the remote machine is deleted when it existed

oot@bbgcibkp:/export# while true; do zfs list -r -t all homepool/home1; sleep 60
; done
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.27G   159G  1.27G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.28G   159G  1.28G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.29G   159G  1.29G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.30G   159G  1.30G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.31G   159G  1.31G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.32G   159G  1.32G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.32G   159G  1.32G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.33G   159G  1.33G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.34G   159G  1.34G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.35G   159G  1.35G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.36G   159G  1.36G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.37G   159G  1.37G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.38G   159G  1.38G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.39G   159G  1.39G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.40G   159G  1.40G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.40G   159G  1.40G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.41G   159G  1.41G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.42G   159G  1.42G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.44G   159G  1.44G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.45G   159G  1.45G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.46G   159G  1.46G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.47G   159G  1.47G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.48G   159G  1.48G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.50G   159G  1.50G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.51G   159G  1.51G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.52G   159G  1.52G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.53G   159G  1.53G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.55G   159G  1.55G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.56G   159G  1.56G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.59G   159G  1.59G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.61G   159G  1.61G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.63G   159G  1.63G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.66G   159G  1.66G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.68G   159G  1.68G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.72G   159G  1.72G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.74G   159G  1.74G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.78G   159G  1.78G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.81G   159G  1.81G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.83G   159G  1.83G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.87G   159G  1.87G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.92G   159G  1.92G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.96G   159G  1.96G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  1.99G   159G  1.99G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.03G   159G  2.03G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.08G   159G  2.08G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.12G   159G  2.12G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.15G   158G  2.15G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.19G   158G  2.19G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.23G   158G  2.23G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.27G   158G  2.27G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.31G   158G  2.31G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.34G   158G  2.34G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.37G   158G  2.37G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.39G   158G  2.39G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.41G   158G  2.41G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.44G   158G  2.44G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.46G   158G  2.46G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.49G   158G  2.49G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.51G   158G  2.51G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.53G   158G  2.53G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.56G   158G  2.56G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.58G   158G  2.58G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.61G   158G  2.61G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.63G   158G  2.63G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.65G   158G  2.65G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.67G   158G  2.67G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.69G   158G  2.69G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.71G   158G  2.71G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.73G   158G  2.73G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.75G   158G  2.75G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.77G   158G  2.77G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.79G   158G  2.79G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.81G   158G  2.81G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.84G   158G  2.84G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.86G   158G  2.86G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.89G   158G  2.89G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.91G   158G  2.91G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.94G   158G  2.94G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.96G   158G  2.96G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.97G   158G  2.97G  none
  NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  2.99G   158G  2.99G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.00G   158G  3.00G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.02G   158G  3.02G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.03G   158G  3.03G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.05G   158G  3.05G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.06G   158G  3.06G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.08G   158G  3.08G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.10G   158G  3.10G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.12G   158G  3.12G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.14G   158G  3.14G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.17G   157G  3.17G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.21G   157G  3.21G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.28G   157G  3.28G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.34G   157G  3.34G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.41G   157G  3.41G  none
NAME             USED  AVAIL  REFER  MOUNTPOINT
homepool/home1  3.45G   157G  3.45G  none
cannot open 'homepool/home1': filesystem does not exist
cannot open 'homepool/home1': filesystem does not exist



^C
root@bbgcibkp:/export# 
root@bbgcibkp:/export# 
root@bbgcibkp:/export# 


root@bbgcibkp:/export# zfs list -r -t all homepool/home1
cannot open 'homepool/home1': filesystem does not exist
root@bbgcibkp:/export# 

root@bbgcibkp:/export# zfs list
NAME                              USED  AVAIL  REFER  MOUNTPOINT
homepool                          133G   161G    31K  none
homepool/home0                   90.1G   161G  90.1G  /export/home0
homepool/home2                   27.1G   161G  21.2G  /export/home2
homepool/home3                    128M   161G   122M  /export/home3
homepool/home4                     31K   161G    31K  /export/home4
homepool/home5                     31K   161G    31K  /export/home5
homepool/home6                     31K   161G    31K  /export/home6
homepool/home7                     31K   161G    31K  /export/home7
homepool/home8                   15.1G   161G  15.1G  /export/home8
homepool/home9                     31K   161G    31K  /export/home9
rpool                            77.7G  68.9G  73.5K  /rpool
rpool/ROOT                       37.8G  68.9G    31K  legacy
rpool/ROOT/sol11.1-sru20         37.8G  68.9G  31.3G  /
rpool/ROOT/sol11.1-sru20/var     4.86G  68.9G  4.00G  /var
rpool/ROOT/solaris               7.53M  68.9G  4.15G  /
rpool/ROOT/solaris-backup-1       118K  68.9G  2.53G  /
rpool/ROOT/solaris-backup-1/var    58K  68.9G   693M  /var
rpool/ROOT/solaris/var           4.67M  68.9G   255M  /var
rpool/VARSHARE                   19.4M  68.9G  19.4M  /var/share
rpool/dump                       33.0G  69.9G  32.0G  -
rpool/export                     2.82G  68.9G    44K  /export
rpool/export/home                2.82G  68.9G    33K  /export/home
rpool/export/home/admin          2.82G  68.9G  2.82G  /export/home/admin
rpool/export/home/zfsreplicator  47.5K  68.9G  47.5K  /export/home/zfsreplicator
rpool/swap                       4.13G  69.1G  4.00G  -

Can you help me?

**Comment by ppbrown** [comment]
hm.

well, zrep doesnt go around deleting filesystems.
(unless someone is doinb a recursive replication of a top level ZFS, and
deletes a sub-level filesystem perhaps)

So, doesnt sound like this has anything to do with zrep. You most likely
have something else running on your  bbgcibkp system.

**Comment by sergeCapwell** [comment]
ok but the homepool/home1 sync failing and display [NEVER] while it was working sync several days

zrep status -a -v
homepool/home1 last synced [NEVER]
homepool/home2 last synced Thu Mar 15 11:10 2018
homepool/home3 last synced Thu Mar 15 11:10 2018

how can we solve this to resync normally?

after initialization fails, there is only one snapshot but it is not sent to the remote host

root@bbgciprod:~# zfs list -r -t all homepool/home1
NAME                         USED  AVAIL  REFER  MOUNTPOINT
homepool/home1              4.99G   119G  4.98G  /export/home1
homepool/home1@zrep_000000  6.48M      -  4.98G  -

**Comment by ppbrown** [comment]
what evidence do you have that home1 was ever successfully synced? I may
have missed that.

just because there is ONE snapshot, doesnt mean sync was ever successful.
acutally, that could describe why fs went away on other side.

if the filesystem is crazy big, sync could take days... and then if job
fails.. sync is incomplete, and remote ZFS will roll back the initial sync.
Which, if it is done directly by snapshot..will have the effect of removing
the filesystem, perhaps.

**Comment by sergeCapwell** [comment]
ok 
I configured the home1, home2 and home3 in the same way
home2 and home3 sync without problem
only home1 does not sync
in addition  no logs messages
it's crazy

**Comment by ppbrown** [comment]
"does not sync" is not informative.
how large is the filesystem, and how fast is your connection?

**Comment by sergeCapwell** [comment]
sorry for my late answer
I was sick

the size of  filesystem is :
NAME                             AVAIL   USED  USEDSNAP  USEDDS  USEDREFRESERV  USEDCHILD
homepool/home2           83.9G  31.6G     13.2M   31.6G              0          0

our connection is 8mb/s

**Comment by ppbrown** [comment]
Hmm.

Well, seems like you have both an unreliable connection, and a slow
combination. Unfortunate.

I am working on a "restart sync" option to zrep, but thats going to take
some time. So meanwhile, you would probably be best off doing a manual
initialization. BUT, instead of copying the data with scp or ssh.. maybe
you could copy to a USB drive, then mail it over to the other site.

**Comment by ppbrown** [comment]
On Wed, Oct 24, 2018 at 1:25 AM sergeCapwell <notifications@github.com>
wrote:

> if I understand correctly I manually copy the contents of the file system
> to the other site
> Then what should I do?
>


Actually, you need to make a snapshot, and save the output of a "zfs send"
of the filesystem.
copy it to USB drive. send it over.
Then do a "zfs receive" of the data on the other side.

Once you have done that, then you can follow the zrep documentation section
under
"Pre-existing filesystem"

**Comment by sergeCapwell** [comment]
Hi,
now it's ok
we had converted a snapshot using zrep and it works
thanks you

**Comment by ppbrown** [comment]
Glad to hear it :)
