### ISSUE TITLE
Timestamp instead of sequence number in snapshot name

### ISSUE THREAD

**Issue by tinuzz** [bolthole/zrep#90]
Hi,

Is there any special reason that Zrep uses an incremental sequence in snapshot names, rather than a timestamp? The latter seems more obvious, because it is inherently more informative, but there is also a more practical reason to do this.

I was looking at Samba's [vfs_shadow_copy2](https://www.samba.org/samba/docs/current/man-html/vfs_shadow_copy2.8.html) module, that allows filesystem snapshots of any kind to be presented to Windows clients as _shadow copies_, enabling users to browse previous versions of files and directories right from their desktop. One of the requirements for this to work, is that the snapshots have a timestamp in their name, that can be matched with a configurable strptime() format.

I found about 6 or 7 places in Zrep that need changes to make this work, so it's doable, but I was wondering if there are compelling reasons not to change the format that I may have overlooked, should I decide to go that way,.

Cheers,
Martijn.

**Comment by ppbrown** [comment]
How is it more informative?

usually, people want "the latest".
a sequence makes it instantly clear which is the latest. Unless you pick a
date format that looks like a timestamp anyway, ie: YYYYMMDDHHMMDD


and if some reason you really need to know when it was created...
that's what "zfs get creation" is for.

plus, the current scheme works across timezones.
your idea, does not.

**Comment by tinuzz** [comment]
Well, yes... a naturally sortable timestamp format like YYYYMMDDHHMMSS would obviously the sanest choice. I don't think it's really worth a discussion whether that is more informative or not.

Maybe I wasn't entirely clear, I'm not suggesting you change the current implementation. I was merely wondering about the reasons behind your choice to use a sequence, and whether I would somehow run into problems if I were to try something like that.

I know about 'zfs get creation', but that is not going to help me implement the shadow copy support in Samba. A matchable timestamp in the snapshot name is a hard requirement there.

**Comment by ppbrown** [comment]
I read the link you included.

date doesnts seem like a "hard requirement" in the description of snapshot
format. They mention the format is configurable.
Seems like it is just "the default".
So you might look into that more.

You might also consider patching that shadow copy module, instead of zrep.

**Comment by tinuzz** [comment]
"the snapshot's directory is expected to be a formatted version of the snapshot time.", where the format is indeed configurable. That fact whether it contains a timestamp is not, as I read it.

My guess is, that patching the Samba module (which is written in C) is much harder than patching Zrep. I did look at the source though, and it unconditionally calls strptime() on the snapshot name, so either it contains a timestamp, or it is a constant string (which means all snapshots are named identically).

Anyway, I'm not even sure why I'm looking into this. Patching Zrep for this use case would be 15 minutes of work. I was merely wondering if I there is some great idea behind the naming convention. I'll just assume there isn't. Thank you.

**Comment by ppbrown** [comment]
there are some side effect benefits  of using sequential identifiers.  for
example if things have been failing for a while, you then get a clear idea
of the number of times in a row it has failed.
There are probably  A few others I'm forgetting.

 as far as patching the Samba side  it doesn't sound difficult at all
unless you're a complete neophyte when it comes to C code.

**Comment by darkpixel** [comment]
@tinuzz I use zrep together with zfs-auto-snapshots to generate VSS data for Windows.

I use zrep to handle backups only and that data does not get sent to VSS.  Then I use zfs-auto-snapshots to give frequent, hourly, daily, weekly, monthly, and yearly snapshot data.

I run zfs-auto-snapshot from cron like so:
```0 0 * * * /usr/sbin/zfs-auto-snapshot --quiet --syslog --label=03 --keep=45 --recursive tank```

That's my 'daily' snapshot.  The label is '03' is what I use to identify 'daily' snapshots.

This gives me snapshots in the form: ```tank@zfs-auto-snap_03-2018-04-24-0700```

For each Samba share, I have a config option: ```shadow:format = zfs-auto-snap_%S-%Y-%m-%d-%H%M```

That treats the '03' in the snapshot name as 'seconds'...and if you look closely at the VSS tab in Windows, you'll see that Windows doesn't display seconds when giving you VSS times.

It's slightly hacky, but it should give you what you want--the ability to snapshot frequently, hourly, daily, weekly, etc...and to feed that data into Windows without things being wonky and it doesn't require a change to zrep.

I hope that helps.

**Comment by tinuzz** [comment]
Hi, @darkpixel. Thanks, I found multiple suggestions on how to implement this with zfs-auto-snapshot. Maybe that is the best idea after all, to create an independent range of snapshots for Samba and let Zrep just do its own thing.

**Comment by ppbrown** [comment]
Seems like it makese the most sense to me.
Particularly since zrep is most useful if it runs frequently (multiple
times an hour) but if that is the case, then the preserved snapshots wont
be very old.
Users would more likely be interested in daily snapshots or some such.

**Comment by tinuzz** [comment]
Well, we run  Zrep in a continuous loop, so potentially multiple snapshots per minute, but I run an [external expiry tool](https://github.com/isaaceindhoven/zrep-expire) to keep snapshots in a more traditional retention schedule (like, one a minute for an hour, one every 5 minutes for 2 days, one every hour for a month, something like that). Still would be a bit many for Samba users to browse through, though. I guess an implementation outside of Zrep is best indeed.

**Comment by darkpixel** [comment]
I've found that 'split' method works best.
In Unix/Linux simplicity: Do one thing and do it well.

Zrep does an amazing job of backing up or replicating to a hot/warm standby box and expiring more than x snapshots.

zfs-auto-snap does a great job of maintaining and expiring various labeled collections of snapshots that can easily plug into Samba and be displayed via VSS to Windows users.

Combining the two would require a lot of work for very little gain.
