### ISSUE TITLE
Issues Initailizing On FreeBSD in v1.7.3

### ISSUE THREAD

**Issue by gem-pete** [bolthole/zrep#91]
Hi there, I believe this issue may be fallout from issue https://github.com/bolthole/zrep/issues/48

My environment is:
- FreeBSD-11.1-RELEASE
- zrep-1.7.3

When attempting to initialize zrep between two systems I get the following error:

```
./zrep init tank0/influxmeta influxdb1.foo.bar tank0
Setting properties on tank0/influxmeta
Error: older zfs version, cannot initialize top level pool
```

I am able to to init zrep using v1.7.2:
```
./zrep init tank0/influxmeta influxdb1.foo.bar tank0
Setting properties on tank0/influxmeta
Warning: zfs recv lacking -o readonly
Creating readonly destination filesystem as separate step
Creating snapshot tank0/influxmeta@zrep_000000
Sending initial replication stream to influxdb1.foo.bar:tank0/influxmeta
clearing mountpoint value for remote
Initialization copy of tank0/influxmeta to influxdb1.foo.bar:tank0/influxmeta complete
```

This is my first time attempting to use zrep - so if I'm missing something obvious, or if you would like me to provide additional info please let me know.

Thanks!

**Comment by cotcomsol** [comment]
I'm seeing the same issue, but it worked if I used the full destination path, i.e.:
./zrep init zroot/documents app2 zroot/documents
instead of just
./zrep init zroot/documents app2 zroot
as shown in the docs

**Comment by ppbrown** [comment]
Hello,

the error message from the first instance, is exactly as described:

"Error: older zfs version, cannot initialize top level pool"

so. the verison of ZFS on BSD that you have, lacks the features required to do a zrep directly to the top level pool. You have to specify a subpath.

Note that some people actually want to directly replicate to the top level pool. It presumed you wanted to do that, but could not. So it errored out.
