### ISSUE TITLE
cannot share 'tank/rsync': share(1M) failed on zrep init

### ISSUE THREAD

**Issue by hostingnuggets** [bolthole/zrep#93]
Hi,

I have a ZFS volume which is shared using the `sharenfs` ZFS setting and which I would like to sync over remotely using zrep. Unfortunately the initial zrep init fails as you can see below:

```
# zrep init tank/rsync remotehost.domain.tld tank-backup/rsync
Setting properties on tank/rsync
Warning: zfs recv lacking -o readonly
Creating readonly destination filesystem as separate step
Creating snapshot tank/rsync@zrep_000000
Sending initial replication stream to remotehost.domain.tld:tank-backup/rsync
cannot share 'tank-backup/rsync': share(1M) failed
Destroying any zrep-related snapshots from tank/rsync
Removing zrep-related properties from tank/rsync
Error: Error transferring tank/rsync@zrep_000000 to remotehost.domain.tld:tank-backup/rsync. Resetting
```

To me it seems that it tries on the remote host to share that backup copy which has just been sent. It does not make any sense and I think here the `sharenfs` setting should not be copied over to the remote host if this is possible. Any taughts?

My OS is Debian 9.4 using the official distrib ZoL packages from the Debian 9 APT repository.

**Comment by ppbrown** [comment]
that sounds like an accurate diagnosis.
show me the specific output of the property please, with zfs get.

**Comment by hostingnuggets** [comment]
```tank/rsync  sharenfs              rw=@192.168.1.5,rw=@192.168.1.6  local```

To be sure it is that, I am now running again a zrep init after having removed this `sharenfs` setting. I will keep you posted later as there is 1 TB to sync over...

**Comment by hostingnuggets** [comment]
So I managed to get the zrep init doing its job by temporarily removing the `sharenfs` setting, so it is really this setting which generates this problem.

**Comment by hostingnuggets** [comment]
Any news regarding this issue? It is quite an annoying one as I have to unshare my ZFS volume in order to be able to do a zrep init...

**Comment by ppbrown** [comment]
Thank you for checking back with me.
Can you give me any insight as to WHY the share fails on the replicated
volume?
After all, it looks like you are sharing via IP address. I cant see why
that would possibly fail.
SO perhaps it is failing for some OTHER reason, that is being misreported
as a shared fail.

Yes, you have proved that it is somehow triggered by the share property.
However, it seems unlikely that is the *actual* problem. so I'd like to fix
the real problem, rather than blindly hacking workarounds.

**Comment by hostingnuggets** [comment]
On my replicated server where the replicated volume gets replicated to I do not have any NFS server/daemon installed or running. So this is the reason why it can't share the replicated ZFS volume and then the whole zrep init fails.

My replicated server is a backup/archive server so I do not want to run any NFS daemon on that server.

Maybe the easiest then would be to have sort of "skip sharenfs" parameter in the config.

**Comment by ppbrown** [comment]
Unfortunately I dont see a way that is cleanly doable.
As a workaround, i suggest installing the nfs software, but just  not enabling the service.
in theory, a sensible system should allow for "configure this filesystem for sharing, when and if NFS service is enabled", but not insist that the service is active.
If it doesnt.... then maybe file a complaint with your OS vendor ;)

**Comment by ppbrown** [comment]
PS: alternative workaround: clear the property after initial init. It should not attempt to reshare after that.
