### ISSUE TITLE
REMOTE expire failed

### ISSUE THREAD

**Issue by pythonman64** [bolthole/zrep#95]
Hello,

First I'm not sure if this is an issue or just the way I am running zrep.

Zrep is being run inside a bash script started by cron.
I am using zrep to backup data from an internal to an external HDD on XigmaNAS (Nas4Free - FreeBSD). 
Zrep was failing to expire the snapshots on the external HDD after zrep sync (Getting the error "REMOTE expire failed).

The Issue:
In zrep 1.7.3 on line 429. eval returns the error: zrep: No such file or directory.
This is because zrep is not in the $PATH.

Solution:
Zrep on my system lies in /usr/local/bin/zrep
So I add this just before I run the zrep command in by bash script: 

PATH=$PATH:/usr/local/bin # Append the $PATH so zrep can be found

Then when zrep runs itself with eval, it can find itself.

Hope this is of some use!

**Comment by ppbrown** [comment]
Hello,
zrep has a particular variable for this purpose. you should set it:

ZREP_PATH

I suggest you read the top of the script for the various variables you can
set in your environment.

**Comment by pythonman64** [comment]
Thank you Philip!
