### ISSUE TITLE
Wrong snapshot name

### ISSUE THREAD

**Issue by kuon** [bolthole/zrep#96]
I am trying to pull a snapshot from a backup server.

Backup server is running freebsd and client is running linux.

When running refresh on the backup server, I get the following error:

```
# zrep refresh data/backups/yoda/kuon
cannot open 'metaphysical': dataset does not exist
cannot open 'metaphysical': dataset does not exist
cannot open 'metaphysical': dataset does not exist
cannot open 'metaphysical': dataset does not exist
cannot open 'metaphysical': dataset does not exist
Error: Canthappen: _refreshpull cant findlastsent snap
bash: line 1: zroot/data/home/kuon@zrep_000002: No such file or directory
cannot receive: failed to read from stream
Error: Unforseen error pulling snapshot metaphysical zroot/data/home/kuon@zrep_000002 from yoda
``` 

`zroot/data/home/kuon` is the fs on the client, and `data/backups/yoda/kuon` is the fs on the server.

I followed the steps described under **Backup server with an existing ZFS filesystem**

I tried to find where that `metaphysical` thing was coming from.

ksh is version `93v-` on linux (client) and `93u+` on bsd (backup server).

**Comment by kuon** [comment]
I was able to pinpoint the issue to this line:

`if getconf PATH_RESOLVE > /dev/null 2>&1 ; then`

Which does not redirect stdout in v1.7.3. But it is fixed on master.

Maybe you could release a new version?

**Comment by ppbrown** [comment]
Done:  1f9c40d
