### ISSUE TITLE
Documentation: scenario when production side dead

### ISSUE THREAD

**Issue by hostingnuggets** [bolthole/zrep#97]
Hello,

In the official documentation it would be nice to have the step-by-step procedure documented for the scenario when the production side is dead in order to know how to transfer back the snapshots from the backup side to the production side when the production side is up and running again with an empty zpool.

**Comment by ppbrown** [comment]
Fair enough. I just added a "Recovery" section. Please let me know if that is adequate

**Comment by hostingnuggets** [comment]
Thank you very much for adding this Recovery section. Now the following sentence is not quite clear to me:

``` you need to first bring the pair to a partially synced state again.```

Do you mean here manually do a `zfs send|zfs recv` from the backup to the prod host? and if yes is it not possible to do that directly with zrep? It would be nice to have this part also documented with example commands.

**Comment by ppbrown** [comment]
You dont have to do anything more than what I already put there.
i'll make the documetation clearer :)

**Comment by hostingnuggets** [comment]
Thanks it's quite clear now and simple with basically only two commands to run. I will give it a try next week!
