### ISSUE TITLE
FQDN in src-host and dest-host

### ISSUE THREAD

**Issue by hostingnuggets** [bolthole/zrep#98]
My src-host and dest-host ZFS properties set by zrep do not contain a FQDN hostname but just the hostname such as "myhostname". Shouldn't these two ZFS properties contain the FQDN instead such as "myhostname.mydomain.com"?

**Comment by ppbrown** [comment]
the dest-host property gets set to exactly what the user specifies. I believe that to always be the correct behaviour.
For the localhost... determining FQDN can be tricky, I seem to recall. If there was a universal standard for how to get it, I would use it. But as far as I'm aware, there isnt. So I dont ;)

**Comment by hostingnuggets** [comment]
Yes I found out that the script uses `uname -a` for that purpose but this does in most of the cases on Linux not include the FQDN... The best way on Linux would be to use `hostname -f` instead.
